### ISSUE TITLE
Script to execute single notebook

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#119]
We want the ability to generate the executed notebooks.  This can be run as a separate step after Jupinx.

First, lets add in a `notebooks` directory right under the `lecture-source-jl` root, and add in a `.gitignore` with `.ipynb_checkpoints` to be skipped.  This is where we will add in the `Project.toml` and `Manifest.toml` at some point as well.

First, lets have it as taking a given filename and it would just copy the file to the correct location.  e.g.
`executenotebook mynotebook.ipynb`, which would be done inside of where you run the `make jupyter command`.  It could then do something like

```
cp ./_build/jupyter/mynotebook.ipynb    ./notebooks/mynotebook.ipynb
jupyter nbconvert --ExecutePreprocessor.timeout=600 --to notebook --execute ./notebooks/mynotebook.ipynb
```
Play around with the settings to make sure it knows it can replace the existing one.

We can then get into the habit of calling `executenotebook mynotebook.ipynb` whenever we modify things.

**Comment by arnavs** [comment]
Closed with 4c03382595a6679e52447c4af91dd53a7f88dbdf.
