### ISSUE TITLE
Come up with a font check file

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#123]
List out all of the unicode characters in a `.jl` file we might want to use, then we can load it in Jupyter and Atom on various OSs.

- Check u_0, etc.

**Comment by arnavs** [comment]
Checked in a very basic one with bce75a718063f515002a912389b9a897d966b7c8 as discussed. Eventually we can add this to the style guide once we decide on a set of rules.

**Comment by jlperla** [comment]
We need to avoid combinations of non-ascii characters with underscores, tildes, etc.
