### ISSUE TITLE
Find references to Python exercises

### ISSUE THREAD

**Issue by Nosferican** [QuantEcon/lecture-source-jl#124]
A few lectures will make reference or ask for the student to write some code in Python instead of Julia.

**Comment by arnavs** [comment]
Thanks for pointing this out. Should just be able to a global grep for Python as a first pass. When we're rewriting each lecture, we can then make sure that the text is good as well.

**Comment by arnavs** [comment]
Done with 5bb412c96f12141d72215b8c0895db7eed302577. It looks like the only lecture which did this was the Dynamic Stackelberg lecture, which is probably the one you were looking at.
