### ISSUE TITLE
Meta package to make instantiating QuantEcon compatible projects easier?

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#125]
- Can we put our Manifest.toml and Project.toml into a package and easily instantiate and download it?
- Can this handle versioning well?
- What folder do we instantiate in?

**Comment by jlperla** [comment]
Is there a good naming convention?

**Comment by Nosferican** [comment]
Is the idea of the package just to have all needed dependencies and packages to be used exported automatically? Would need to make sure all no conflict between all the dependencies, but once compiled I don't think it would be to bad to have the package `@reexport` a set of dependencies used in the lectures... If so, then the lectures would only need a `using QuantEconLectures` and no more `using` or `import` statements. It would also take care of the `Project` / `Manifest` issues as the package would take care of it.

**Comment by jlperla** [comment]
No, we aren't thinking about this as a reexport.  In fact, I am not sure we really want any source-code at all?   I think it is important to separate the packages used by different parts of the notebooks so that people copy/pasting code can do that and see the proper packages.

The idea to investigate was really about finding a better way to distribute and version the Project.toml and Manifest.toml files for instantiating everything.  So, basically, they could go
```julia
using Pkg
pkg"add QuantEconLectures"
pkg"activate ?????"
pkg"instantiate; precompile"
```
At that point, they would have have an instantiated version of all of the lectures installed locally.

Then at the top of the notebooks, instead of `pkg"activate ."` and requiring the Project.toml and Manifest.toml to always be the same folder as the notebooks, they could instead go
```
using Pkg
pkg"activate ????"
```
Where the activation would be to that particular project?  Not sure this is the right approach, but there is a real issue with having to distribute .toml files along with the notebooks.

**Comment by Nosferican** [comment]
All lectures locally? As in a build script that downloads the repo and generates the `make jupyter`?

**Comment by jlperla** [comment]
No, thinking here about users of notebooks after they are distributed - not our build process.  The alternative is to force them to copy a Project.toml and Manifest.toml wherever they want to use the notebooks and call `activate .` at the top of the notebooks.  Which is OK if needed, but is very error prone.

**Comment by Nosferican** [comment]
If they use the `(v1.0) pkg` environment everything should work fine... it would be using the global Project, Manifest... the lectures should work just fine with the "wild". We can test this just in case.

**Comment by jlperla** [comment]
Actually, I think that the activation may be easier... Here is the suggested workflow:

In the installation instructions, we would tell students to run the following:
```julia
using Pkg
pkg"add QuantEconLectures"
pkg"activate QuantEconLectures"
pkg"instantiate; precompile"
```

Then at the top of every notebook we can have
```julia
using Pkg
pkg"activate QuantEconLectures"
```
and then they are using a consistent set of versions for the project.

> If they use the (v1.0) pkg environment everything should work fine... it would be using the global Project, Manifest... the lectures should work just fine with the "wild". We can test this just in case.

I have already had all sorts of projects using the base pkg environment.  And if they install or update versions, it could very easily to break.  Certainly they "could" do this (and don't need to execute that cell), but if we have the notebooks activate a set of versions then it is idiot-proof and it will always work.

**Comment by jlperla** [comment]
Try to get the most minimal package possible in econtoolkit as test.  Call it `QuantEconPackages`
- [ ] Try the setup `using Pkg; pkg"add QuantEconPackages; activate QuantEconPackages; instantiate; precompile"`
- [ ] In a new notebook, `using Pkg; pkg"activate QuantEconPackages"`

With the URL for the first.

**Comment by jlperla** [comment]
This was a failure, but the discussion generated a possible longer term discussion. See https://github.com/JuliaLang/IJulia.jl/issues/673#issuecomment-425306944
