### ISSUE TITLE
Add activation of packages to all lectures

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#128]
Add the following at the top of every lecture with code, in a separate cell right above the first set of code.
```
using Pkg
Pkg.activate(@__DIR__);
```

**Comment by Nosferican** [comment]
Any markdown above it such as:

#### Activate the project environment
```
using Pkg; Pkg.activate(@__DIR__);
```

For the setting we just need to tell them to keep one Manifest file were they have the lectures?

**Comment by jlperla** [comment]
Yes.  We can tell people about that in the setup (and hope that someone  - or us!) implements Valentin's idea about a small library to associate the projects with.  I think the setting is no important that it is worth pointing out on every notebook as a reminder - since people will copy them around.

Here is the rst text that we will want above the first use of the code - being careful with whitespace and RST, as always.
```

Activate the project environment, ensuring that the ``Project.toml`` and ``Manifest.toml`` are local

.. code-block:: julia

    using Pkg; Pkg.activate(@__DIR__); #activate environment in the notebook's location


```
We will probably want to create a mini-repo with just the project environment for  `````Project.toml`` and ``Manifest.toml`` ``` to link to, but we can wait on that and do a global search/repalce later.

**Comment by Nosferican** [comment]
Sounds good. I can work on getting the Files and adding the cell block. These will likely include the standard library `Test` for compatibility with the version with tests.

**Comment by jlperla** [comment]
We can leave the cell block modifications to one of the RAs to let you focus on rewrites/etc.  I think that `using Test` is added in a code-test block already in all files.

The files we have been maintaining are currently in https://github.com/QuantEcon/lecture-source-jl/tree/master/notebooks
and arnav wrote a simple script to copy a build file there and run it through `nbconvert`  https://github.com/QuantEcon/lecture-source-jl/blob/master/execute-notebooks.sh

This is all temporary, but the current `_build` directory is not versioned, and we don't necessarily want to rewrite the .ipynb files when we run them.  Lets take further discussions onto slack

**Comment by arnavs** [comment]
Yes, `using Test` is added as a `:class: test` block in all files.

**Comment by arnavs** [comment]
Done at 7762b6d. Just copied and pasted that precise block of text above the first `code-block`, minding syntax.
