### ISSUE TITLE
Move the Project.toml and Manifest.toml to the build-location

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#129]
There are two ways to do this:

- First, see if you can add a line to the makefile so that it copies them from the current `notebooks` directory when `make jupyter` is run.  This is ideal
- If not, then:
  - add the `_build/jupyter` or whereever the notebooks aree generated to git.
  - ignore all `ipynb`, etc. files in there
  - Put the `toml` files there, and make sure they are in git, as they would be the master versions
  - Remove the `toml` files from git in the `notebooks` directory, so we only have 1 copy
  - Add a line into the bash script for running notebooks which atuomatically copies the toml files into `notebooks`, and make sure they are ignored in git.

**Comment by arnavs** [comment]
Done at 193a592. We add `bash -c "cp notebooks/*.toml _build/jupyter"` to the Makefile.
