### ISSUE TITLE
Script to execute all of the notebooks, skipping ones that are not modified

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#130]
Lets modify the current file https://github.com/QuantEcon/lecture-source-jl/blob/master/execute-notebooks.sh

Or perhaps rename it to `execute-notebook.sh` and have a new one `execute-notebooks.sh` which will call it.

The basic goal of this is to run all of the notebooks in the `_build/jupyter` directory and put them in the `/notebooks` directory.  But we only really need to run the `nbconvert` if the `_build/jupyter/MYFILE.ipynb` has been modified since the last time the script was executed.

A suggested approach:
- Consider modifying the  https://github.com/QuantEcon/lecture-source-jl/blob/master/execute-notebooks.sh script so that it takes a relative path to the file instead of putting in the `/_build/jupyter` on its own.  Test to see if it is better, but, for example, changing the line to:
```
\cp $1 ./notebooks/$1 # Move first argument to the right folder. Will overwrite. 
```
- At the beginning of running the script, if there is a `./notebooks/timestamp.txt` or whatever file, then load the timestamp.
- If no timestamp is there, then the assumption will be that things have never been run... maybe set the timestamp to `0` or something so that filtering is easy.
- Get a list of all `./_build/jupyter/*.ipynb` with the timestamp
- Filter out from that list of files anything where the timestamp is < the stored timestamp... and if there is no timestamp loaded, then don't filter.
- Replace or save the current timestamp in ` ./notebooks/timestamp.txt`
- Run the modified https://github.com/QuantEcon/lecture-source-jl/blob/master/execute-notebook.sh script on each of the filtered list of files.

Then when you put this in git, make sure to ignore the timestamp files and any intermediate files you create in the process.

**Comment by arnavs** [comment]
Done as of 3c747179c3414a5923be56c545ce209f183bbe13. Still need to test rigorously, but from what I've seen the script behaaves as expected. In particular: 

* It will create a file in the `notebooks/` directory if none of the same name exists. 
* It will overwrite that file if the source in `_build/jupyter/` is newer. 
* It won't overwrite if the source in `_build/jupyter/` is older. 
* It will swallow any Jupyter errors. 

### Usage 

From the main directory (where we run `make jupyter`), run `./run-all-notebooks.sh`. 

### Sample Output 

For the full conversion: 

```
 lecture additive_functionals.ipynb
 target exists; checking timestamps...
 replacing now
[NbConvertApp] Converting notebook ./notebooks/additive_functionals.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: julia-1.0
Starting kernel event loops.
[NbConvertApp] Writing 46701 bytes to ./notebooks/additive_functionals.ipynb
 conversion complete
 lecture aiyagari.ipynb
 target exists; checking timestamps...
 replacing now
```

If the target exists: 

```
 lecture additive_functionals.ipynb
 target exists; checking timestamps...
 target is not older than source.
 lecture aiyagari.ipynb
 target exists; checking timestamps...
 target is not older than source.
 lecture amss.ipynb
 target exists; checking timestamps...
 target is not older than source.
 lecture arellano.ipynb
 target exists; checking timestamps...
 target is not older than source.
```

If the target doesn't exist:

```
 lecture additive_functionals.ipynb
 target does not exist; creating now.
[NbConvertApp] Converting notebook ./notebooks/additive_functionals.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: julia-1.0
```

To address a question @jlperla had about lag, there's no caching, so the only timestamps that matter are those that pertain to the files when the loop gets to them. So, if we start this script at 11:00, edit `wald_friedman` at 11:40, and then the script only gets there by `11:50`, we should be OK. 

Will close for now, pending any errors in additional testing.
