### ISSUE TITLE
Add missing packages for the notebooks

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#131]
When I use the project files, I am missing `LaTeXStrings`, which breaks current notebooks.
I realize that we will eventually get rid of all latexstrings, but we are not there yet.
- [ ] Until then, can you add it to the Project.toml and the Manfiest.toml for the notebooks?
- [ ] Also add `GR` while you are at it, so that it precompile.
- [ ] Give the new files to Jasmine to get these built into the syzygy activation, if at all possible.

**Comment by jlperla** [comment]
Also consider doing an `] up` on the activated project and doing a quick test.

**Comment by arnavs** [comment]
Added these packages. Ran `] up` and nothing changed, I suspect because we grabbed these so recently. 

@jasminefish000, see above about the Syzygy. Basically, the TOML on the server is good to go.

**Comment by Nosferican** [comment]
I found that a few packages do not get picked up until the function is call... For example, `PyPlot`, `PyCall`, `LaTeXStrings`... so best to clean up and run it an environment with the global environment only having `IJulia`.

**Comment by arnavs** [comment]
Sorry, not sure what you mean. If you `run all cells` in a few notebooks, why wouldn't that be enough?

**Comment by Nosferican** [comment]
I mean running all cells should work. Looking at `using` and `import` statements won't because of what I described...
Also, I found that unicode works pretty good in my applications as a replacement of LaTeXStrings.

**Comment by jlperla** [comment]
@Nosferican You mentioned that you had some success with unicode in GR?  I was told it is very platfrom dependent, so I think we should add the tests to https://github.com/QuantEcon/lecture-source-jl/blob/master/unicode.jl test, with a new `Plots` based execution.  Then we can run it on different OS/etc. Let me add an issue.
