### ISSUE TITLE
Expectations Pass

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#133]
Go through the lectures and, wherever possible, replace homebrewed expectations (i.e., the dot product of something with a `pdf` vector) with the `E()` operator from `QuantEcon/Expectations.jl`. 

Some lectures to check: 

- [ ] Wald-Friedman 
- [ ] McCall 
- [ ] IFP 
- [ ] Classical Filtering 
- [ ] Aiyagari

**Comment by arnavs** [comment]
@yolsever Just a reminder of the task, the goal is to rip out discrete home-brewed expectations (i.e., we're taking a PDF function from some distribution, broadcasting it across some state vector, and dotting it with values, like `f = x -> pdf(dist, x); pdf_vec = f.(states); E = dot(f, vals)` and replacing it with the expectations operator. 

The above list is just a starting point. Also, if you find that either (a) we can't really do this without rewriting the lecture significantly, or (b) this is above your pay grade, both of those are valid results.

**Comment by arnavs** [comment]
@yolsever see 117e687 (which moves the `mccall_bellman_iteration.jl` to expectations) for an example. In particular, when we write `E = expectations(dist, nodes = w_vec)` we're using a specific method (that allows users to specify nodes), so we can later replace the `pdf.(dist, w_vec)`. We also had to tweak some argument signatures and type signatures to eliminate references to the `p_vec`.

See what you can do, but if you find something is giving you a hard time, just flag that lecture and move on.

**Comment by arnavs** [comment]
Closing this because we've replaced all the ones we can without completely gutting the lecture (i.e., `amss`, `ifp`).

**Comment by Nosferican** [comment]
Leave a list of the ones not replaced: `ifp`, `amss`, etc.
