### ISSUE TITLE
Add Unicode in GR/Plots test for checking platform support

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#137]
@Nosferican : Can you tell us what you tried for the unicode in plotting labels, etc.? or directly add a test to https://github.com/QuantEcon/lecture-source-jl/blob/master/unicode.jl

Then we can run it in different OSs to see if they are in fact valid.  The GR maintainer told me that unicode support is very spotty due to the all the backends.
cc: @arnavs

**Comment by Nosferican** [comment]
I made this with `Plots.pyplot()`
https://imgur.com/a/zbAbggK

**Comment by jlperla** [comment]
I think pyplot works fine the unicode.  But we need to use GR.

**Comment by jlperla** [comment]
I checked on Jupyter, and even somethign as simple as
```
plot(1:3, 1:3, title = "α")
```
Does not work.  I will close.  We cannot use unicode in titles/labels until GR supports it, or we change plotting backends.
