### ISSUE TITLE
Interpolations pass

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#146]
Change everything to use Interpolations.jl and remove references to the QuantEcon

**Comment by arnavs** [comment]
Checklist for the `LinInterp`:

- [ ] Wald-Friedman
- [ ] Robustness 
- [ ] Optimal Growth 
- [ ] `opt_tax_recur`
- [ ] `odu`
- [ ] Lucas Model 
- [ ] Job V 
- [ ] `egm_policy_iter`
- [ ] `coleman_policy_iter`
- [ ] `amss` *
