### ISSUE TITLE
Dev Environment

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#148]
From earlier discussion with @jlperla. Implementing a set of tools that new RAs/collaborators could use to quickly start working on the lectures. Wishlist could include: 

- [ ] Notebook testing scripts (individual and all). 
- [ ] Scripts to grab dependency information (which packages are used, how often and where?)
- [ ] Docker image?

**Comment by jlperla** [comment]
- [ ] snippets for vscode and atom.  For example, https://github.com/vscode-restructuredtext/vscode-restructuredtext/blob/master/snippets/snippets.json is close with a few additional ones or modifications

**Comment by mmcky** [comment]
- [ ] Documentation and Style guide

**Comment by arnavs** [comment]
@mmcky Do you mean writing some sort of tool that would enforce the style guide?
