### ISSUE TITLE
Ranges pass

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#149]
After @Nosferican finishes https://github.com/JuliaLang/Compat.jl/issues/631  we can search for all `ranges` and use the newer syntax

**Comment by arnavs** [comment]
Once https://github.com/JuliaLang/Compat.jl/pull/633 is merged, we can make this into an RA issue. Basically tell them to get rid of the `stop = X` kwargs?

**Comment by jlperla** [comment]
Pretty much.  So
```
range(a, stop = b, length = 10)
```
to
```
range(a, b, length = 10)
```

**Comment by jlperla** [comment]
I think that we should directly have `using Compat` instead of re-exporting from `using QuantEcon`.  In general, we are getting to the point where we don't need too many functions from it.  And the eventual goal will be to be able to split out the crucial features into smaller packages.

**Comment by jlperla** [comment]
With the latest `Compat.jl` this is now possible.  We should probably get in the habit of putting a `using Compat` at the top of most files when we go through this pass.

**Comment by arnavs** [comment]
Done at ec7e80944c9734437780cd04bb9d4d0083d3adf9. Will add the compat in the next commit and then we're good to go.
