### ISSUE TITLE
Global plot color settings

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#150]
Right now a lot of the plots are along the lines of
```
plot(x, color = "blue")
```

Is the `color = "blue"` really necessary, and is there a better way to make a global setting change right below where the `using Plots; gr(...)` is used?  If so, lets get rid of them globally.

**Comment by jlperla** [comment]
I think it is just
```
default(color = "blue")
```
- But we need to make sure that using the option doesn't mess up the other color choices.
- My basic feeling may be that it isn't worth it, and leaving as the default color is good enough.  Again, if so we should just remove globally

**Comment by Nosferican** [comment]
The `palette` can be used to specify these.

**Comment by jlperla** [comment]
Perfect.  I think for now maybe we should just avoid finicky color settings in order to keep the code looking clean, and we can make global `palette` changes at the top of the file if we want to.

**Comment by jlperla** [comment]
Also, consider
```
default(width = 2)
```
