### ISSUE TITLE
Code-Math Integration

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#153]
We should make sure that (a) code that's directly implementing math is commented with an equation number and (b) as a corollary, all significant equations are numbered. Example of a lecture with non-numbered equations is Wald-Friedman.

**Comment by Nosferican** [comment]
Can you post an example of those with the numbered equations and label/references?

**Comment by jlperla** [comment]
To add in equations we have to put in a label, such as 
```
.. math::
    :label: fixed_point_map

    x = 1
```

And we can add in the labels as required to create equation numbers


We do not have a way to have the equation numbers automatically spliced into the code blocks, so we need to manually put them in.  The idea is to put in the comment, so if the labelled equation there is `(1)` then the relative julia code would be
```julia
x = 1 #(1)
```
But I don't think this is a good issue as currently written.Lets hold off on doing this globally for now, and just do it case by case for now.  There is a chance we can have it automatically generate.

**Comment by arnavs** [comment]
Closing this, we can replace it later with an actionable issue.
