### ISSUE TITLE
Roots pass

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#157]
Move to https://github.com/JuliaMath/Roots.jl instead of the QuantEcon.jl features.

I think the ones to look for in the code are all of the bracketed root functions
- http://quantecon.github.io/QuantEcon.jl/latest/api/QuantEcon.html#QuantEcon.bisect-Union{Tuple{Function,T,T},%20Tuple{T}}%20where%20T%3C:AbstractFloat
- http://quantecon.github.io/QuantEcon.jl/latest/api/QuantEcon.html#QuantEcon.brent-Union{Tuple{Function,T,T},%20Tuple{T}}%20where%20T%3C:AbstractFloat
- http://quantecon.github.io/QuantEcon.jl/latest/api/QuantEcon.html#QuantEcon.brenth-Union{Tuple{Function,T,T},%20Tuple{T}}%20where%20T%3C:AbstractFloat

To be clear, though, I am not sure that `Roots.jl` is always better, just that it is where we should add in new code and be able to swap out algorithms easily.  It will also be much easier to tweak `find_zero` to support `BigFloat`, etc.

In fact, porting over some of those QuantEcon.jl routines to Roots.jl might be a good project for a student.  Or maybe implementing "TOMS Algorithm 748" or something similar to see if it works well.

**Comment by arnavs** [comment]
Done at 7370c59. The Roots.jl solutions were close enough to the QuantEcon.jl that regression tests didn't need amending.
