### ISSUE TITLE
Move to :png with GR

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#171]
From teaching, students frequently forget to `Trust` the notebook.  The main place this causes issues is that the graphs disappear when they reopen it.

I think the solution is to use the `png` wherever plots comes up.  That is,
```julia
using Plots
```
globally becomes
```julia
using Plots
gr(fmt=:png)
```
--------------------
## Getting Started with Julia
- [ ] [Setting up your Julia Environment](https://lectures.quantecon.org/jl/getting_started.html)
- [x] [An Introductory Example](https://lectures.quantecon.org/jl/julia_by_example.html)
- [x] [Julia Essentials](https://lectures.quantecon.org/jl/julia_essentials.html) and more material
- [x] [Fundamental Types](https://lectures.quantecon.org/jl/julia_arrays.html)  with more material
- [x] [Introduction to Types and Generic Programming](https://lectures.quantecon.org/jl/types_methods.html)

## More Programming and Software Engineering Principles
- [ ] Generic Programming
- [ ] [The Need for Speed](https://lectures.quantecon.org/jl/need_for_speed.html)
- [ ] [Plotting in Julia](https://lectures.quantecon.org/jl/julia_plots.html)
- [x] [Useful Libraries](https://lectures.quantecon.org/jl/julia_libraries.html)

## Tools and Techniques 
- [x] [Linear Algebra](https://lectures.quantecon.org/jl/linear_algebra.html)
- [ ] [Orthogonal Projections and their Applications](https://lectures.quantecon.org/jl/orth_proj.html)
- [x] [LLN and CLT](https://lectures.quantecon.org/jl/lln_clt.html)
- [ ] [Linear State-Space Models](https://lectures.quantecon.org/jl/linear_models.html)
- [x] [Finite Markov Chains](https://lectures.quantecon.org/jl/finite_markov.html)
- [ ] [Continuous State Markov Chains](https://lectures.quantecon.org/jl/stationary_densities.html)
- [x] [A First Look at the Kalman Filter](https://lectures.quantecon.org/jl/kalman.html)

## Dynamic Programming 
- [ ] [Shortest Paths](https://lectures.quantecon.org/jl/short_path.html)
- [x] [Job Search I: The McCall Search Model](https://lectures.quantecon.org/jl/mccall_model.html)
- [x] [Job Search II: Search and Separation](https://lectures.quantecon.org/jl/mccall_model_with_separation.html)
- [ ] [A Problem that Stumped Milton Friedman](https://lectures.quantecon.org/jl/wald_friedman.html)
- [x] [Job Search III: Search with Learning](https://lectures.quantecon.org/jl/odu.html)
- [x] [Job Search IV: Modeling Career Choice](https://lectures.quantecon.org/jl/career.html)
- [x] [Job Search V: On-the-Job Search](https://lectures.quantecon.org/jl/jv.html)
- [x] [Optimal Growth I: The Stochastic Optimal Growth Model](https://lectures.quantecon.org/jl/optgrowth.html)
- [ ] [Optimal Growth II: Time Iteration](https://lectures.quantecon.org/jl/coleman_policy_iter.html)
- [x] [Optimal Growth III: The Endogenous Grid Method](https://lectures.quantecon.org/jl/egm_policy_iter.html)
- [ ] [LQ Dynamic Programming Problems](https://lectures.quantecon.org/jl/lqcontrol.html)
- [x] [Optimal Savings I: The Permanent Income Model](https://lectures.quantecon.org/jl/perm_income.html)
- [x] [Optimal Savings II: LQ Techniques](https://lectures.quantecon.org/jl/perm_income_cons.html)
- [x] [Consumption and Tax Smoothing with Complete and Incomplete Markets](https://lectures.quantecon.org/jl/smoothing.html)
- [x] [Optimal Savings III: Occasionally Binding Constraints](https://lectures.quantecon.org/jl/ifp.html)
- [ ] [Robustness](https://lectures.quantecon.org/jl/robustness.html)
- [x] [Discrete State Dynamic Programming](https://lectures.quantecon.org/jl/discrete_dp.html)

## Multiple Agent Models
- [x] [Schelling's Segregation Model](https://lectures.quantecon.org/jl/schelling.html)
- [x] [A Lake Model of Employment and Unemployment](https://lectures.quantecon.org/jl/lake_model.html)
- [ ] [Rational Expectations Equilibrium](https://lectures.quantecon.org/jl/rational_expectations.html)
- [x] [Markov Perfect Equilibrium](https://lectures.quantecon.org/jl/markov_perf.html)
- [ ] [Asset Pricing I: Finite State Models](https://lectures.quantecon.org/jl/markov_asset.html)
- [x] [Asset Pricing II: The Lucas Asset Pricing Model](https://lectures.quantecon.org/jl/lucas_model.html)
- [ ] [Asset Pricing III: Incomplete Markets](https://lectures.quantecon.org/jl/harrison_kreps.html)
- [ ] [Uncertainty Traps](https://lectures.quantecon.org/jl/uncertainty_traps.html)
- [x] [The Aiyagari Model](https://lectures.quantecon.org/jl/aiyagari.html)
- [x] [Default Risk and Income Fluctuations](https://lectures.quantecon.org/jl/arellano.html)
- [ ] [Globalization and Cycles](https://lectures.quantecon.org/jl/matsuyama.html)

## Time Series Models
- [x] [Covariance Stationary Processes](https://lectures.quantecon.org/jl/arma.html)
- [ ] [Estimation of Spectra](https://lectures.quantecon.org/jl/estspec.html)
- [ ] [Additive Functionals](https://lectures.quantecon.org/jl/additive_functionals.html)
- [x] [Multiplicative Functionals](https://lectures.quantecon.org/jl/multiplicative_functionals.html)
- [x] [Classical Control with Linear Algebra](https://lectures.quantecon.org/jl/lu_tricks.html)
- [ ] [Classical Filtering with Linear Algebra](https://lectures.quantecon.org/jl/classical_filtering.html)

## Dynamic Programming Squared
- [ ] [Dynamic Stackelberg Problems](https://lectures.quantecon.org/jl/dyn_stack.html)
- [ ] [Optimal Taxation in an LQ Economy](https://lectures.quantecon.org/jl/lqramsey.html)
- [x] [Optimal Taxation with State-Contingent Debt](https://lectures.quantecon.org/jl/opt_tax_recur.html)
- [x] [Optimal Taxation without State-Contingent Debt](https://lectures.quantecon.org/jl/amss.html)

**Comment by arnavs** [comment]
Done at 62065ce.
