### ISSUE TITLE
Make the set up lines a static file

### ISSUE THREAD

**Issue by Nosferican** [QuantEcon/lecture-source-jl#175]
Similar to the `lecture_howto_jl.raw`, the set up is repeated across each lecture. I think it would be a good candidate for a static file.

**Comment by arnavs** [comment]
I think we can also plug this into a build option to specify, say, a tag of the QuantEconLecturePackages to be globally applied.

**Comment by arnavs** [comment]
Closing this issue, since now we can discuss this in the PR.
