### ISSUE TITLE
No longer require Ref for broadcasting distributions

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#177]
Bug report from a student!

It appears that Distributions is now "broadcast friendly".  We should look for uses of `Ref` with broadcasting with it (e.g. `pdf.(Ref(d), [1.0, 3.0])` no longer requires the `Ref`) and remove it.  This might be a good time to review all uses of `Ref(` in the notes, since others might have changed.

**Comment by arnavs** [comment]
Done at bf5efe5.
