### ISSUE TITLE
Change to Interpolations.jl

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#180]
See https://github.com/QuantEcon/lecture-source-jl/pull/159

I didn't realize we were so close to running the HTML output. This means we need to ensure we get rid of other interpolation libraries sooner than we we thought.

See the PR. 

https://github.com/QuantEcon/lecture-source-jl/pull/159

**Comment by Nosferican** [comment]
Could we have an update on this tracker?

**Comment by arnavs** [comment]
@Nosferican All that's left is `odu` and `amss`, which I believe you're working on

**Comment by Nosferican** [comment]
Can you do `odu`, just the interpolations? That should help me for doing the Parameters pass on that one.

**Comment by arnavs** [comment]
Yeah, on it.

**Comment by jlperla** [comment]
Is this issue complete?  I also saw mention of the Interpolations pass in #159 , if that depends on this?
