### ISSUE TITLE
Remove Interact.jl dependency in lectures

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#181]
The only lecture I know that used Interact.jl was `matsuyama.rst`

For the most part, I think that moving towards heavily interactive notebooks is a valuable target, but I think it should be a planned and comprehensive change, and we would need to think through how interactive notebooks sync with staticly generated code.

Since it doesn't seem essential jere, why don't we comment out the interactive code for now and change the https://lectures.quantecon.org/jl/matsuyama.html#exercise-2 code to just display the starting point values in the `create_attraction_basis` model.

**Comment by arnavs** [comment]
Done at 0a81451. We should actually just remove the Exercise 2 solution, because it's just an interactive version of the plots in Exercise 1 (i.e., instead of different `rho` plots, show us a slider for `rho`). There actually isn't a distinct Exercise 2 task in the lecture.
