### ISSUE TITLE
"Test Notebooks" script

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#184]
Parallel to the `./run-all-notebooks.sh`, it would be nice to have CLI tools to test whether things pass for a given notebook or all notebook. Relates to #148.

**Comment by jlperla** [comment]
OK, but it is premature to work on this before discussing the automated checking and building with matt.

**Comment by jlperla** [comment]
I am closing this.  We will need to discsus separate build checking/etc. instead.
