### ISSUE TITLE
Invalid kernels for index files

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#185]
Do a fresh build of the `rst` and you will see a warnings like
```
/mnt/c/Users/jlperla/Documents/GitHub/lecture-source-jl/rst_files/index.rst:: WARNING: Invalid jupyter kernels. jupyter_kernels: {'python3': {'kernelspec': {'display_name': 'Python', 'language': 'python3', 'name': 'python3'}, 'file_extension': '.py'}, 'julia': {'kernelspec': {'display_name': 'Julia 1.0.0', 'language': 'julia', 'name': 'julia-1.0'}, 'file_extension': '.jl'}}, lang: julia
```
I note that the display name here is `Julia 1.0.0`, for example, among other issues.  I don't know if this all causes any trouble since there is no code to run, but warnings should generally be investigated.

**Comment by arnavs** [comment]
Can't reproduce this error on my 1.0.1 machine, but I fixed the display name to reflect the kernel name (`1.0`). 619c3c2
