### ISSUE TITLE
Broken StatPlots for Distributions issue

### ISSUE THREAD

**Issue by Nosferican** [QuantEcon/lecture-source-jl#188]
Related issue affecting the notes, https://github.com/JuliaPlots/StatPlots.jl/issues/195.

**Comment by jlperla** [comment]
@Nosferican @arnavs : This was with v0.3.1 of https://github.com/QuantEcon/QuantEconLecturePackages?

**Comment by arnavs** [comment]
@Nosferican What lecture did you find an issue in? I checked this for both of the lectures that use `StatPlots` and they look fine.

**Comment by Nosferican** [comment]
In the re-write of a lecture to use `StatPlots` for `plot(::Distribution)`. For those, we just need to make sure that we replace `using Plots` with `using StatPlots`

**Comment by arnavs** [comment]
Michael said the solution is to load `StatPlots` before using `Plots`. Even if the second `Plots` is useless, I'd like to have it to distinguish the two packages. I tested it on your MWE in that issue, and it works. 

Will close now, though, since we know what to do.

**Comment by Nosferican** [comment]
The recommended way style is
```
using StatPlots, Distributions
plot(Normal())
```
No `using Plots` as `StatPlots` `@reexports` `Plots`.

**Comment by arnavs** [comment]
Recommended by who? To quote the maintainer's response from that issue: 

> You should never load Plots before StatPlots though, so that is the solution to the issue today.

    The solution in the longer run will most likely be to not reexport Plots, and thus require you to load Plots.

**Comment by Nosferican** [comment]
StatPlots reexports Plots. Why would one call a package already exported? Is common practice not to load packages already exported from others. That is the case in most if not ecosystem that use Reexport.

**Comment by jlperla** [comment]
Put a comment in that says something like: `using Plots` isn't necessary when `using StatPlots` and that is good enough until they change the package.
