### ISSUE TITLE
High degradation of plot quality with GR

### ISSUE THREAD

**Issue by Nosferican** [QuantEcon/lecture-source-jl#189]
Some plots that have been ported from other backends to GR make the new plots utterly useless. Some can be "fixed" through a re-write while others simply need a different approach given the limitations of the backend. Opening this issue to keep track of the decisions.

**Comment by jlperla** [comment]
Can you give an example of this?  Some of the problems are because Plots.jl had some bugs with sizes of labels/etc. that are being fixed.

Also I think we need to make a decision on whether we go with `png` or `svg`.... At this point
`gr(fmt=:png)` seems to solve a lot of issues with the sizes, and it also makes the notebooks show pictures without trusting it first.  A major benefit for users.

Are there any downsides?

**Comment by Nosferican** [comment]
![clt3d](https://user-images.githubusercontent.com/2529329/47309533-4cb0de00-d5fa-11e8-91ec-045175b4c6d0.png)
![gr](https://user-images.githubusercontent.com/2529329/47309535-4f133800-d5fa-11e8-9ca1-6f07f64b996e.png)

**Comment by jlperla** [comment]
Both are with GR, and the second one is the version with `png`?  Are all of the major issues you are seeing with 3D plots

**Comment by arnavs** [comment]
If I recall, we talked about these issues before and they all bound to 3D plots only.

**Comment by jlperla** [comment]
There aern't all that many 3D plots, and some of them could even be shown as a sequence of 1D plots if required.

Why not identify all of the terrible plots for now in a checklist here, and then we can one-by-one see if  we can make it work with GR in its current form.

BTW, I had a student today with terrible (2D) plots, but when he used the `gr(fmt = :png)` it started working again.  Should we make a global change?  If nothing else, it means that when we get sent notebooks from students we can actually see the graphs without `Trust`

**Comment by arnavs** [comment]
@jlperla I think we already made the global change in #171.

**Comment by jlperla** [comment]
Great.  Even if `png` is slightly inferior to `svg`, it is nice to have consistency for testing purposes.  But yeah, why don't we keep a list of ugly figures to fix up there.  This is high priority, especially if the HTML rendering comes soon'ish.

**Comment by Nosferican** [comment]
The first one is the 0.6 from the webpage. The second one is with `gr(fmt=:png)`.
This is another example,
From webpage
![lapro](https://user-images.githubusercontent.com/2529329/47312828-0613b180-d603-11e8-9ebc-f36af71f23ab.png)
After porting to GR
![la](https://user-images.githubusercontent.com/2529329/47312835-09a73880-d603-11e8-9e82-bf39e43af072.png)
After re-write
<img width="345" alt="screen shot 2018-10-22 at 2 00 41 pm" src="https://user-images.githubusercontent.com/2529329/47312861-19268180-d603-11e8-80ac-52469ee4b117.png">

**Comment by jlperla** [comment]
OK.  So enumerate the ones that look bad and we can see if there are ways to make it look good... or get it "good enough" and wait a year until `Makie.jl` is ready.  Using multiple backends isn't an option, since the whole point of consolidating on `GR` was that it is the only stable one with idiot-free setup instructions.

**Comment by ajozefiak** [comment]
Most of the plots in #67 are fine, where there are only two exceptions that haven't been converted from PyPlot/Gadfly to Plots, precisely for this issue.

Those two are: Globalization and Cycles, and Jov Search IV: Modelling Career Choice

**Comment by arnavs** [comment]
Did a lot of these just now. Linear Algebra is pending outcome of slack. Job Search IV is assigned to @ajozefiak. Once those two are done, we can close.

**Comment by ajozefiak** [comment]
I'll have a look later and see if I missed any degraded plots, but I think the list above is complete.

**Comment by arnavs** [comment]
Closing this since I think all plots are now "good enough." @ajozefiak, if you find any more degraded plots, let me know and we can take a look and/or re-open.
