### ISSUE TITLE
Organization of github PRs for new lectures

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#194]
I need to start having new lectures and major rewrites as PRs so we don't have half-finished or orphaned material when generating HTML.  New lectures can be setup as a WIP with the new file and the changes in the accompanying index.

A few of the things to do:
- [x] https://github.com/QuantEcon/lecture-source-jl/blob/master/rst_files/index_getting_started_julia.rst
  - That is wrong.  It should end with `introduction_to_types`  The rest are in the "more" section
  - I don't anticipate any more lectures in there.
- [x] https://github.com/QuantEcon/lecture-source-jl/blob/master/rst_files/index_more_julia.rst
  - This is where the additional lectures material will go
  - Leave the `generic_programming` in there, since I will finish it today and work off of master.
  - Otherwise, only the `need_for_speed` is sufficiently coherent and updated to be generated for the html.
  - I think the others should all be removed, where the addition to the index there is part of the PR for the lecture itself.

Which leads to the high priority additional lectures
- [x]  PR for https://github.com/QuantEcon/lecture-source-jl/blob/master/rst_files/version_control.rst where we will put the Git tutorials, with accompanying change to the index files
- [x] same for https://github.com/QuantEcon/lecture-source-jl/blob/master/rst_files/testing.rst where we will put in unit testing
- [x] for https://github.com/QuantEcon/lecture-source-jl/blob/master/rst_files/tools_editors.rst where we will put the material Atom and the REPL, creating project files/etc.
- [x] PR for https://github.com/QuantEcon/lecture-source-jl/blob/master/rst_files/more_types.rst  with accompanying change to the index files

And the lower priority ones, which we should have a PR for but are unlikely to be finished off anytime soon
- [x] https://github.com/QuantEcon/lecture-source-jl/blob/master/rst_files/more_types.rst  
- [x] https://github.com/QuantEcon/lecture-source-jl/blob/master/rst_files/plots.rst for updates on the plotting ecosystem
- [x] https://github.com/QuantEcon/lecture-source-jl/blob/master/rst_files/file_io.rst for file/io, using bigdata type files, loading R datasets, etc.
- [x] https://github.com/QuantEcon/lecture-source-jl/blob/master/rst_files/packages.rst for additional packages in the julia ecosystem
- [x] https://github.com/QuantEcon/lecture-source-jl/blob/master/rst_files/need_for_speed.rst a rewrite of this for the newest Julia.

**Comment by arnavs** [comment]
Done @jlperla
