### ISSUE TITLE
Better formatting of docstrings in the lecture notes

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#197]
There are a few places where we use the `?command` to get the docstring.  They don't format very well in IJulia (see https://github.com/JuliaLang/IJulia.jl/issues/766#issuecomment-432392604 )

There isn't that much we can do except:
1. Live with it.
2. Manually copy and modify the docstring output into a markdown cell to simplify the formatting (i.e. remove the H1)
3. Use a hacky implementation to only show a certain number of lines.  The one provided in slack is 
```julia
docs(word; lines = 15) = Markdown.parse(join(split(string(include_string(Main, "@doc $word")), '\n')[1:min(lines, end)], '\n'))
docs("diff", lines = 6) # to call it
```

**Comment by jlperla** [comment]
One option for (2) above is to put the code in a `:class: no-execute` in the code-block, and then just copy the segment of the docstring we need...

**Comment by arnavs** [comment]
@jlperla We could also use a `:class: collapse` block, which only shows a bit of the text (but lets you expand it out if you want).

**Comment by jlperla** [comment]
Tried it, but I did it wrong or the `:class: collapse` is not supported in jupyter output?

**Comment by jlperla** [comment]
I am moving this to v1.0 because I think it is necessary.  The solution, though, might just be avoid the executable cell, manually copy in and modify the text and say it has been lightly edited.
