### ISSUE TITLE
Fix links with underscores

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#206]
In the generic programming section, we have links such as
```
`Field <https://en.wikipedia.org/wiki/Field_(mathematics)>`_
```
 in the RST.  I think these may be broken due to the underscore.  Lets figure out how to fix these in rst

**Comment by arnavs** [comment]
I think the underscore is rST syntax for an anonymous link. But it might not work if there’s punctuation after it or something. Will check:

**Comment by Nosferican** [comment]
Usually those might be indicating to opening the link in a new tab (easy test of that theory).

**Comment by jlperla** [comment]
My guess is that there is a way to escape characters in RST...
