### ISSUE TITLE
Plan for github lecture

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#208]
Always link to Github Desktop and github help.

Some ideas:
- reiterate the github free for academic link
- Creating private repos and adding in private collaborators
- GithubDesktop (how they could git)
- How to a create a new repo, how to clone
- How to push up changes,
- Reverting changes
- Issues and changes
- Explain branches and what they are for
  - How to switch branches/etc. for using other peoples branches
  - (advanced): how to create their own branches
- Common github errors and workarounds
- Show how to deal with a merge conflict (use Atom)
- Explain what a Pull Request is for reading them, comments, etc. and how to change to a Pull Request branch
- Show: make a small PR only from the github webpage (e.g. small typos, create the PR from github).
- Action: find something they want to fix in an existing project.  How to do it?
  - Create a Pull Request  (branch if required)
  - How to suggest reviewers? How to put commits up, etc.
  - Merge conflicts, show it.
  - Making comments on individual lines of code, reviewing code
- `gitignore` 
- Showing the history in the GithubDesktop but also traversing the history in the commits...

**Comment by Nosferican** [comment]
A friend developed this [Git Material](https://bi-sdal.github.io/training/version-control.html) which can be helpful for it.

**Comment by jlperla** [comment]
Very cool.  @arnavs , great to see what other people were covering, but be careful not to take anythign directly due to copyrights.

For the most part, I think the goal here was "github desktop for dummies" (i.e., nothing in the terminal) with pointers to the "real" git materials for people who get more advanced stuff.

**Comment by arnavs** [comment]
```
Setup 
===========
GitHub Setup
	- Make an account 
	- Student Developer Pack: https://education.github.com/pack (free Travis, private, etc.)
	- Researchers: https://help.github.com/articles/about-github-education-for-educators-and-researchers/

GitHub Desktop Setup 
	- https://desktop.github.com
	- Configure with local git, etc. 

GitHub 101
	- Repo: https://github.com/QuantEcon/Expectations.jl. Corresponds to an overall project 
	- Commit: Individual DIFF. Represents a modular work unit, and some metadata 
	- Repos as historyful objects. 
	- Branches: Parallel development flows (CAVEAT)
	- Issues 
	- gitignore 
	- README.md, LICENSE.md

Versioning your own projects
=================================

Creating a Repo 
	- De Novo (Website)
	- README, LICENSE, .gitignore  
	- Cloning and Download/Open in Desktop  

Making and Committing Changes
	- Opening in Atom  
	- Making Changes
	- Adding Files to Commit 
	- Making Commit 
	- Pushing 

Going Back in Time 
	- WEBSITE 
	- Resetting File to State 
	- Discarding Changes 
	- etc.

Moving Between Computers
	- Cloning Repo on New Computer 
	- Pulling in Changes from Server 
	- Gui Information Repo Thing 


Collaborating on Projects
===============================

Adding Collaborators 
	- GitHub Server

Typos
	- Straight from Website


Remote has Refs not Local 

Merge Conflicts 
	- What they Are 
	- How to fix them Online
	- How to fix them Locally 

High Level Branch 

Reading Commits
	- Reviewing code / Comments 
	- Emails

Issues
	- Checkboxes 
	- Tags
	- Labels 
	- Assigned ppl 
	- Discussions 

Open-Source Projects
=============================

Typo / ONLINE 

---------

Fork Workflow (ADVANCED)

Pull Requests from Forks (ADVANCED)

Merging and PRs
	- Why Pull Requests? 
	- Structure of a PR (reviewers, comments, edits, etc.)

Creating a PR
	- On the Website
	- Tagging Reviewers 
	- Leaving comments
	- Tagging issues 
	- etc. 

Fixing a PR 
	- Checking out Branch and Fixing 

Firefighting/Bugfixing 
==============================

Links to resources 

Git Bash 

**************
Local Julia 
**************

Non-Dockerized
===================

Setup 
	- Install Conda 
	- Install Julia 
	- Install Atom + Juno 
	- Link Julia to Atom
	- Local Jupyter Notebook 
		- Jupyter Lab foo
	- Normal REPL 
 
Juno 
	- Standard Layout Overview 


Why Local?
	- Running Scripts
	- Working with Files
	- Version Control + Editors  

Dockerized
====================

Setup
	- Install Docker 
	- Pull QuantEcon Docker Image 

Use
	- Using the Docker Image with Local Files 
	- Using the Docker Image with Container 
	- Editing Local Files in the Docker Image 

NOTES 
	- DROPBOX 
```
