### ISSUE TITLE
abs2

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#213]
Make sure we don't use this when we can avoid it. Only comes up in a few places, so this is mostly a sanity check for new PRs.

**Comment by jlperla** [comment]
If this is a sanity check for new prs, then it belongs in the style guide (where it is).  Otherwise, we should close it after they are gone.

**Comment by arnavs** [comment]
OK, will close this when the others are removed.

**Comment by arnavs** [comment]
Done.
