### ISSUE TITLE
Julia Gotchas

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#214]
Unintuitive behavior can go here: 

- Semantic difference between `f = x -> x` (can be rebound, can't be overloaded) and `f(x) = x` (can't be rebound, can be overloaded). 

-

**Comment by jlperla** [comment]
I am not sure either of those are unintuitive to me.  Not sure about this issue.

**Comment by Nosferican** [comment]
The `const` will eventually throw an error when changing value. Currently it only throws a warning.

**Comment by arnavs** [comment]
@jlperla Just thinking from the PoV of a student.

**Comment by jlperla** [comment]
I just don't think we should have this sort of thing in the course at this point.  These are not important enough to be in a gotchas.  I think this should be removed.

**Comment by arnavs** [comment]
OK, done.
