### ISSUE TITLE
Finish and test the new jupyter-first getting started

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#216]
We have moved a lot of the advanced stuff for use in a `tools and editors` PR.  We should be able to get the rest of it working.

In particular
- [x] look for all of the TODOs and big bold text and remove them as you cross things off
- [x] Finish off the the docker setup instructions.  Was that all there was for creating a local store?
- [x] Test the docker running instructions on both OSX and Windows, and ensure all of the paths are correct
- [x] For the Local installation of Jupyter/Anaconda, get someone to carefully go through it on windows and OSX witha  fresh machine, to see if we need to do anything to get the paths right for calling `jupyter lab`, etc.  We want it to be idiot-proof.

**Comment by arnavs** [comment]
Think this is done, but the Jupinx output is really ugly. For example, you should be able to indent code-blocks to make them children of the preceding bullet (so you can continue the numbering), but it's a mess right now. 

I think the best bet for testing would be to just send someone the RST for now.

**Comment by jlperla** [comment]
I will close.  We can get remumbering fixed when Matt is back.
