### ISSUE TITLE
Redo "getting started" images with Jupyterlab

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#217]
Right now the jupyter instructions are all for jupyter notebooks, but I think we want jupyterlab as the primary interface.

This will mean going through, generating new screenshots, and checking that the instructions make sense (i.e. some thigns have changed for the navigation).

**Comment by Nosferican** [comment]
I know a few months back Jupyter lab was considered in development and not production ready. Assuming the functionality seems stable and all features matured enough, I would love to do the transition to having the lectures use lab.

**Comment by jlperla** [comment]
I think it is ready, especially if people use a local installation. I have been using it since February with almost no problems. 

I think the issue with jupyterlab in production is probably more about the different plugins, etc. since the architecture changed. So if you were building a massive jupyterhub, you might be wary

**Comment by arnavs** [comment]
@yolsever If you don't have anything to work on for this repo right now, it would be great if you could knock this one out quickly. Make sure the images are basically matching what we have in the getting started repo (but with jupyter lab instead of jupyter), the sizes check out, etc.

**Comment by jlperla** [comment]
When you take screenshots, make sure that everything is as clean as possible (i.e. bookmarks aren't visible, etc.)

**Comment by jlperla** [comment]
When we do this, I would also like to avoid having our names in them if possible (e.g. `quanteconuser` or whatever).  But I realize it may not be that easy.
