### ISSUE TITLE
Bump priority of markov chain and dynamic programming rewrites

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#219]
I would love to teach some of the following mid-next week, if there is any way to bump the priority of the following:

- [ ] https://lectures.quantecon.org/jl/mccall_model.html
- [ ] https://lectures.quantecon.org/jl/mccall_model_with_separation.html
- [ ] https://lectures.quantecon.org/jl/short_path.html
- [ ] https://lectures.quantecon.org/jl/finite_markov.html

I believe that @arnavs  has started on https://github.com/QuantEcon/lecture-source-jl/pull/218 for some of it.  @Nosferican  if you were able to do the short_path and finite_markov it may make sense as a way to separate things.

**Comment by arnavs** [comment]
We also merged https://github.com/QuantEcon/lecture-source-jl/pull/173 for the Finite Markov rewrite. @jlperla let me know if you think we should revisit that one.

**Comment by Nosferican** [comment]
Sounds good. @jlperla do you have any comments or issues with the current versions? Both short_path and finite_markov seem to be quite up to date. If none, I can do a quick tuning of aesthetic and style, but don't seem like these need any major re-writes.

**Comment by arnavs** [comment]
https://github.com/jlperla/ECON407_2018/tree/master/notebooks Jesse's old stuff, should be aware of this while rewriting.

**Comment by jlperla** [comment]
I think that you guys may be through most of my changes for these.  The other places where the notebooks are useful are in other areas.  In particular `markov_asset.rst` and `discrete_dp.rst` in particular
