### ISSUE TITLE
Create the QuantEconLectureAllPackages

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#229]
@arnavs @Nosferican 

The plan was to have a "big" packages environment for lecture notes that require much more than the minimal setup we were interested in.  Most of these are to tool things up for harder statistics and econometrics.

In particular, this is a *strict superset* of the packages in https://github.com/QuantEcon/QuantEconLecturePackages

Then add in 
- https://github.com/JuliaGraphs/LightGraphs.jl
- https://github.com/queryverse/DataVoyager.jl
- https://github.com/queryverse/Queryverse.jl
- https://github.com/queryverse/Query.jl
- https://github.com/fredo-dedup/VegaLite.jl
- https://github.com/johnmyleswhite/RDatasets.jl
- https://github.com/JuliaStats/StatsModels.jl
- https://github.com/JuliaStats/StatsBase.jl
- https://github.com/matthieugomez/FixedEffectModels.jl
- https://github.com/jmboehm/RegressionTables.jl
- https://github.com/JuliaStats/GLM.jl
- https://github.com/matthieugomez/LeastSquaresOptim.jl
- https://github.com/JuliaData/CategoricalArrays.jl
- https://github.com/JuliaOpt/NLopt.jl
- https://github.com/JuliaOpt/JuMP.jl
- https://github.com/JuliaOpt/Ipopt.jl
- https://github.com/robertfeldt/BlackBoxOptim.jl

@arnavs  Can you
- Clone to https://github.com/QuantEcon/QuantEconLectureAllPackages
- take the QELP baseline ones as the starting point
- do all of the add operations/update
- Tag a version number so we can start using InstantiateFromURL.

Do JuMP.jl one last, as I am not sure that it is fully working on Julia v1.0.  If you have any trouble with these, tell me and we can remove them

**Comment by arnavs** [comment]
OK, done. `JuMP` didn't pose any problems. But I did have failures trying to add `RDatasets`. I was able to do this through Syzygy for my talk the other day, so this is either a Windows issue or a relatively modern one.

**Comment by arnavs** [comment]
Works with `RDatasets` and instantiating from that now.
