### ISSUE TITLE
Mutable Structs

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#237]
These are the lectures where we define a `mutable struct`. We can check off each one when either (a) we've removed it, or (b) we've decided it's OK.

- [x] `aiyagari` (#254)
- [ ] `amss` (#159)
- [x] `generic_programming`
- [x] `introduction_to_types`
- [ ] `markov_asset` (#248)
- [x] `multiplicative_functionals` (#251)
- [ ] `odu`
- [ ] `opt_tax_recur` (@arnavs is doing this one)
- [ ] `schelling` (#247)
- [ ] `uncertainty_traps` (#252)

cc @jlperla, @Nosferican

**Comment by arnavs** [comment]
FWIW, I think the `mutable struct` works really well in the Schelling lecture (we have a bunch of Agent objects, whose locations are updated over time).

**Comment by jlperla** [comment]
OK, sounds like that is a good exception.  Agent based models are a good example of where object-oriented approaches are reasonable.

**Comment by Nosferican** [comment]
I will work the re-write / pass for these ones.

**Comment by Nosferican** [comment]
- aiyagari (inner constructor)
- multiplicative_functionals (inner constructor)
- opt_tax_recur (inner constructor)
- uncertainty_traps (inner constructor)
- amss is currently broken (missing dependency still)
See what should we do if inner constructors simplify the code?

**Comment by jlperla** [comment]
The inner constructors were the hardest part of the OO style last year for stidents. They were totally lost.

In a functional or generic approach I think having well organized functions that operate on the parameters is the way to go.

We may not get a clean organization quite yet

**Comment by Nosferican** [comment]
For example,
```
struct SequentialAllocation{TP <: Model,
                            TI <: Integer,
                            TV <: AbstractVector}
    model::TP
    mc::MarkovChain
    S::TI
    cFB::TV
    nFB::TV
    ΞFB::TV
    zFB::TV
end

function SequentialAllocation(model)
    β, Π, G, Θ = model.β, model.Π, model.G, model.Θ
    mc = MarkovChain(Π)
    S = size(Π, 1)   # Number of states
    # Now find the first best allocation
    cFB, nFB, ΞFB, zFB = find_first_best(model, S, 1)

    return SequentialAllocation(model, mc, S, cFB, nFB, ΞFB, zFB)
end
```
And many others follow the same strategy
```
struct Model
    A
    y
    x
    function Model(A, y)
        model = Model(A, y, zeros(size(A, 2))
        fit!(model)
        return model
    end
end
function fit!(model)
    Model.x = Model.A \ Model.y
end
```
Do you have a suggestion for an alternative structure? That approach is not possible with NamedTuples.

**Comment by Nosferican** [comment]
Other cases are:
```
struct Model
    a
    b
    c
    Model(a, b) = (a, b, a + c)
end
```
which can't be easily mirrored with NamedTuples.

**Comment by Nosferican** [comment]
Aye, that change is managed intuitively through Parameters. Those could be changed.

**Comment by Nosferican** [comment]
Guess this works too,
```
using Parameters

Model = @with_kw (A, b, x = A \ b)

Model(A = rand(10, 2), b = rand(10))
```

**Comment by jlperla** [comment]
Is the checklist on the mutable structs removal here up to date?

**Comment by arnavs** [comment]
Superseded by #320
