### ISSUE TITLE
Hyperlink doesn't work for equations' labels in Julia's jupyter notebook

### ISSUE THREAD

**Issue by PooyaFa** [QuantEcon/lecture-source-jl#249]
Sometimes in the notes we refer to an equation which is mentioned before and a reader wants to just click on it and see it. However, it seems that it isn't the case.

**Comment by jlperla** [comment]
Thanks Pooya. For these sorts of issues, it is best to give very specific description of where it happens. If it always happens, then pick one example of it that is easy to see what is going on

**Comment by arnavs** [comment]
Same instructions w.r.t. Jupinx bugs as #250

**Comment by PooyaFa** [comment]
I provided it here. 

https://github.com/QuantEcon/sphinxcontrib-jupyter/issues/136#issuecomment-436052896

**Comment by arnavs** [comment]
This works now. See for ex. `mccall_model`, where the link to the `objective` equation works. Also, we have to be careful to distinguish cases where the hyperlink exists but doesn't work (which I don't think happens) from the case where it doesn't exist but should.
