### ISSUE TITLE
Font choice for unicode, consoles, etc. with instructions

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#25]
The default font used in Windows consoles has poor unicode coverage, which is a problem if we want to use unicode heavy examples.  Luckily, if fonts are installed it is relatively easy to change it in Windows (and I suspect terminals on other OSs).

My general gut is that for windows it might be `DejaVu Sans Mono` or `Fira Mono` which is installed by Atom but I could be wrong...
- [ ] Check if DejaVu Sans Mono` is installed on your Windows system by right-clicking on the shortcut, going to properties, choosing the font, etc.
- [ ] Check what the default font is for an Atom installation.  I can't tell if this is set in the one-dark syntax theme or is chosen separately..  I think it is either one of these two, though it could be different for different OS.  Check Windows, Ubuntu, and OSX
- [ ] The julia console used within Atom uses whatever is the default font, as far as I can tell.  This is helpful since it means if they use the embedded console the experience is very solid.
- [ ] Check the default font used in jupyterlab
- [ ] Add content to the setup instructions for Windows to set the font.
 - It is pretty easy to choose by right-clicking on the link if the font is installed.  This could be described in one line
- However, if the font we want to choose doesn't show up in the list, then it may require a registry tweak.  Best avoided if possible, but here is https://www.wikihow.com/Customize-the-Font-in-Windows-Command-Prompt   

A good test-suite to see if the font is solid is to type into the console (where the `<TAB>` completes the latex)
```julia
\alpha<TAB>
x\hat<TAB>
x\_1<TAB>
x\bar<TAB>
\alpha<TAB>\_1<TAB>
\cdot<TAB>
\otimes<TAB>
\partial<TAB>
```
And some others I am not sure the latex expansion for
```julia
𝒟
```

**Comment by Nosferican** [comment]
Some for Julia functions,
```
\in<TAB> ∈
\notin<TAB> ∉
\subseteq<TAB> ⊆
\ne<TAB> ≠
\approx<TAB> ≈
```

**Comment by arnavs** [comment]
Added these to the fontcheck. And the thing with the latex expansion is `\scrL` in Atom, maybe requires a package in latex straight.
