### ISSUE TITLE
Add citation to Stefanov and Rose book

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#253]
``Mathematics to Generic Programming (Stefanov and Rose)

Add to the bibtex, and put in the citation in the Generic Programming lecture.

**Comment by Nosferican** [comment]
```
@book{stepanov_mathematics_2014,
      author = {Stepanov, Alexander A. and Rose, Daniel E.},
      date = {2014},
      location = {Upper Saddle River, NJ},
      title = {From mathematics to generic programming},
      isbn = {978-0-321-94204-3},
      pagetotal = {293},
      publisher = {Addison-Wesley},
      keywords = {Computer algorithms, Generic programming (Computer science), Mathematics}
}
```

**Comment by jlperla** [comment]
Thanks!

@arnavs  Can you figure out how to put this in the bitex used by the lecture notes, and add in the reference is used at the top of the generic_programming lectures?  I just don't know how that works in rst.

**Comment by arnavs** [comment]
Done.
