### ISSUE TITLE
Add material on higher-order functions to "julia essentials"

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#257]
Gentle introduction in the closure section to:
- Functions of functions
- Functions that return functions

Some simple examples:
```
twice(f,x) = f(f(x))
f(x) = x^2
twice(f, 2.0)
twice(x -> x^2, 2.0)
```
and 
```
function doubleit(g)
    return x -> 2 * g(x) #i.e. returns a function which uses f
end
f(x) = x^2
h = doubleit(f) #Use our quadratic, returns a new function which doubles the result
h(2)
```
Also, show you can return a closure and not just an anonymous function.

**Comment by arnavs** [comment]
Small point, but I think it'd be good to show how easy this is in Julia vs. other languages 

Paul Graham has a list of [canonical solutions](http://www.paulgraham.com/accgen.html) to the problem "write a function to take _n_, and return a function that adds _n_ to _x_"

The Python and C++ examples are all much longer than the Julia, which is `n -> (x -> x + n)`

This could also be a good showcase of the https://github.com/QuantEcon/Expectations.jl package, which wouldn't work unless functions could be passed around
