### ISSUE TITLE
[Render] Top Dropdown for each lecture not rendering correctly

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-jl#263]
![image](https://user-images.githubusercontent.com/8263752/48111894-d96cc480-e2a7-11e8-9a47-a8643745ab7e.png)

should be in a collapsed block.

**Comment by arnavs** [comment]
OK @mmcky, done at a1cad7c. Let me know when you build the HTML again and I'll confirm that it's resolved.

**Comment by jlperla** [comment]
We can try this after #267 is done.

**Comment by mmcky** [comment]
thanks @arnavs I will recompile the latest `master` first thing tomorrow morning and update `compare-lectures` for review.

**Comment by mmcky** [comment]
hey @arnavs had a look at your commit. The `:class: collapse` only works on `code-blocks` provided by the `quantecon` theme layer. The top dropdown we have always just injected as raw html as it rarely needs modification. We still have the `jl` version in `_static/includes` on the `py` repo if you want to use that. https://github.com/QuantEcon/lecture-source-py/blob/master/rst_files/_static/includes/lecture_howto_jl.raw

**Comment by arnavs** [comment]
Gotcha @mmcky, that explains some difficulties we were having earlier with the class. I think we can use what you linked.

**Comment by mmcky** [comment]
thanks @arnavs you'll just need to add the text for `Trust` etc. Let me know if you have any difficulties and I will add the html as a PR.

**Comment by arnavs** [comment]
@mmcky Think this is done now. And deleted the markdown headers that we'd come up with ourselves.

**Comment by arnavs** [comment]
Closing this since it works now. See e.g. http://compare-lectures.quantecon.org/jl/mccall_model.html
