### ISSUE TITLE
Precompilation of packages in the build process

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#268]
@mmcky You may have noticed in the HTML version of the lecture notes there is a lot of output from the precompiling packages on first use.  We want to be able to get rid of that.

There are a few things here:
I am not sure it will be very clean before the v1.0.2 release of Julia (which should be in the next week) since there were package manager bugs.  But that won't change how we address the issue

Since every package we use is in two project files, we can instantiate and precompile the necessary versions for all of the lectures at once.  To do this,
  * You need to make sure that the global environment in julia has the `] add InstantiateFromURL` in it
  *  We need to run the `_static/includes/deps.jl` and the `alldeps.jl` prior to running jupyter in the build process.  When julia's package manager bugs are gone, this will install/precompile/etc. all of the dependencies
  * We need to ensure that the working directory is the one in which the notebooks are going to run, as it will create a folder `.projects` relative to that folder they can use.
  * At the beginning of the build process, we need to make sure we delete that `.projects` folder before running the dependency 

@arnavs  is the one who can help you with this and get up to speed with the build infrastructure as well, if possible.

**Comment by arnavs** [comment]
Resolved thanks to @mmcky.
