### ISSUE TITLE
Ensure all source-code displays without horizontal scrolling

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#271]
For example, in http://compare-lectures.quantecon.org/jl/julia_by_example.html#

![image](https://user-images.githubusercontent.com/13106721/48233904-ff5b9d00-e36b-11e8-88f6-16a90c9af040.png)

To do this, we will need to shorten the lines of code.
* If it is actual code then we can use string concatenation,
i.e. instead of 
```julia
println("Fixed point = $(sol.zero), and |f(x) - x| = $(norm(f(sol.zero) - sol.zero)) in $(sol.iterations) iterations")
```
maybe something like (noting the use of `*` as string concatenation to make it multiple line correctly
```julia
println("Fixed point = $(sol.zero), and |f(x) - x| = $(norm(f(sol.zero) - sol.zero))"*
"in $(sol.iterations) iterations")
```
* If it is due to comments on the right of equations being too long we can move the comments to their own line before the equation.  Or we can remove/shorten  the comments if they don't seem to make much sense.  For these, don't forget the style guide https://github.com/QuantEcon/lecture-source-jl/blob/master/style.md#naming-conventions-comments-etc

@Nosferican  @arnavs  It might be helpful to figure out the length at which scrolling appears, if you have any ideas?  We could then could check that column width in our editors.

Active template for checklists:

## Getting Started with Julia
- [x] [Setting up your Julia Environment](https://lectures.quantecon.org/jl/getting_started.html)
- [x] [An Introductory Example](https://lectures.quantecon.org/jl/julia_by_example.html)
- [x] [Julia Essentials](https://lectures.quantecon.org/jl/julia_essentials.html) and more material
- [x] [Fundamental Types](https://lectures.quantecon.org/jl/julia_arrays.html)  with more material
- [x] Introduction to Types and Generic Programming

## More Programming and Software Engineering Principles
- [x] Generic Programming
- [x] General Purpose Packages
- [x] Data and Statistical Ecosystem
- [x] Solvers, Optimizers, AD
- [x] GitHub and Version Control
- [x] Tools and Editors
- [x] Testing and CI

## Tools and Techniques 
- [x] [Linear Algebra](https://lectures.quantecon.org/jl/linear_algebra.html)
- [x] [Orthogonal Projections and their Applications](https://lectures.quantecon.org/jl/orth_proj.html)
- [x] [LLN and CLT](https://lectures.quantecon.org/jl/lln_clt.html)
- [x] [Linear State-Space Models](https://lectures.quantecon.org/jl/linear_models.html)
- [x] [Finite Markov Chains](https://lectures.quantecon.org/jl/finite_markov.html)
- [x] [Continuous State Markov Chains](https://lectures.quantecon.org/jl/stationary_densities.html)
- [x] [A First Look at the Kalman Filter](https://lectures.quantecon.org/jl/kalman.html)

## Dynamic Programming 
- [x] [Shortest Paths](https://lectures.quantecon.org/jl/short_path.html)
- [x] [Job Search I: The McCall Search Model](https://lectures.quantecon.org/jl/mccall_model.html)
- [x] [Job Search II: Search and Separation](https://lectures.quantecon.org/jl/mccall_model_with_separation.html)
- [x] [A Problem that Stumped Milton Friedman](https://lectures.quantecon.org/jl/wald_friedman.html)
- [x] [Job Search III: Search with Learning](https://lectures.quantecon.org/jl/odu.html)
- [x] [Job Search IV: Modeling Career Choice](https://lectures.quantecon.org/jl/career.html)
- [x] [Job Search V: On-the-Job Search](https://lectures.quantecon.org/jl/jv.html)
- [x] [Optimal Growth I: The Stochastic Optimal Growth Model](https://lectures.quantecon.org/jl/optgrowth.html)
- [x] [Optimal Growth II: Time Iteration](https://lectures.quantecon.org/jl/coleman_policy_iter.html)
- [x] [Optimal Growth III: The Endogenous Grid Method](https://lectures.quantecon.org/jl/egm_policy_iter.html)
- [x] [LQ Dynamic Programming Problems](https://lectures.quantecon.org/jl/lqcontrol.html)
- [x] [Optimal Savings I: The Permanent Income Model](https://lectures.quantecon.org/jl/perm_income.html)
- [x] [Optimal Savings II: LQ Techniques](https://lectures.quantecon.org/jl/perm_income_cons.html)
- [x] [Consumption and Tax Smoothing with Complete and Incomplete Markets](https://lectures.quantecon.org/jl/smoothing.html)
- [x] [Optimal Savings III: Occasionally Binding Constraints](https://lectures.quantecon.org/jl/ifp.html)
- [x] [Robustness](https://lectures.quantecon.org/jl/robustness.html)
- [x] [Discrete State Dynamic Programming](https://lectures.quantecon.org/jl/discrete_dp.html)

## Multiple Agent Models
- [x] [Schelling's Segregation Model](https://lectures.quantecon.org/jl/schelling.html)
- [x] [A Lake Model of Employment and Unemployment](https://lectures.quantecon.org/jl/lake_model.html)
- [x] [Rational Expectations Equilibrium](https://lectures.quantecon.org/jl/rational_expectations.html)
- [x] [Markov Perfect Equilibrium](https://lectures.quantecon.org/jl/markov_perf.html)
- [x] [Asset Pricing I: Finite State Models](https://lectures.quantecon.org/jl/markov_asset.html)
- [x] [Asset Pricing II: The Lucas Asset Pricing Model](https://lectures.quantecon.org/jl/lucas_model.html)
- [x] [Asset Pricing III: Incomplete Markets](https://lectures.quantecon.org/jl/harrison_kreps.html)
- [x] [Uncertainty Traps](https://lectures.quantecon.org/jl/uncertainty_traps.html)
- [x] [The Aiyagari Model](https://lectures.quantecon.org/jl/aiyagari.html)
- [x] [Default Risk and Income Fluctuations](https://lectures.quantecon.org/jl/arellano.html)
- [x] [Globalization and Cycles](https://lectures.quantecon.org/jl/matsuyama.html)

## Time Series Models
- [x] [Covariance Stationary Processes](https://lectures.quantecon.org/jl/arma.html)
- [x] [Estimation of Spectra](https://lectures.quantecon.org/jl/estspec.html)
- [x] [Additive Functionals](https://lectures.quantecon.org/jl/additive_functionals.html)
- [x] [Multiplicative Functionals](https://lectures.quantecon.org/jl/multiplicative_functionals.html)
- [x] [Classical Control with Linear Algebra](https://lectures.quantecon.org/jl/lu_tricks.html)
- [x] [Classical Filtering with Linear Algebra](https://lectures.quantecon.org/jl/classical_filtering.html)

## Dynamic Programming Squared
- [x] [Dynamic Stackelberg Problems](https://lectures.quantecon.org/jl/dyn_stack.html)
- [x] [Optimal Taxation in an LQ Economy](https://lectures.quantecon.org/jl/lqramsey.html)
- [x] [Optimal Taxation with State-Contingent Debt](https://lectures.quantecon.org/jl/opt_tax_recur.html)
- [x] [Optimal Taxation without State-Contingent Debt](https://lectures.quantecon.org/jl/amss.html)

**Comment by arnavs** [comment]
Scrolling kicks in at 99/100 characters. I think a good workflow is to set the text in the editor to that width (plus indentation), and then make sure that no code lines go over the limit.

Assigning @XiaojunGuan per slack

**Comment by arnavs** [comment]
Closing this thanks to #283, thanks @XiaojunGuan for your hard work
