### ISSUE TITLE
Upgrade and test the new docker build

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#280]
With Julia v1.0.2, the new precompiled version numbers of both sets of packages 0.9 (or whatever).  Might as well throw `REPL.jl` to the precompile script as we did in the setup (why not!)  

This will help us have people do docker based QA

**Comment by arnavs** [comment]
Working on this today. Will update this post with issues as they appear. 

- [ ] Errors building Cairo and Ipopt with the QELAP v0.9.0. This causes DataVoyager to fail precompiling and break the build.

**Comment by jlperla** [comment]
@PooyaFa let's leave you off of any docker setup issues since you are having problems. There is plenty of other QA to do on the other lectures

**Comment by arnavs** [comment]
@XiaojunGuan said she's done with the scrolling issue #278 and has some extra capacity, so I'm going to hand this over to her. 

I think this is orthogonal of the location of the instructions in #292. Xiaojun, basically we need to make sure that the Docker build works as described and that the instructions are relatively clear (we will be simplifying them further). If there are any issues, we can touch base tomorrow.

**Comment by arnavs** [comment]
Also, for good measure this should involve a spot-check of a few of the lectures with the new Docker and make sure that there are no glitches.

**Comment by arnavs** [comment]
The issue above was also stopping @mmcky from running the `activate_github` for the QELAP in the build, and it'll likely fail for any lecture that uses the `alldeps`. 

Will look into fixing it. cc @Nosferican if you have any insights re Cairo and Ipopt build errors.

**Comment by arnavs** [comment]
Closing because the missing libraries are in the Dockerfile, and the syzygy is good.
