### ISSUE TITLE
tools_editors lecture:

### ISSUE THREAD

**Issue by PooyaFa** [QuantEcon/lecture-source-jl#285]
Figure /_static/figures/juno-plots.png isn't clear

In Docker Integration https://docs.junolab.org/latest/man/faq.html/ doesn't work (page not found)

**Comment by arnavs** [comment]
Hi @PooyaFa, do you mean that the image is too small/you can't read the code? Or is something about the image misleading

<img width="1749" alt="screen shot 2018-11-11 at 8 06 50 am" src="https://user-images.githubusercontent.com/5009477/48315263-c2202680-e588-11e8-826e-5ae91069045b.png">

Thanks, need to remove the `/` from the URL.
