### ISSUE TITLE
Error in docker for windows 10 after automatic restart after installation

### ISSUE THREAD

**Issue by PooyaFa** [QuantEcon/lecture-source-jl#290]
I downloaded Docker, installed it, and then it shows me that it will automatically signing out. After signed out, it shows it will restart windows automatically. After restarted, it showed this error:

![docker error](https://user-images.githubusercontent.com/44382270/48318408-6d46d500-e5b5-11e8-896e-d8285d2ccbb9.png)

**Comment by PooyaFa** [comment]
After clicking on "Reset to factory defaults" it showed an error again:

![2](https://user-images.githubusercontent.com/44382270/48318434-ddedf180-e5b5-11e8-9e00-1cb63eab56de.PNG)

**Comment by arnavs** [comment]
Works fine on my work machine. Issue seems to be that you need to install/run as administrator (from a quick google). If that doesn't work and you can't find info online, let's touch base on Tuesday where I'm front of a Windows box.

**Comment by arnavs** [comment]
But definitely something we need to make clear in the instructions.

**Comment by PooyaFa** [comment]
I will uninstall and do it again.

**Comment by PooyaFa** [comment]
It didn't work. The exact error is:

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'DESKTOP-5GQBFKQ' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by jlperla** [comment]
To be clear, though, it doesn't sound like this has anything to do with the QE setup?  There is only so much we can do for general docker setups.  Though if what you have is a common installation error, we could provide a link to the troubleshooting guide for docker? See https://docs.docker.com/docker-for-windows/troubleshoot/ for example.

**Comment by PooyaFa** [comment]
No it doesn't have anything to do with the QE setup. I can't test QE setup though! I will try it on others' windows. See what happens.

**Comment by jlperla** [comment]
It also might be worth trying to figure out how to fix docker on your computer, since it is such a useful tool.

**Comment by PooyaFa** [comment]
I couldn't install on another windows either. 

This is a long issue about the same error I 'm getting, and apparently it has many reasons:
https://github.com/docker/for-win/issues/1221

**Comment by jlperla** [comment]
Maybe something like https://github.com/docker/for-win/issues/1221#issuecomment-410534002

If this works for you, we may want to put something like this in setup notes for others.

**Comment by arnavs** [comment]
@pooyafa Do you mean that if you don’t check that option, you can successfully build and run the image?

The reason we picked that option is because the QuantEcon/base is a Linux container (it’s built on a Jupyter stack, which I think is built on debian Linux). As of April, you needed to manually toggle that option to switch between Linux and Windows containers, although there was a development feature for Linux Containers on a Windows (LCOW). Maybe it’s been released now.

**Comment by jlperla** [comment]
Closing since this isn't related to the lectures
