### ISSUE TITLE
Test on juliabox

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#293]
I am not sure the current status of juliabox and manifests. But since they tend to do a job keeping packages working together. I think a full test probably requires #270 but it would be nice to see how close we are by trying to run a few lectures.

Part of this is also to find which packages are missing from the basic juliabox image

**Comment by jlperla** [comment]
Tested.  Not working sufficiently fore the v1.1 release, so will move forward for discussion with julia computing.

**Comment by jlperla** [comment]
@arnavs Keeping track of package issues here:
- `] add Expectations NLsolve StatPlots; precompile`  is needed at this point
- The Compat version is not up to date.  This causes some issues with the `range` notation.  Perhaps it could be updated with Juliabox?

**Comment by jlperla** [comment]
Maybe update `Parameters` as well?

**Comment by arnavs** [comment]
`QuantEcon` needs to be bumped (depends on some old version with a `LineSearches` dependency)
`StatPlots` isn't there (and this comes with a ton of deps)
I think `Optim` also needs to be installed

**Comment by jlperla** [comment]
Not everything needs to be there by default, we can have a single installation instruction (or even a notebook with the appropriate cells) that does
```
] add Expectations NLsolve StatPlots Optim; precompile
```
or something like that.  But if we can identify which packages are at old versions which don't work with the lecture notes, it is helpful.

**Comment by jlperla** [comment]
The other thing is that there are packages like `Optim` which require an `] add` but I don't think are actually downloading anything (i.e. they are in a repo, even if at an older version).  Lets try to keep track of ones that actually download.

**Comment by jlperla** [comment]
This comes back to the consideration from before whether an "activate" of a project after deleting the manifest isn't a bad idea for juliabox...

**Comment by arnavs** [comment]
My main concern with the JuliaBox environment is that it seems one-off, in the sense that we get errors while using and installing packages that you wouldn't get on a local machine or on an image like syzygy. I was seeing some memory errors, lots of `Pkg` errors. `LibGit` and git errors as well. 

Strictly in terms of what's on the machine, I think there is enough. But the rest of the ecosystem feels shaky when I played with it.

**Comment by arnavs** [comment]
@jlperla Does a syzygy or JupyterHub based setup from QuantEcon not work anymore?

**Comment by jlperla** [comment]
The question is for general users, not for a bunch of specific students that can be handheld.

If there are a small number of things to ask Julia Computing for so that juliabox works with the lectures, then it would be useful to have an option.  But I don't want to suggest people use it unless it is a predictable setup and usage process.
