### ISSUE TITLE
Fix StatPlots precompilation?

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#309]
cc @arnavs 

With the upgrade to Julia v1.0.2, most of the issues with precompilation have gone away, and the generated jupyter then html 

... except for `StatPlots.jl`

I think it is easy to replicate:
* Use the InstantitateFromURL to activate a project with statplots as a dependency, like our baseline setup, which then does a `] precompile` at the end of the script.  Perhaps you could just manually make a new project and then precompile it.
* Then go `using StatPlots` to make sure that it gets precompiled.
* Now, start up another jupyter notebook and go `using StatPlots`, or activiating with `InstantiateFromURL`.  If you do, it should say that it is precompiling a bunch of stuff, even though it did it already.

@Nosferican : Is there any way you could look at this problem, and maybe discuss with the maintainers there?

**Comment by arnavs** [comment]
The PR to METADATA has been merged and the upgraded StatPlots has been reflected in the new `v0.9.1` of QELP and QELAP, so closing now.
