### ISSUE TITLE
Embed information from the tools and editors guide

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#310]
See the link to `https://github.com/econtoolkit/tutorials/blob/master/julia.md#installation-and-setup/` in `tools_editors.rst` 

Those instructions need to be emdeded here and that markdown file soon deprecated.  Luckily, it appears to be the only link to the old, rough, setup notes.

**Comment by jlperla** [comment]
Leave in the opinionated setup instructions for Atom (i.e. the softwrap and the change to `LF`) in https://github.com/econtoolkit/tutorials/blob/master/julia.md#installation-and-setup

**Comment by jlperla** [comment]
Also
* Move all of the atom setup and installation steps right after installation of Atom
* Get rid of the "I" and instead have "you" or something similar
* Get someone to test the installation steps from scratch by nuking Atom and the `.atom` folder
* Are we sure about the things about "changes in versions" etc. that are in those setup instructions?

**Comment by arnavs** [comment]
@jlperla This is done now. Agree that the changing versions stuff doesn't make sense here (the fix was 'turn it off and turn it on again', which I suspect people would do anyway).

Will hand over to @XiaojunGuan to test since she's out of issues.

**Comment by jlperla** [comment]
Great.  I will test as well.

**Comment by jlperla** [comment]
I am going to close this since we are at the "run tests everywhere" stage
