### ISSUE TITLE
Make all setup guides enumerated

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#311]
This is worth doing sooner so we can do a thorough test.

The goal is to have anything which is a one-time setup step (or a repeated workflow step) enumerated.  Some of the ones that stand out are:
- [x] Getting started manual installation: http://compare-lectures.quantecon.org/jl/getting_started.html#Installing-Julia-and-Dependencies-Manually (thought thigns were moved around)
- [x] Version control setup: http://compare-lectures.quantecon.org/jl/version_control.html#Setup
- [x] Go through the other ones in http://compare-lectures.quantecon.org/jl/version_control.html but I don't see other step-based workflows that jump out
- [x] The new docker stuff in http://compare-lectures.quantecon.org/jl/tools_editors.html
- [x] Probably the http://compare-lectures.quantecon.org/jl/testing.html#Julia-Setup steps 
- [x] Perhaps http://compare-lectures.quantecon.org/jl/testing.html#Collaborative-Work

But I would go through all of these to see what would be clearer as lists.  Some of them are already organized into sections, which may be more appropriate.

**Comment by arnavs** [comment]
@jlperla Committed at XYZ. Let me know what you think. I general, I left things as sections (basically the `version_control` github setup) when they were essentially linear with no commentary. Otherwise, I used the numbers to distinguish actions from information.
