### ISSUE TITLE
Jupinx Lists

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#312]
Keep an eye on https://github.com/QuantEcon/sphinxcontrib-jupyter/issues/143 and https://github.com/QuantEcon/sphinxcontrib-jupyter/issues/144, and make sure that once they're done, we either confirm that our lists are rendering properly or adjust our syntax to make that happen.

**Comment by arnavs** [comment]
Make sure these work with nested bullets and nested numbers before closing, since we use both in (at least) `version_control`

**Comment by mmcky** [comment]
This looks like it is working .. do you intend to use mixed lists of bullets and numbers? I would have thought the second layer would be consistent.

![image](https://user-images.githubusercontent.com/8263752/48987416-b6308900-f172-11e8-9126-18a2332f5b62.png)

Just a side note: the images in the version_control.py lecture are hard to read -- they may need to be bigger?

**Comment by mmcky** [comment]
These are rendering correctly due to the use of `4 space` indentation. So we should stick to that in mixed lists for now.

**Comment by arnavs** [comment]
Sounds good, closing this now. @mmcky I think mixed lists are a special case of the distinction between numbers and bullets, in that sometimes sublists will be sequential steps and sometimes not.
