### ISSUE TITLE
Remove Type declarations in the zeros whenever possible

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#314]
cc: @Nosferican  Just to make sure you saw this for future stuff.

Search for 
```
zeros(Float64
```
and
```
ones(Float64
```
And get rid of the `Float64`  We want to avoid all type declarations it at all possible.

**Comment by Nosferican** [comment]
I am pretty sure that is the current style. At least I have been doing so.

**Comment by jlperla** [comment]
Perfect then.  We can get someone to search for ones that remain.

**Comment by arnavs** [comment]
Done with the batch of commits I pushed. Quite a lot of these were left.

There was also some other stuff I ripped out, like `Vector{Vector{Float64, 1}}()` and the thing below...

```
struct LQFilter{TF_ <: Union{Vector{Float64},Nothing}, TI_ <: Union{Int,Nothing}}
```
