### ISSUE TITLE
Should we relaunch the cheat-sheet at the same time?

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#319]
@Nosferican @arnavs  Thoughts?
https://cheatsheets.quantecon.org/

**Comment by Nosferican** [comment]
Sure. Could be updated with https://docs.julialang.org/en/latest/manual/noteworthy-differences/.

**Comment by jlperla** [comment]
Great.  If we get all of our other changes for the launch done before the build infrastructure and HTML output is complete, then I think it would be worth the time.  I will make a few notes in a different issue.

**Comment by jlperla** [comment]
See https://github.com/QuantEcon/QuantEcon.cheatsheet/issues/52   Not work holding up the release over, but if we have some extra time while waiting for build issues to be fixed it is a good idea to chip away at it.

**Comment by arnavs** [comment]
Think we're good on the Julia stuff (at my fork https://github.com/arnavs/quantecon.cheatsheet). Need to iron out the build/rST formatting. Will have an RA do the Python stuff.

**Comment by jstac** [comment]
@jlperla You don't think it serves a useful purpose?  It could easily be updated and then referenced in the first lecture or two as a guide for syntax.

**Comment by jlperla** [comment]
@jstac I think it serves a purpose, for sure.  The quetsion is more about what we want there for the v1.0 lecture notes launch.

The question is whether it is (1) working and tested; (2) up to date in the spirit of Julia v1.0 where the additional material relative to the Julia/Matlab/Python is worthwhile; (3) as comprehensive as the main alternatives https://juliadocs.github.io/Julia-Cheat-Sheet/ 


I think there are 3 choices here:
1. Leave it as is, hopefully checking that it doesn't make any "mistakes", and plan to revisit it in the new year.  Maybe put the link to https://juliadocs.github.io/Julia-Cheat-Sheet/ at the top so people can see the additional material.
2. Remove it temporarily to focus on the comparison cheat-sheet, drop it from the site, and then revisit it in the new year
3. Temporarily point to https://juliadocs.github.io/Julia-Cheat-Sheet/ from the current link

**Comment by arnavs** [comment]
Just want to point out that there's a PR open to fix the content on the Julia cheatsheet at https://github.com/QuantEcon/QuantEcon.cheatsheet/pull/54/files. All that's required is for someone to help figure out why the LaTeX is overflowing in the table.

**Comment by arnavs** [comment]
Going to close this issue as it's no longer a showstopper for `v1.0` given the open PRs.
