### ISSUE TITLE
Comment on package operations in OS/X REPL

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#321]
From a student: It sounds like the julia console on OSX doesn't have the same  functionality that the windows/linux does.

In particular, you can't copy and paste strings with full package operations into it (e.g.  `] st`  directly)

We should find when we tell people to use the REPL and put in a note on this.  Basically just say
```
`*Note*: on OS/X you cannot paste the entire string, and must type the ``]`` separately from the other package operations
```

A few of them:
- [x] http://compare-lectures.quantecon.org/jl/getting_started.html#The-REPL 
- [x] http://compare-lectures.quantecon.org/jl/tools_editors.html#Package-Mode

That may be enough?  I would also post a bug on it to the Julia repo

**Comment by arnavs** [comment]
Roger that, will ask about this in Slack and add these caveats in.

**Comment by arnavs** [comment]
Done. And raised the issue on Slack. Somebody said: 

> I think it might work if the terminal doesn't support bracketed paste
