### ISSUE TITLE
QA-Issues in `getting_started`

### ISSUE THREAD

**Issue by XiaojunGuan** [QuantEcon/lecture-source-jl#325]
1. Many links in `getting_started` are not working right now. 
For example in the `Jupyter/Options` section, none of the links are working for me except the one `Atom/Juno`. In the next section `Using Jupyter Online`, the link for `JuliaBox` is not working either. They return something like this 

<img width="755" alt="link" src="https://user-images.githubusercontent.com/35314124/48647122-e40e1480-e99f-11e8-9ead-eab905d13c5e.png">

**Comment by XiaojunGuan** [comment]
2. The indices in section `Installing Julia and Dependencies` are quite confusing. There are two `1.` followed by a `2.` and then followed by three `1.`.

**Comment by arnavs** [comment]
@XiaojunGuan this is an example of when you neee to go to the source rST. This is helpful, but a lot of this is build stuff out of our control. The key is to look for content-level changes that we can do.

**Comment by XiaojunGuan** [comment]
I checked. These links in the notebook generated by the source rst are also not working and that is okay?

**Comment by arnavs** [comment]
It’s OK in that it’s an issue with the generation step, and not what we wrote. The issue would be if we misspecified the link there or something.

**Comment by XiaojunGuan** [comment]
Got it, thanks.
