### ISSUE TITLE
Remove LaTeXStrings everywhere (except general_packages)

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#327]
I also note that it is there in two static files, which should be removed once they are merged
- [x] paths_and_hist.jl
- [x] mccall_cf_plot1.jl
- [x] stationary_densities.rst

**Comment by arnavs** [comment]
@jlperla Should I take out the section about LaTeXStrings in general_packages.rst?

**Comment by jlperla** [comment]
everywhere (except general_packages)

**Comment by arnavs** [comment]
Done.
