### ISSUE TITLE
Remove mentions to obsoleted objects

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#329]
I found `scipy` in the following
I think all of these are just artifacts of a porting of python to julia code
- [x] `jv.rst`
- [x] `multiplicative_functionals.rst`
- [x] `odu.rst`
- [x] `stationary_densitives.rst`

I did not find numpy, and the reference to "Pandas" and "python" were all appropriate.    Any others to check?

**Comment by arnavs** [comment]
On this note, we also need to eliminate references to types/structs we created when we moved over to a `NamedTuple`.
