### ISSUE TITLE
Fix problems in "Setting up your julia environment"

### ISSUE THREAD

**Issue by yolsever** [QuantEcon/lecture-source-jl#339]
"Options" the links are broken except the link to Juno
"Using Jupyter online" Juliabox link is broken
"Plots" the first cell takes a lot of time to run because of running it for the first time. There should be a note about this as it may make students think there is something wrong
in "notebook basics", it says the previous figure has a cell bordered in green even though the cell has blue borders
At the bottom of the page, the next topic is: estimation of spectra and the previous one is time series model which is not true

**Comment by arnavs** [comment]
Thanks @yolsever, and very good point about the plots. The "time-to-first-plot" problem is actually on the list of priorities for the next version of the Julia compiler
