### ISSUE TITLE
Fix problems in "introductory examples"

### ISSUE THREAD

**Issue by yolsever** [QuantEcon/lecture-source-jl#341]
Under "Other References" the link for Julia manual is broken
Typo: The word in from the for loop can be replaced by "etiher "
Typo: Here, eachindex(ϵ) returns an "interator" of indices which can be used
In the code block "ϵ_sum = 0.0 # careful to use 0.0 here, instead of 0!". Not a big problem but 0! can be understood as 0 factorial.
In function fixedpointmap(f; iv, tolerance=1E-7, maxiter=1000), f(v) = p + β * v #, "note that p and "β" are used in the function!" The "beta" is not capitalized
In the lecture file under section "Using a package" the code does not output as well as the code below but these work well in my notebook
The code with line "# use arbitrary precision floating points", outputs UndefVarError: fixedpoint not defined
And when I click on Julia1.0 on top to go back to the main menu, I get 404 not found error

**Comment by arnavs** [comment]
Hey @yolsever overall looks good, what do you mean by the beta capitzlied?

**Comment by arnavs** [comment]
Done at c305dd1. Some of this stuff like the arbitrary precision comment is fixed in later changes.
