### ISSUE TITLE
Is the comment about the Travis website deprecation useful?

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#342]
In http://compare-lectures.quantecon.org/jl/testing.html#Account-Setup
It says:
> NOTE As of May 2018, Travis is deprecating the travis-ci.org website. All users should use travis-ci.com

If this isn't useful, remove the noise and just keep all of the links to the `.com` one>

**Comment by arnavs** [comment]
The reason we need something like this because `travis-ci.org` still exists and doesn't display a depwarn of any kind. Resolved by just making the links a bit clearer and removing the big warning.

**Comment by jlperla** [comment]
If we haven't told them to go to that link, then why do we care if it still exists?  Is it that they need to manually change the link to travis-ci.com following other parts of the workflow?  I would rather remove informational noise from workflows if it is just background information which may or may not be useful following those steps.

**Comment by arnavs** [comment]
Right, the links point to the `.com`, the warning was just a precaution. The screenshots and such all use the correct one. But in any case, it's removed now.
