### ISSUE TITLE
Some Issues about introduction_to_types lecture

### ISSUE THREAD

**Issue by PooyaFa** [QuantEcon/lecture-source-jl#345]
1. There are some differences between HTML and ipynb notebooks: line 88 in rst of introduction_to_types :
![1](https://user-images.githubusercontent.com/44382270/48670242-60504700-eac9-11e8-81ad-d0386f4596fa.PNG)

2.  As stated before links don't work, except for websites: links in line 145,146, and 147:
![2](https://user-images.githubusercontent.com/44382270/48670246-6f36f980-eac9-11e8-96b8-dbc544a59e90.PNG)

3. line 232 in rst file and HTML are different. And since links don't work I think it is better if we replace "this lecture" with "generic programming":
![3](https://user-images.githubusercontent.com/44382270/48670250-8fff4f00-eac9-11e8-94f0-6fd24751de04.PNG)

4. There is no "julia by example lecture" in https://lectures.quantecon.org/jl/. but it is mentioned in exercise 4:
![5](https://user-images.githubusercontent.com/44382270/48670268-d6ed4480-eac9-11e8-82ca-3fc2d00fc0be.PNG)
should I change it in the note or the lecture "An Introductory Example" will be changed to "julia by example"?

5. The link in exercise 6 is not working and it is not clear what it is refereed to: `rules for generic programming <_generic_tips_tricks>`_:
![6](https://user-images.githubusercontent.com/44382270/48670258-b0c7a480-eac9-11e8-9a21-fe42ca1b8e29.PNG)

**Comment by arnavs** [comment]
Links will work eventually, but the name there should be more specific. As for Julia by Example, that's the "Introductory Examples" lecture. @jlperla, do you want to change the name?

**Comment by jlperla** [comment]
There is a discrepancy between the name and the filename.  Stick with the name "Introductory Examples" for the link.
