### ISSUE TITLE
Some issues about generic_programming lecture

### ISSUE THREAD

**Issue by PooyaFa** [QuantEcon/lecture-source-jl#347]
1. There are some differences between HTML and ipynb notebooks: line 250 in rst file:
![1](https://user-images.githubusercontent.com/44382270/48679794-5bcb7300-eb49-11e8-9483-a3e7836d355a.PNG)
![1i](https://user-images.githubusercontent.com/44382270/48679795-5bcb7300-eb49-11e8-843d-8ebdf885ca80.PNG)

2. Is it intentional or a mistake? line 260 rst file
![2i](https://user-images.githubusercontent.com/44382270/48679809-68e86200-eb49-11e8-8100-bdafc03c59aa.PNG)
![2ii](https://user-images.githubusercontent.com/44382270/48679810-68e86200-eb49-11e8-8af0-f129f51fc2ca.PNG)

3. difference between HTML and rst (jupyter notebook generated in jupyter lab)
![3i](https://user-images.githubusercontent.com/44382270/48679811-71d93380-eb49-11e8-8700-abe01040cee1.PNG)
![3ii](https://user-images.githubusercontent.com/44382270/48679812-71d93380-eb49-11e8-9f17-84a81e9d5557.PNG)

4. I think "Understanding Multiple Dispatch in Julia" should be before "Exploring Type Trees". I found it more clear if I started with this section. 

5. which style is correct: "i.e." or "i.e.," ?
![4i](https://user-images.githubusercontent.com/44382270/48679822-8ae1e480-eb49-11e8-82b2-45358ed1a478.PNG)
![4ii](https://user-images.githubusercontent.com/44382270/48679823-8ae1e480-eb49-11e8-843c-b51f2fedbb3e.PNG)

**Comment by yolsever** [comment]
Also the quoted link is broken:

Deducing and Declaring Types
We will discuss this in detail in "this lecture"

**Comment by yolsever** [comment]
I am not sure where the OP got his lecture file from but in mine it looks a little bit different. So, I list the errors I find in my version, namely: [(http://compare-lectures.quantecon.org/jl/generic_programming.html#)]

Quoted links are broken

> "When programming in Julia
> There is no "encapsulation") and most custom types." And the general structure is badly formatted with unnecessary brackets etc

> "In mathematics, a "Ring")". 

This bracket problem persists across the lecture, I suspect there is a problem in structuring the links in .rst file

> Thinking back to the mathematical motivation, "a Field)" is

**Comment by PooyaFa** [comment]
@yolsever  Yes, I addressed this problem in https://github.com/QuantEcon/lecture-source-jl/issues/345#issue-381940232

and in https://github.com/QuantEcon/lecture-source-jl/issues/249#issue-377037499.

**Comment by arnavs** [comment]
1. Since this involves lists in Jupinx, I think we can hold off on it for now.

2. Done 

3. Same as 1.

4. I disagree. Multiple dispatch is when Julia will look at your tuple of argument types and traverse the method signatures to find the lowest parent tuple. That requires knowing what types are, how they have children and ancestors, etc. Also what methods and functions are.

5. The commas are more precise, done.
