### ISSUE TITLE
Code Execution Issues

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-jl#350]
With a timeout setting of 1200s the following notebook seems to have execution issues

```bash
2018-11-19 12:34:31,744[ERROR]execute_nb.py(524): career
```

**Comment by arnavs** [comment]
Hi @mmcky, just ran this lecture again locally and it looks like all the tests pass. Do you think we could relax the timeout to 25 minutes? This one is sitting around 21 on the server, and much less on my local machine.
