### ISSUE TITLE
Fix error in Arrays, Tuples, Ranges, and Other Fundamental Types

### ISSUE THREAD

**Issue by yolsever** [QuantEcon/lecture-source-jl#358]
The last code-block, namely 

` using QuantEcon

norm(our_solution - solve_discrete_lyapunov(A, Σ * Σ')) `

is failing in the notebook with error:

>  Info: Recompiling stale cache file /home/mmcky/.julia/compiled/v1.0/QuantEcon/V0Mv9.ji for QuantEcon [fcd29c91-0bd7-5a09-975d-7ac3f643a60c]
└ @ Base loading.jl:1187
ERROR: LoadError: MethodError: no method matching getindex(::ErrorException, ::Int64)

**Comment by jlperla** [comment]
Does this fail when you run it yourself, or are you reporting that the automatic running is failing in the build?

**Comment by arnavs** [comment]
Works on the local machine with no errors and the answer corresponds to what's on the build server, so closing.
