### ISSUE TITLE
Fix errors in data statistical packages

### ISSUE THREAD

**Issue by yolsever** [QuantEcon/lecture-source-jl#360]
Errors in while running the code in the html:

> ERROR: LoadError: Ipopt not properly installed. Please run Pkg.build("Ipopt")

> UndefVarError: mean not defined

Quoted links are broken:

> Working with Missing As we discussed in "fundamental types", the semantics 

Typo:

> is possible to to just

**Comment by arnavs** [comment]
Thanks for the typo, the other two (links and QELAP) are build issues.
