### ISSUE TITLE
ipopt doesn't load in optimizations_solvers

### ISSUE THREAD

**Issue by yolsever** [QuantEcon/lecture-source-jl#361]
Code not running for "function squareroot(x)" and the error carries over to the very next code-block
> ERROR:  LoadError: Ipopt not properly installed. Please run Pkg.build("Ipopt")

**Comment by arnavs** [comment]
Related to #368

**Comment by arnavs** [comment]
This works now, see http://compare-lectures.quantecon.org/jl/optimization_solver_packages.html#
