### ISSUE TITLE
Warning on name clash with Distributions.jl

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#363]
We frequently get
```
WARNING: using Distributions.mode in module Main conflicts with an existing identifier.
```
After we bump the versioning of the packages to `v0.9.1` or whatever to fix the `StatsPlots.jl` installation, we should see if it still happens (e.g. it happens with `generic_programming.rst` in the second code cell)) and fix if it does

**Comment by arnavs** [comment]
Goes away with the `v0.9.1` of QELP
