### ISSUE TITLE
QuantEcon.jl Precompilation Issues

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#364]
We need to resolve/investigate https://github.com/QuantEcon/QuantEcon.jl/issues/226, which is muddying the output.

**Comment by arnavs** [comment]
From @Nosferican

> The pre-compilation sporadic issue is not in QuantEcon, but in the Pkg stdlib... I think it is documented, but probably not a priority for Pkg folks.

cc @jlperla

**Comment by jlperla** [comment]
Maybe, but I don't think we see this with any other packages now that the precomipilation is working in the HTML output?

I flipped through a whole bunch of the lecture output and the only ones I see are ``StatPlots`` and ``QuantEcon``.    @arnavs  Are we ready to test things out with the bumped statplots version?  Maybe after we fix that and do #368 we can see if QuantEcon.jl is the only one left that is a problem.  It is possible that the QE.jl is also related to #368 as well...

Just for posterity, here is the error in  http://compare-lectures.quantecon.org/jl/fundamental_types.html#

```
┌ Info: Recompiling stale cache file /home/mmcky/.julia/compiled/v1.0/QuantEcon/V0Mv9.ji for QuantEcon [fcd29c91-0bd7-5a09-975d-7ac3f643a60c]
└ @ Base loading.jl:1187
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for Optim [429524aa-4258-5aef-a3af-852621145aeb]
│   exception = Required dependency NLSolversBase [d41bc354-129a-5804-8e4c-c37616107c6c] failed to load from a cache file.
└ @ Base loading.jl:966
┌ Warning: Module NLSolversBase with build ID 19199811453844568 is missing from the cache.
│ This may mean NLSolversBase [d41bc354-129a-5804-8e4c-c37616107c6c] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:944
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for QuantEcon [fcd29c91-0bd7-5a09-975d-7ac3f643a60c]
│   exception = ErrorException("Required dependency NLSolversBase [d41bc354-129a-5804-8e4c-c37616107c6c] failed to load from a cache file.")
└ @ Base loading.jl:966
┌ Info: Precompiling Optim [429524aa-4258-5aef-a3af-852621145aeb]
└ @ Base loading.jl:1189
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for Optim [429524aa-4258-5aef-a3af-852621145aeb]
│   exception = ErrorException("Required dependency LineSearches [d3d80556-e9d4-5f37-9878-2ab0fcc64255] failed to load from a cache file.")
└ @ Base loading.jl:966
WARNING: using QuantEcon.LQ in module Main conflicts with an existing identifier.
```

**Comment by arnavs** [comment]
Yeah, we're good to go with the StatPlots.

**Comment by jlperla** [comment]
OK.  No point doing this until #368 is complete, but at that point we should probably rerun the HTML output and see if the problem is still there.

**Comment by arnavs** [comment]
Update on this- problem still persists after QELAP, etc., and it looks like it applies to a few other packages as well. See: http://compare-lectures.quantecon.org/jl/aiyagari.html#, where (for ex.) we're also recompiling the NLsolversbase and plots. 

Do you think we need to just experiment with ways to suppress the precompilation output? Are there output-suppressed blocks in Jupinx?

**Comment by jlperla** [comment]
Closign for the #270 solution.
