### ISSUE TITLE
Small Equations

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#365]
When https://github.com/QuantEcon/sphinxcontrib-jupyter/issues/117 is resolved, we need to implement whatever changes (or Jupinx bump) comes out of it.

**Comment by mmcky** [comment]
A fix for this has been added as https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/152

No intervention will be required in the sources.

**Comment by arnavs** [comment]
Closing since that PR was merged.
