### ISSUE TITLE
Reparametrize Structs

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#367]
Need to go back in and, wherever we have a `struct` that we can't efficiently rip out, need to put back in the type annotations. 

See #320 for a list of `struct`s and `mutable struct`s.

**Comment by jlperla** [comment]
Yes but I would rather not add in parameters if we have time to get rid of the structs in the first place.  So maybe work thorugh anything else that can be done first, which may give us time to convert over the `struct`, and we can add in the parameters last minute (or even post-release) if necessar.

**Comment by arnavs** [comment]
OK, the structs are re-parametrized.
