### ISSUE TITLE
Jupinx test cases

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#369]
We should create an (untracked) `test_jupinx.rst` file with minimal examples of Jupinx bugs, so they're easily accessible from the comparison tool.

**Comment by jlperla** [comment]
We can have it in git, but just not put it in the tree of lectures (i.e. not in any indices)?

**Comment by arnavs** [comment]
Right, exactly. Sorry should've been more clear on "untracked"

**Comment by arnavs** [comment]
Done.
