### ISSUE TITLE
Problems in testing

### ISSUE THREAD

**Issue by yolsever** [QuantEcon/lecture-source-jl#374]
Broken links:

> If you navigate to your git repo (ours is "here")

Error:
Even though the code does not fail on the website, the expected result is this:

> using QuantEcon # fails, even though QuantEcon is on the machine

Test output is not reflecting the expected value:

>  Testing ExamplePackage Resolving package versions...

> Test  Summary:     | ExamplePackage.jl | No tests    Testing ExamplePackage tests passed 

Link broken:

> As mentioned in "version control"

> relevant section of the "version control"

**Comment by arnavs** [comment]
Thanks so much @yolsever for this feedback
