### ISSUE TITLE
Some Issues about general_packages lecture

### ISSUE THREAD

**Issue by PooyaFa** [QuantEcon/lecture-source-jl#377]
1. versions are not the same the setup part (jupyter notebook generated by rst file and HTML version have different setups versions : version 0.9.0 and 0.1.2 ) :
![5i](https://user-images.githubusercontent.com/44382270/48742204-d44a3680-ec12-11e8-910a-8e5a9c6afdb3.PNG)
![5ii](https://user-images.githubusercontent.com/44382270/48742205-d4e2cd00-ec12-11e8-8692-9484d2ed5002.PNG)

2. Different versions in above results in an error using ``using FastGaussQuadrature``. 
![1](https://user-images.githubusercontent.com/44382270/48742241-f93ea980-ec12-11e8-8727-2af5f4dc9162.PNG)
![2](https://user-images.githubusercontent.com/44382270/48742242-f93ea980-ec12-11e8-8061-a2fc9e391d4b.PNG)

3. Is ".. points" a notation for "n" points for example?
![4](https://user-images.githubusercontent.com/44382270/48742382-94d01a00-ec13-11e8-8d34-9be9a8b156a9.PNG)

**Comment by arnavs** [comment]
Thanks @PooyaFa.

1. You may be on an old version. The v0.1.2 of QELAP was from a few weeks ago. Try running a `git pull`. FWIW, it seems to work fine on the server. 

2. Should resolve the above. 

3. Fixed, thank you.
