### ISSUE TITLE
Global scoping in code and Jupyter 

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#39]
It appears that IJulia in the latest version has https://github.com/stevengj/SoftGlobalScope.jl

Built in. We should try it, as I believe this is a tagged release with v1.0 on Windows now. If so, then it means we can avoid the `let` blocks.

It would still have trouble if that code is copied to a REPL without modification (or embedding in a function or `let`, but I would bet money that this sort of Soft global thing is built into the REPL before too long 

Cc: @arnavs @Nosferican

**Comment by Nosferican** [comment]
@arnavs Could you drop the few `let` blocks from the first lectures?

**Comment by arnavs** [comment]
Yeah already on it, since otherwise tests can't access variables.

**Comment by Nosferican** [comment]
Maybe proto the test suite for to ensure it works after that? If all good, I can put the tests as I work on the updating.

**Comment by Nosferican** [comment]
SoftScope is implemented in IJulia.
