### ISSUE TITLE
Test Travis CI Lecture Again

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#407]
We've iterated this on a bit to identify pain points, but I'd like to run through this again since it's the most demanding of the "software engineering" section. Assigning @yolsever since you said weekends were productive for you? 

Let's not worry about formatting on this run, just content. The goal is to make sure there is no confusion or ambiguity in the instructions, and that they're accessible _as written_ to a complete novice. What you should do is: 

(1) Pull the latest `master` branch from GitHub. 

(2) Compile the Jupyter notebooks with `make jupyter`

(3) Open the `testing.ipynb` file that's created in `_build/jupyter`

(4) Run through the instructions, and do a bit of a stress test. What happens if I make an error somewhere, can I easily recover or am I screwed for the rest of the lecture? What happens if I try to run the sections out of order, etc? Assume the reader is neither too bright nor too diligent about this.

File your results as a git issue, or, even better, a PR.

**Comment by yolsever** [comment]
*** git user.name and user.email had to be set before adding the package but there is no note about this
:: 'user.name' missing, package generation will fail unless you supply a GitConfig

*** The screenshots are too small

*** I got the following error when I changed ExamplePackage and I broke something in the source code trying to solve this. Julia stopped compiling packages and I had to restart by removing the package

> Package ExamplePackage does not have Distributions in its dependencies

*** cant do this::

> From an activated (ExamplePackage) REPL, simply run ] test (recall that you can activate with ] activate ExamplePackage)

*** "travis badge" on readme is actually called "build"

*** codecov takes a lot of time to update stuff so I could not see the results of testing for +5 min

**Comment by arnavs** [comment]
Thanks Kaan. Some of this stuff would be resolved by running the `version_control` lecture first, but we should definitely make a note of it.

**Comment by arnavs** [comment]
Would be great if you could reproduce the steps that broke the package manager, but I suspect this is because you couldn't generate the package properly ab initio? Not sure
