### ISSUE TITLE
logical flow of getting started lecture

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-source-jl#409]
Below [this heading](http://compare-lectures.quantecon.org/jl/getting_started.html#Installing-Julia-and-Dependencies) there have a picture of the REPL.  [Later](http://compare-lectures.quantecon.org/jl/getting_started.html#The-REPL) it's introduced as if for the first time.  

Some reference back to the earlier discussion would improve the flow.  

Also, JupyterHub is mentioned in the first sentence after

http://compare-lectures.quantecon.org/jl/getting_started.html#The-REPL

although it has not been discussed previously (due to reorder of content).  Suggest adding "(see below)" or a hyperlink.

**Comment by arnavs** [comment]
Thanks professor, will fix these when I’m back at my desk.

**Comment by arnavs** [comment]
Done.
