### ISSUE TITLE
Smoke Test

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#413]
For when we go through each lecture and scroll through. Will need to wait until we build the latest. 

Active template for checklists:

## Getting Started with Julia
- [ ] [Setting up your Julia Environment](http://compare-lectures.quantecon.org/jl/getting_started.html)
- [ ] [An Introductory Example](http://compare-lectures.quantecon.org/jl/julia_by_example.html)
- [ ] [Julia Essentials](http://compare-lectures.quantecon.org/jl/julia_essentials.html) 
- [ ] [Fundamental Types](http://compare-lectures.quantecon.org/jl/julia_arrays.html)  
- [ ] [Introduction to Types and Generic Programming](http://compare-lectures.quantecon.org/jl/introduction_to_types.html)  

## More Programming and Software Engineering Principles
- [ ] [Generic Programming](http://compare-lectures.quantecon.org/jl/generic_programming.html)
- [ ] [General Purpose Packages](http://compare-lectures.quantecon.org/jl/general_packages.html)
- [ ] [Data and Statistical Ecosystem](http://compare-lectures.quantecon.org/jl/data_statistical_packages.html)
- [ ] [Solvers, Optimizers, AD](http://compare-lectures.quantecon.org/jl/optimization_solver_packages.html)
- [ ] [Tools and Editors](http://compare-lectures.quantecon.org/jl/tools_editors.html)
- [ ] [GitHub and Version Control](http://compare-lectures.quantecon.org/jl/version_control.html)
- [ ] [Testing and CI](http://compare-lectures.quantecon.org/jl/testing.html)
- [ ] [The Need for Speed](http://compare-lectures.quantecon.org/jl/need_for_speed.html)

## Tools and Techniques 
- [ ] [Linear Algebra](http://compare-lectures.quantecon.org/jl/linear_algebra.html)
- [ ] [Orthogonal Projections and their Applications](http://compare-lectures.quantecon.org/jl/orth_proj.html)
- [ ] [LLN and CLT](http://compare-lectures.quantecon.org/jl/lln_clt.html)
- [ ] [Linear State-Space Models](http://compare-lectures.quantecon.org/jl/linear_models.html)
- [ ] [Finite Markov Chains](http://compare-lectures.quantecon.org/jl/finite_markov.html)
- [ ] [Continuous State Markov Chains](http://compare-lectures.quantecon.org/jl/stationary_densities.html)
- [ ] [A First Look at the Kalman Filter](http://compare-lectures.quantecon.org/jl/kalman.html)

## Dynamic Programming 
- [ ] [Shortest Paths](http://compare-lectures.quantecon.org/jl/short_path.html)
- [ ] [Job Search I: The McCall Search Model](http://compare-lectures.quantecon.org/jl/mccall_model.html)
- [ ] [Job Search II: Search and Separation](http://compare-lectures.quantecon.org/jl/mccall_model_with_separation.html)
- [ ] [A Problem that Stumped Milton Friedman](http://compare-lectures.quantecon.org/jl/wald_friedman.html)
- [ ] [Job Search III: Search with Learning](http://compare-lectures.quantecon.org/jl/odu.html)
- [ ] [Job Search IV: Modeling Career Choice](http://compare-lectures.quantecon.org/jl/career.html)
- [ ] [Job Search V: On-the-Job Search](http://compare-lectures.quantecon.org/jl/jv.html)
- [ ] [Optimal Growth I: The Stochastic Optimal Growth Model](http://compare-lectures.quantecon.org/jl/optgrowth.html)
- [ ] [Optimal Growth II: Time Iteration](http://compare-lectures.quantecon.org/jl/coleman_policy_iter.html)
- [ ] [Optimal Growth III: The Endogenous Grid Method](http://compare-lectures.quantecon.org/jl/egm_policy_iter.html)
- [ ] [LQ Dynamic Programming Problems](http://compare-lectures.quantecon.org/jl/lqcontrol.html)
- [ ] [Optimal Savings I: The Permanent Income Model](http://compare-lectures.quantecon.org/jl/perm_income.html)
- [ ] [Optimal Savings II: LQ Techniques](http://compare-lectures.quantecon.org/jl/perm_income_cons.html)
- [ ] [Consumption and Tax Smoothing with Complete and Incomplete Markets](http://compare-lectures.quantecon.org/jl/smoothing.html)
- [ ] [Optimal Savings III: Occasionally Binding Constraints](http://compare-lectures.quantecon.org/jl/ifp.html)
- [ ] [Robustness](http://compare-lectures.quantecon.org/jl/robustness.html)
- [ ] [Discrete State Dynamic Programming](http://compare-lectures.quantecon.org/jl/discrete_dp.html)

## Multiple Agent Models
- [x] [Schelling's Segregation Model](http://compare-lectures.quantecon.org/jl/schelling.html)
- [ ] [A Lake Model of Employment and Unemployment](http://compare-lectures.quantecon.org/jl/lake_model.html)
    - [ ] Precompilation message
- [ ] [Rational Expectations Equilibrium](http://compare-lectures.quantecon.org/jl/rational_expectations.html)
    - [ ] Using LinearAlgebra again (remove it from `using`)
- [ ] [Markov Perfect Equilibrium](http://compare-lectures.quantecon.org/jl/markov_perf.html)
    - [ ] Using LinearAlgebra again (remove it from `using`)
    - [ ] Alignment of arrays
- [x] [Asset Pricing I: Finite State Models](http://compare-lectures.quantecon.org/jl/markov_asset.html)
- [x] [Asset Pricing II: The Lucas Asset Pricing Model](http://compare-lectures.quantecon.org/jl/lucas_model.html)
- [ ] [Asset Pricing III: Incomplete Markets](http://compare-lectures.quantecon.org/jl/harrison_kreps.html)
    - [ ] Using LinearAlgebra again (remove it from `using`)
    - [ ] In `price_optimistic_beliefs` and `price_pessimistic_beliefs` use `norm`
- [x] [Uncertainty Traps](http://compare-lectures.quantecon.org/jl/uncertainty_traps.html)
- [ ] [The Aiyagari Model](http://compare-lectures.quantecon.org/jl/aiyagari.html)
    - [ ] Use `@unpack` for all possible values (e.g., `am.Q`, `am.R`, etc.)
- [ ] [Default Risk and Income Fluctuations](http://compare-lectures.quantecon.org/jl/arellano.html)
    - [ ] Precompilation message
- [ ] [Globalization and Cycles](http://compare-lectures.quantecon.org/jl/matsuyama.html)
    - [ ] Plots splatting
    - [ ] `range(0,  ` with extra spaces
## Time Series Models
- [ ] [Covariance Stationary Processes](http://compare-lectures.quantecon.org/jl/arma.html)
- [ ] [Estimation of Spectra](http://compare-lectures.quantecon.org/jl/estspec.html)
    - [ ] Calculation markdown section has deprecated syntax and mathematically questionable
           `abs(fft(X)).^2 / length(X)` should probably be `fft.(X).^2 / length(X)`
    - [ ] `function hanning_window(M)` should be in compact form `hanning_window(M) = `
    - [ ] Legend placement is less than ideal, but it might best feasible
- [ ] [Additive Functionals](http://compare-lectures.quantecon.org/jl/additive_functionals.html)
- [ ] [Multiplicative Functionals](http://compare-lectures.quantecon.org/jl/multiplicative_functionals.html)
- [ ] [Classical Control with Linear Algebra](http://compare-lectures.quantecon.org/jl/lu_tricks.html)
- [ ] [Classical Filtering with Linear Algebra](http://compare-lectures.quantecon.org/jl/classical_filtering.html)

## Dynamic Programming Squared
- [ ] [Dynamic Stackelberg Problems](http://compare-lectures.quantecon.org/jl/dyn_stack.html)
- [ ] [Optimal Taxation in an LQ Economy](http://compare-lectures.quantecon.org/jl/lqramsey.html)
- [ ] [Optimal Taxation with State-Contingent Debt](http://compare-lectures.quantecon.org/jl/opt_tax_recur.html)
- [ ] [Optimal Taxation without State-Contingent Debt](http://compare-lectures.quantecon.org/jl/amss.html)

**Comment by arnavs** [comment]
Assigning the RAs but of course if capacity constraints are binding then that's OK.

**Comment by jlperla** [comment]
Just to be clear, though, we can't smoke test until the testing is turned off in the HTML output

**Comment by arnavs** [comment]
Right, should've made that explicit.

**Comment by mmcky** [comment]
Thanks @arnavs and @jlperla this will be great to pick up smaller bugs that haven't been found yet.

**Comment by arnavs** [comment]
OK, we can start now. Basically, check off a lecture above once you think it could be pushed to the `lectures.quantecon.org` without issues. Things to watch for include (a) errors in code, including package errors or workflow mistakes, (b) errors in logic, such as saying things are increasing when they aren't, (c) errors in math (mainly for McCall I and II). See the #313 for a more detailed list.

Don't worry about screenshots or site wide infrastructure like breadcrumbs for now. Can leave your results as a PR (ideal) or an issue with the v1.0 milestone.

cc @jlperla @Nosferican @natashawatkins

**Comment by arnavs** [comment]
Also, we can edit the thing below to make sure changes aren't repeated. 

## Getting Started with Jupyter

Getting Started: List Error (extra enumeration)
By Example: Move to `deps_no_using` for style

**Comment by Nosferican** [comment]
@ajozefiak @yolsever Feel free to pick the small issues on lectures, for example, fix an extra space or so those are low hanging fruits. Most should be trivial at this point.

**Comment by arnavs** [comment]
Just going to add an addendum to the above that you shouldn't change things in `master` (e.g., whitespace tweaks, deleting `using`, etc.) unless something is truly broken. The rest of that stuff can wait for `v1.1` when there's time to consider it thoroughly and do it uniformly.
