### ISSUE TITLE
Referring to Named Tuples

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#419]
How should we refer to the named tuple objects/constructors that we put it in when we ripped out the `struct`? It feels awkward to say 'named tuple' all the time, and 'anonymous type' might be a bit too advanced.... Not sure.

cc @jlperla @Nosferican

**Comment by jlperla** [comment]
Can you give a link to where you think it is awkward? Tuple is perfectly fine on most circumstances when named tuple seems excessive

**Comment by arnavs** [comment]
There are a few instances like "below we define a type which..." or "use the type we created above..." I'll find a few and link them.
