### ISSUE TITLE
Update packages on build server

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-jl#420]
- [x] `RDataSets` appears to be required but then loads on `using` later in the lecture?

```
ArgumentError: Package RDataSets not found in current path:
- Run `import Pkg; Pkg.add("RDataSets")` to install the RDataSets package.


Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:823
 [2] top-level scope at In[2]:2
```

**Comment by mmcky** [comment]
- [ ] This Voyager interactive popup times out when running headless

```
Voyager(Electron.Window(Application(Base.PipeEndpoint(RawFD(0x00000033) paused, 0 bytes waiting), Process(`/home/matthewmckay/.julia/packages/Electron/IV1np/src/../deps/electron/electron /home/matthewmckay/.julia/packages/Electron/IV1np/src/main.js /tmp/juliaelectron-85592-1 /tmp/juliaelectron-sysnotify-85592-1 SWan7okTSkOPk2bH0O4gdeZE0duUnGy2raHU0DU3UfETWIQPc9V06uFX9PciQpjfWjznj8r5s7SAteH61KNuXJKUbARngErQ3o970UenTZaN7mb1/O5qELax5p2ojep5m83Lx4qlXEs4Ne8U70EtWyw7n57lBtv2ynUO34ejNHU=`, ProcessRunning), [1 window]), 1, true, Channel{Any}(sz_max:128,sz_curr:0)))
```

**Comment by mmcky** [comment]
- [ ] does this package in ``getting_started`` need to match our precompiler script?

```
activate_github("QuantEcon/QuantEconLecturePackages", tag = "v0.9.4");
```

**Comment by arnavs** [comment]
Yes, it should match (versions should be the same throughout). 

RDatasets is in the all deps. Did something break there? And we can no-execute the voyager pop up line if need be.

In transit for a bit will be online later tonight.

**Comment by jlperla** [comment]
For the voyager, we don't have to run that code when generating the lecture notes... Should we turn those lines into a no-execute? People running the notebooks in jupyter would have to manually copy that into code cells, but I don't think that is so bad...

**Comment by arnavs** [comment]
The `RDatasets` issue was because I spelled it wrong in the earlier block (`RDataSets` instead of the correct `RDatasets`). Fixed now.

**Comment by arnavs** [comment]
Eliminated the voyager popup etc. so we can close now.
