### ISSUE TITLE
Weird Formatting/jldoctest output in tools_editors

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#423]
### RST 

```
Help Mode 
---------------

Hitting ``?`` will bring you into help mode 

The key use case is to find docstrings for functions and macros, e.g. 

.. code-block:: julia 

    ? print 

Note that objects must be loaded for Julia to return their documentation, e.g. 

.. code-block:: julia 

    ? @test 

will fail, but 

.. code-block:: julia 

    using Test 

.. code-block:: julia 

    ? @test 

will succeed 
```

### Output 

http://compare-lectures.quantecon.org/jl/tools_editors.html#The-REPL and scroll down to help mode 

This is related to the issue @jlperla identified of the huge headers etc. from the code. 

I'm going to make these no-executes for now, but worth documenting this as a Jupinx issue. 

cc @mmcky

**Comment by jlperla** [comment]
For this specific case, I think it is perfectly reasonable to just not show any of the output, and leave the `] ?` a no-execute.

More generally with the `?` output, I think we are better off just pasting in part of the output and reformatting it.  It isn't essential to run the `? foo` in any notebooks, so it is more informational.

**Comment by arnavs** [comment]
Makes sense. Closing now since I changed to no-execute.
