### ISSUE TITLE
Missing call to f() with FooNotTyped

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#425]
http://compare-lectures.quantecon.org/jl/introduction_to_types.html#Issues-with-Type-Declarations

**Comment by jlperla** [comment]
Also `f(Foo4)` is probably worth showing.  But make sure to show the `@show typeof(foo)`

**Comment by jlperla** [comment]
See #688   @arnavs  handing over to for a sanity check.  If it passes coverage without errors, we should be good.

**Comment by arnavs** [comment]
Closing per #688
