### ISSUE TITLE
Rendering of blackboard R not working in jupyterlab or jupyter notebook

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#437]
The `\RR` macro, which must be in some latex preamble for the HTML - where it works great, isn't working for either jupyter technology.  See the following, for example.

Not a show-stopper.

![image](https://user-images.githubusercontent.com/13106721/49180329-2c66f400-f309-11e8-9875-68be7d169482.png)

**Comment by jstac** [comment]
This has always caused us problems on and off.  I've asked @mmcky  to replace them all with `\mathbb R` and we'll use that in the future.

**Comment by jlperla** [comment]
Sounds good.  So we can just go through and replace `\mathbb{R}` as the solution globally?

**Comment by jlperla** [comment]
@arnavs  has done the change.

**Comment by jstac** [comment]
Great.  There might be a few `\ZZ`s and `\NN`s in there too.

Oh, and `\EE` and `\PP`, now I think about it.  (Expectation and probability.)

**Comment by jlperla** [comment]
Here is an example http://nbviewer.jupyter.org/url/compare-lectures.quantecon.org/_downloads/ipynb/jl/orth_proj.ipynb 

I think that pretty much everything in the python's latex preamble is a problem, which are in the `conf.py` .  @mmcky Is there no easy way to get that latex into the notebooks for MathJax?

**Comment by arnavs** [comment]
OK, I've gone and replaced all instances of `\xX` with the appropriate command (e.g., `\mathcal{F}` or `\mathbb{E}`, etc.).

**Comment by arnavs** [comment]
I think this is done now? Closing but @jlperla can reopen if there's anything left for the v1.1 milestone.
