### ISSUE TITLE
Decrease the error output in fundamental types, or explain why we are showing insane errors

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#440]
http://compare-lectures.quantecon.org/jl/fundamental_types.html#

Perhaps showing and explaining the error insanity is better... at least once...

**Comment by arnavs** [comment]
Added two lines here:

```
More precisely, the error is that there isn't an implementation of ``*`` for two one dimensional vectors

The output explains this, and lists some other methods of ``*`` which Julia thinks are close to what we want
```

Will leave this open until Jesse can review (I decided to take some time and crunch through the easy cleanup tasks on these.)

**Comment by jlperla** [comment]
@arnavs  I will hand this back to you.  I like your text for this.

**Comment by jlperla** [comment]
Oops, it is already done!  Closing.
