### ISSUE TITLE
Resizing of images/snippets of imagtes in the version_control and packages/testing

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#445]
There are a lot of screenshots that are zoomed out but still massive, and a few that are not zoomed or snipped.  Minor issue, but will look more polished if we iterate on these

**Comment by jlperla** [comment]
Don't forget about the first two lectures are heavily image based as well

**Comment by arnavs** [comment]
Moving this to testing mode. We'll see how it looks in the next hourly build.
