### ISSUE TITLE
JupyterLab smoke test

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#450]
Run a few of the notebooks in Jupyterlab (esp. stuff like `amss, orth_proj, linear_algebra` where we changed a lot of the math) and make sure that things are solid.

**Comment by jlperla** [comment]
I just wanted to make sure that you did a few of these with the latest version.  If so, I think we should close.

**Comment by arnavs** [comment]
Thanks for bumping. Still see the occasional math issue (seems stochastic) in the Jupyter downloads and source builds. For ex., the image below built from source, or a `\col` in the `orth_proj` download (near "the following result uses the preceding algorithm...") HTML looks fine in both cases. 

![mangled-math](https://user-images.githubusercontent.com/5009477/49535950-45782380-f87a-11e8-807e-4de619b0d713.PNG)

**Comment by jlperla** [comment]
If it is stochatic, it could just be bugs in jupyterlab and mathjax.  If the code works, I think we are in business.

**Comment by arnavs** [comment]
Perfect, never saw any code issues. So will close now then.
