### ISSUE TITLE
Get rid of remaining pyplot and latexstrings

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#469]
I am still seeing some `pyplot()` used instead of `gr()`.  There is no reason to think that the pyplot backend would be installed (even if it is on the build server).

I think these may be coming in from `.jl` includes rather than rst files.  In particular
- [x] `paths_and_hist.jl` included in `linear_models`
- [x] `mccall_vf_plot1.jl` in `mccall`, if it is used....

For these, I would much rather just merge the code into the RST so we don't have this sort of hidden include issue again, if possible.

**Comment by arnavs** [comment]
Second file isn't used. First file isn't used in a lecture either, but rather is linked as a "code for this figure can be found [here](link)..." type thing. Will eliminate it from the file.

**Comment by jlperla** [comment]
OK.  If it is not actually used in the jupyter notes, then that is fine.  I thought I saw code for it with the pyplot backend and latexstrings, but maybe it is a false-positive.  It could be that I clicked on something in the compare-lectures and accidentlaly saw an old version.

**Comment by arnavs** [comment]
Done. Had to undeprecate the `paths_and_hist` a little bit. Can't find any reference to the `mccall_vf_plot1.jl` so figure it's been removed.
