### ISSUE TITLE
Legend in arma plots

### ISSUE THREAD

**Issue by Shunsuke-Hori** [QuantEcon/lecture-source-jl#483]
Most of the figures in Covariance Stationary Process lecture (arma) have odd legends, for example,

![image](https://user-images.githubusercontent.com/25315074/49953534-21889380-feb3-11e8-8c31-e9d53547d211.png)

They used to be correct
https://github.com/QuantEcon/lecture-source-jl/commit/b53a336270436ce5c507b45178ce657aa18ab6bc#diff-5deb0d38adabea182b6a883a673e1926R248

**Comment by arnavs** [comment]
Hey @Shunsuke-Hori, thanks for the issue. 

It looks like the only difference in the legends is that the old ones used `LaTeXStrings` and these don't. That was actually a conscious decision on our part. See #327.

Will close this issue, but please re-open if I've missed something.

**Comment by arnavs** [comment]
Actually, now that I think about it, we could probably do better by interpolating the actual value into the legend (which is likely what you had in mind?). Will make that change.

**Comment by Shunsuke-Hori** [comment]
@Shunsuke-Hori Yes, that's what I meant, like python version:

![image](https://user-images.githubusercontent.com/25315074/49966759-c74cfa00-fed5-11e8-9481-c4b072073b43.png)

**Comment by arnavs** [comment]
Perfect. Sorry, saw the `latexstring` call and thought that's what you meant. But in any case, took care of it in the commit above.

**Comment by Shunsuke-Hori** [comment]
@arnavs thank you for the commit. I think next figure should be fixed as well

![image](https://user-images.githubusercontent.com/25315074/49967015-87d2dd80-fed6-11e8-857a-6634bdfb61f4.png)

**Comment by arnavs** [comment]
Yup, that was also included `:-)`

https://github.com/QuantEcon/lecture-source-jl/commit/d7808395153ac5d80f805803434d93580e19daec#diff-5deb0d38adabea182b6a883a673e1926R488

**Comment by Shunsuke-Hori** [comment]
@arnavs Oh, sorry. I didn't see that. Thank you for all the work!!
