### ISSUE TITLE
Build base docker image with julia (no jupyter) and test within CI

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#484]
- [x] Figure out the base image (use the julia base one)
- [x] Add in the code to precompile the QELP (not the QEALP)
- [x] Figure out how to use this for a simple travis test, changing the image used.

**Comment by jlperla** [comment]
See https://docs.travis-ci.com/user/docker/#using-a-docker-image-from-a-repository-in-a-build as a starting point.

**Comment by jlperla** [comment]
See https://github.com/QuantEcon/docker/issues/7 for naming discussion

Based on that naming convention, this issue is for the `quantecon/julia` image.

**Comment by arnavs** [comment]
Done. See https://travis-ci.com/arnavs/dockertest.jl/builds/95037135#L410. The next step is to figure out how to cache the image (which Travis definitely used to support, so maybe they still do?).
