### ISSUE TITLE
Docker based sphinx builds for the lecture notes

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#488]
When https://github.com/QuantEcon/docker/issues/8 is done, we should test it out with these lecture notes.
- [ ] Edit https://github.com/QuantEcon/lecture-source-jl/blob/master/README.md for the docker instructions.  
- [x] Consider setting up a data volume like https://lectures.quantecon.org/jl/tools_editors.html#Docker
- [x] Clone the lecture notes to a local folder
- [x] Test `make jupyter` or whatever and add to the instructions
- [x] Tell them how to run a particular notebook in jupyter.

**Comment by arnavs** [comment]
@ajozefiak Once you're done with your exams (I believe tomorrow?), this is the task that we'll tackle together. So maybe swing by the office and we can go over it. For now, maybe follow https://github.com/quantecon/docker, which is the companion repo.

**Comment by arnavs** [comment]
I added a step to clone the notebooks repo  to the https://github.com/arnavs/jupinx-test, which works great (just fire up the image and then click on the `lecture-jl-notebooks` directory). And it's in a data volume, so changes I make to the notebooks persist from one run to the next. 

Will leave this issue open until confirmed with @jlperla, at which point I'll edit the instructions etc.
