### ISSUE TITLE
See if :scale: => :width: breaks HTML; if so, tweak build

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#502]
@arnavs  From #498 we saw issues with the new introductory lectures.  Download the live QE lectures to see if these are an issue, etc.

If so, track and submit to the sphinxjupyter repo

**Comment by arnavs** [comment]
Downloaded notebooks look fine on my mac but fails on Ubuntu. Will try to pin down the issue.

**Comment by arnavs** [comment]
@mmcky It looks like we can resolve this by removing the `style = <"width:100%;height:100%">` directive, which Ubuntu (and maybe Windows?) are taking too seriously.

**Comment by jlperla** [comment]
@arnavs Do a final sanity check.

**Comment by arnavs** [comment]
Still seeing issues on my machine (Ubuntu box) with the latest downloads of `getting_started` and `julia_environment`. Tried `conda update jupyter` and nothing changed.

**Comment by jlperla** [comment]
@arnavs Can you get people to track this down to see if it happens on OSX/Firefox/Windows/etc.?  I used to see it in Chrome, so I don't think it is a firefox only issue.

**Comment by arnavs** [comment]
Will do. I will give the data to @AakashGfude, who said he could take a look.

**Comment by jlperla** [comment]
I  wanted to check in on this problem.  It is still a major issue!

**Comment by arnavs** [comment]
Hey @jlperla, thanks for bumping this.

Aakash found that it's browse or monitor-dependent (i.e., he can't reproduce on his end). He says: 

> At present we are just giving it 100% on both width and height, so we are forcing it to take the aspect ratio of the container

An interim approach (which seemed to work) is to set `width` to 100%, and `height` to `auto`. I'll prep some files for this tonight and we can see if it passes tomorrow.

**Comment by jlperla** [comment]
Sounds good.  I can test on my computers, as I have never "not" reproduced it.

**Comment by arnavs** [comment]
Yeah, this approach works for `JupyterLab`. 

We'll need to see if it works with the HTML. Otherwise, we can just tweak the generation of the notebooks for download. 

Will rename this issue appropriately, etc.

**Comment by AakashGfude** [comment]
Hey @jlperla @arnavs did it work?

**Comment by arnavs** [comment]
Hey @aakashGfude looks like it. We just need to make sure it doesn’t break the HTML display. If we could push to the preview area tomorrow, that would help. 

I’ll be pushing on the infrastructure this week so let’s touch base tmw if possible.
