### ISSUE TITLE
Add notebook cloning into setup lecture

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#503]
cc @mmcky 
We now have the notebooks to https://github.com/QuantEcon/lecture-jl-notebooks we can add cloning the github repository to the setup.

We can add to the current intro-reorg branch.  I put in a few `TODOGITHUB` there with the places that we should add this, but to summarize:
- [x] The desktop installation should be very clear and explicit, whereas the jupyterhub one can be barebones for now.
- [x] Triple-check that the workflow works if they are cloning and opening notebooks vs. reading on the web.  i.e. if they clone to their desktop, when/how do we tell them to open the notebook.

For the github:
- [x] Put in the same github setup
```
Install git and the GitHub Desktop application

Install git
Install the GitHub Desktop application
```
- [x] Put a link to the Github lecture for "more details"
- [x] Make clear Github desktop is not required, but the easiest approach
- [x] After installation, tell people to go to the site and show the screenshot with the "clone or open".
- [x] Can give them the url for the cloning as well in the text
- [x] In the running jupyter lab section, we tell them to navigate to that folder they cloned (give examples on windows and OSX paths).
- [x] In the "interacting" section, we point back to this section to say "the easiest way to get access to the notebooks is to clone them..."

**Comment by arnavs** [comment]
Closing this as edits would be made on the commits/PR.
