### ISSUE TITLE
Get rid of structs 

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#504]
As of #320 

### Structs and Mutable Structs 

Mutable Structs: 

- [ ] `amss` (#159)
- [x] `odu` (agent-based model)
- [ ] `opt_tax_recur`
- [x] `uncertainty_traps`
- [x] `lake_model` (almost done)

Structs: 

- [x] `lu_tricks` (#559)
- [ ] `amss` (#159)
- [x] `hist_dep_policies`
- [x] `jv`
- [x] `lqramsey` (used for dispatch)
- [x] `odu`
- [ ] `opt_tax_recur`
- [x] `lake_model` (above)

**Comment by arnavs** [comment]
Closing as the remaining structs are either used for dispatch (e.g., continuous vs discrete economies with the same fundamental objects), or are mutable and so under #237

**Comment by jlperla** [comment]
Did we say that the mutable structs should remain mutable?  In general we should avoid mutability if at all possible.

**Comment by arnavs** [comment]
One of these makes sense (it's for an agent-based model, where the structs represent the agents.) The other two are in very complicated/code-dense lectures (`amss` and `opt_tax_recur`). I think it was decided it's best to leave those two as-is.
