### ISSUE TITLE
Add nbutils and document workflow

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#505]
- [ ] Consider adding the `nbutils.ipynb` type thing (i.e., the thing in https://github.com/ubcecon/econ407_2019, which lets you run cells to do git operations like updating notebooks, undoing local changes, nuking all user created files and changes, etc.) 

- [ ] Confirm with Matt about the executable cell (i.e., can run it with shift-enter) that isn't executed by the build server (for git magic). Should it be a `.. code-block:: python` with `:class: no-execute`?

**Comment by jlperla** [comment]
@arnavs Can you add this into (after the rename) to the root of the rst source as a dependency, and have it deployed to the notebook repository?
[utilities.ipynb.txt](https://github.com/QuantEcon/lecture-source-jl/files/3536914/utilities.ipynb.txt)

**Comment by jlperla** [comment]
Actually, I have a change of heart on this.  I think the "delete and repull" workflow will be easier to use with the launch support built in.  So hold off on this for now.
