### ISSUE TITLE
Investigate doing a forced push of git with notebooks

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#509]
@mmcky @sglyon @cc7768

I am putting this issue here, but it equally applied to the datascience course once that notebook repo is setup.

The issue we have is that ipynb have terrible diffs, especially with embedded images.  So if we do a commit everytime we push the notebooks to the repo, it will quickly end up massive (and anyone cloning it gets the entire history).  What we really want is just a git mirror of the notebooks, and the revision history is not essential.

One thought is to see what would happen if we simply force a push and rewrite the git history each time we update it, instead of accumulating commits.  Git and github supports this, but the question is what happens for those using a jupyterhub or desktop UI.

I think the basic test is:
- [x] Create a temporary repo for testing that has a test notebook in it.  Put the nbutils.ipynb in there as well.
- [x] Clone that repo to a jupyterhub installation with nbgitpuller and onto the desktop using Github desktop
- [x] On a different computer than the github desktop installation, make a modification to the notebook and use the git command line to do a force push. of the new version, overwriting the older commit.
- [x] Verify that only the new commit is on github and the history is overwritten
- [x] Go to the GitHub desktop and do a "Pull".  See if is freaks out or if it behaves relatively normal
- [x] Redo the nbgitpuller call and see if the noteook gets updated, and whether it gets confused
- [x] Try the same thing again with a pull through nbgitpuller, an overwrite of the history on github, and the various resets in the nbutils.ipynb to see if that works for updates, or whether it somehow gets confused.

**Comment by arnavs** [comment]
First thing is that this will be difficult for GitHub desktop users, because GitHub will not delete local history with a `git pull` (you need a `git reset --hard origin/master` or something like that). 

So it'll try to give us something like the following, with a merge commit: 

```
arnavsood@Arnavs-MacBook-Pro-2:~/research/force-push-test$ git log
commit 623ae24a9708280b061a7ac9fd71465031c406f8 (HEAD -> master)
Merge: f5d5cf0 7ecb439
Author: Arnav Sood <soodarnav01@gmail.com>
Date:   Wed Jan 2 15:40:10 2019 -0800

    Merge branch 'master' of https://github.com/arnavs/force-push-test

commit 7ecb4398166b4f42779786f54f19517fc519e86c (origin/master, origin/HEAD)
Author: Arnav Sood <soodarnav01@gmail.com>
Date:   Wed Jan 2 14:01:03 2019 -0800

    force check in nbutils

commit f5d5cf002ac0fa1b32d133a92e2ecfa70daa6d50
Author: Arnav Sood <soodarnav01@gmail.com>
Date:   Wed Jan 2 14:01:03 2019 -0800

    check in nbutils

commit da5d04623e054ce0645ebaf8c59d24286246a9d0
Author: Arnav Sood <soodarnav01@gmail.com>
Date:   Wed Jan 2 13:54:10 2019 -0800

    add initial notebook
```

**Comment by jlperla** [comment]
When you say it won't delete the local history, does that mean things get out of whack, or that there is just garbage lying around in the directory?

Is a hard reset possible in the github desktop?

**Comment by arnavs** [comment]
No reset in the GUI yet, it's an open issue from 2 years ago- https://github.com/isaacs/github/issues/659. 

Nothing went out of whack in one round (i.e., it was just a few extra junk commits), but I'll verify what happens if the process is repeated.

**Comment by jlperla** [comment]
Give us a report after seeing if things get out of whack, or the notebooks are incorrect with a git pull. We can then see how the workflow is

**Comment by arnavs** [comment]
Thanks all for the suggestions. Here's what I found-

1. To overwrite the history, we can just stage our files and run a `git commit --amend`, followed by a force push. This solves the problem of maintaining a mountain of diffs.

2. The most robust approach is the `nbutils.ipynb`. It will update all our files, eliminate junk commits, etc. The granular updates also work (i.e., we can just do it for a single file, etc.). 

3. With `nbgitpuller`, I was seeing some quirks with their design decisions (i.e., files that were force-overwritten would get renamed, and then the new copy would be downloaded). You can solve this by nuking the directory contents and clicking the link again. 

4. With GitHub Desktop, I think it's fine so long as we discard all local changes. But this one I'm not 100% on --- I'll need to borrow an RA's computer until I get my Windows back up-and-running. 

So, I think this `force-push` approach will be workable. Let me know if there's anything else that I should investigate.

**Comment by arnavs** [comment]
Note that we'll need to tweak the nbutils a bit (and it would be easier if it wasn't tracked in git, so maybe they'll run a `git rm --cached nbutils.ipynb` cell as part of setup?). So we can iterate on and test that.

**Comment by jlperla** [comment]
Closing since generating extra copies of force rewritten files with nbgitpuller is a non-starter for that workflow.
