### ISSUE TITLE
JuliaBox Requirements

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#510]
cc @jlperla 

They've overhauled the Julia setup over the break (i.e., now it's Julia 1.0.3), so _a priori_ none of the old information is valid. 

## Things we need but can't fix 

* `InstantiateFromURL` - can't install any version after `v0.1.0` (i.e., no error handling that prevents a crash/tells people to add stuff manually). 
* I can't get `RDatasets` to work, even though it looks like it installs properly. Same with the `REPL` required for `] build NodeJS`, which is required for `VegaLite` and `DataVoyager`. 
* `FastGaussQuadrature` isn't in the registry, and we need it for the `general_packages` lecture. 

## Things we need and can fix (with workarounds)

* `] add Expectations`
* `] add StatPlots`
* `] add DataFramesMeta CategoricalArrays Query GLM RegressionTables FixedEffectModels`
* `] add QuadGK Interpolations LaTeXStrings ProgressMeter`
* `] add JuMP Ipopt BlackBoxOptim`
* `] build Ipopt`
* `] add LeastSquaresOptim` 

Lectures I tested: 

* McCall 
* Wald-Friedman
* Data and Statistical Packages 
* General Packages 
* Kalman 
* Lake Model 
* Lucas Model 
* Solvers, Optimizers, and Automatic Differentiation

**Comment by arnavs** [comment]
Closing as we're done testing this for the time being. Can re-open if we start again.

**Comment by jlperla** [comment]
I want to reopen until this is either dealt with or ignored. We can assign to me

**Comment by arnavs** [comment]
@jlperla Given what we talked about earlier (i.e., the phaseout of free JuliaBox), can this be closed now?
