### ISSUE TITLE
Precompiling Time in Julia Benchmarks

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#513]
The lecture execution benchmarks would be more meaningful if they were the result of second runs or averages of multiple runs or something like that (i.e., neglecting setup costs). 

- [x] Confirm with Matt to see if this already happens or not. (edit: it doesn't). 
- [ ] See if we can get this to happen for `v1.0` if it doesn't (run the script once, throw away the results, and run again?) 
- [ ] See if we can get `v0.6` data in the same way (i.e., for #401).

**Comment by jlperla** [comment]
I think this would be lower priority until we can get a container based build approach solid. There are a lot of other features more essential to automate

**Comment by jlperla** [comment]
@arnavs  Is this still relevant with the packagecompiler based image?

**Comment by arnavs** [comment]
@jlperla Not really. Good point.
