### ISSUE TITLE
Fix Credits

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#52]
We are moving to the crediting scheme in https://github.com/jstac/QuantEcon.lectures/issues/1195. 

Highlights: 

* Standardized format for coauthors at the top of each page. (when applicable)
* Removing all "inline" citations/attributions (e.g., in comments, cells, Markdown, etc.) and moving these to a global credits page. There should be no names in the code. 
* Credits page will be in a different repo. Details on where to submit them TBD. 

No need to duplicate the whole checklist here. Can just be mindful of this as we proceed with the rewrite, and then do a final pass to make sure we got them all. 

cc: @jstac, @jlperla, @Nosferican

**Comment by jlperla** [comment]
Sounds good. For now, if there is someone not listed in https://lectures.quantecon.org/about_lectures.html#id7 I think you should add a note to this issue so we don't lose them

**Comment by Nosferican** [comment]
Probably best to do all in one repo after the first pass.

**Comment by arnavs** [comment]
OK, per @jlperla, I did a first pass; below are the names of people whose names come up in the lectures but who aren't credited on the global attribution paragraph. Some of these cites are for `QuantEcon.jl` contributions which are tightly bound to the lectures. 

* Max Huber 
* Balint Szoke 
* Victoria Gregory 
* Willem Hekman 
* Guanlong Ren (with Will, for solving Ex. 1 in `linear_algebra`)
* Alberto Polo (for editing the `Wald_Friedman_jl.ipynb`
* Ranjan Ananthamaran (for working on `lss.jl` in QuantEcon, which powers the `linear_models` lecture). 
* Zac Cranko (for the `lqcontrol` file in the QuantEcon package). 
* Colin Beckingham (for work on the `QuantEcon.jl/src/markov/markov_approx.jl` file, which solves Exercise 3). 

Also, below is the table I was using to keep track of references to people by name. Doesn't directly apply to a task, but I figure it's useless to just destroy it. Some lines may omit frequent contributors.

Lecture Filename | Author(s) | Contributors | 
----------------- | ---------  | ------------
`additive_functionals` | Chase Coleman and Balint Szoke (joint) | Shunsuke Hori | 
`aiyagari` | N/A | N/A |
`amss` | N/A | N/A | 
`arellano` | N/A | Chase Coleman |
`arma` | N/A | N/A | 
`career` | N/A | N/A | 
`classical_filtering` | N/A | Shunsuke Hori | 
`coleman_policy_iter` | N/A | Shunsuke Hori, Spencer Lyon, John Stachurski | 
`discrete_dp` | N/A | Daisuke Oyama, Max Huber  | 
`dyn_stack` | N/A | Spencer Lyon, Victoria Gregory (for `dyn_stack/oligopoly.jl`), Zac Cranko (for `QuantEcon.jl/lqcontrol.jl`) | 
`egm_policy_iter` | N/A | Shunsuke Hori | 
`estspec` | N/A | Spencer Lyon, Shunsuke Hori |
`finite_markov` | N/A | Spencer Lyon, Chase Coleman, José, Natasha, Colin Beckingham | 
`harrison_kreps` | N/A | Shunsuke Hori | 
`hist_dep_policies` | N/A | Spencer Lyon, Victoria Gregory | 
`ifp` | N/A | N/A | 
`julia_arrays` | N/A | N/A | 
`julia_by_example` | N/A | N/A | 
`julia_essentials` | N/A | N/A | 
`julia_libraries` | N/A | Victoria Gregory, Chase Coleman, Spencer Lyon | 
`julia_plots` | N/A | N/A | 
`jv` | N/A | Spencer Lyon |
`kalman` | N/A | Spencer Lyon, Victoria Gregory | 
`lake_model` | N/A | Victoria Gregory, John Stachurski |
`linear_algebra` | N/A | Spencer Lyon, Victoria Gregory, William Hekman, Guanlong Ren | 
`linear_models` | N/A | Chase, Natasha, José, Spencer, Victoria, Ranjan Ananthamaran, Shunsuke | 
`lln_clt` | N/A | Spencer and Victoria | 
`lqcontrol` | N/A | N/A | 
`lqramsey` | N/A | Spencer | 
`lu_tricks` | N/A | Shunsuke | 
`lucas_model` | N/A | Spencer Lyon, John Stachurski |
`markov_asset` | N/A | Spencer Lyon, Tom Sargent, John Stachurski | 
`markov_perf` | N/A | Shunsuke | 
`matsuyama` | Chase Coleman (co-author) | Shunsuke Hori | 
`mccall_model_with_separation | N/A | N/A | 
`mccall_model` | N/A | N/A | 
`multiplicative_functionals` | Chase Coleman and Balint Szoke (joint) | Shunsuke Hori | 
`need_for_speed` | N/A | N/A | 
`odu` | N/A | Spencer Lyon | 
`opt_tax_recur` | N/A | N/A | 
`optgrowth` | N/A | Spencer Lyon, John Stachurski | 
`orth_proj` | N/A | N/A | 
`perm_income_cons` | Chase Coleman (co-author) | N/A | 
`perm_income` | N/A | Spencer, Victoria |
`rational_expectations` | N/A | Chase Coleman, Spencer Lyon, Thomas Sargent and John Stachurski | 
`robustness` | N/A | Spencer | 
`schelling` | N/A | N/A | 
`short_path` | N/A | N/A | 
`smoothing` | N/A | N/A | 
`stationary_densities` | N/A | Spencer, Victoria | 
`types_methods` | N/A | N/A | 
`uncertainty_traps` | N/A | N/A | 
`wald_friedman` | Chase Coleman (co-author) | Shunsuke Hori, Alberto Polo |

**Comment by jlperla** [comment]
@arnavs  Thanks so much for this.  Based on https://github.com/jstac/QuantEcon.lectures/issues/1195#issuecomment-417498436 I think that can now take the next steps:
1. Standardize the `Coauthored with XXX and YYY` at the top of the page where there are co-authors
2. Remove all other names from the sourcecode/etc.
3. Get these names merged into the global contributors, as in https://github.com/jstac/QuantEcon.lectures/issues/1195#issuecomment-417498436 

@jstac : I don't think we have access to the make PRs on the main attributions page, so perhaps you could have someone on the python page merge these in based on however you want to organize the "Developers" vs. "Other Contributors"?

**Comment by arnavs** [comment]
OK, I did a few passes on the Julia side and the code should be free of names. What's the plan for merging in the names above? Should I add them to the individual `index` pages for the Julia, or are we doing something globally?

**Comment by jlperla** [comment]
@jstac We will take your lead on this, as I am not sure which repo/file this would go in.  I think it may be on the global website?

Alternatively, if there is some repo we could add an issue in with this list of names, then we could close things out here.

**Comment by jstac** [comment]
I'm actually not sure to put global credits, now I think about it.  Soon the `lectures.quantecon.org` portal will be used to link to multiple lecture sites (python, julia, data bootcamp).  Perhaps each of those needs their individual "Preface / About these lectures" page, and credits belong there.

Or, we could put some additional credits down the bottom of https://quantecon.org/team.

That page is easy to edit.

**Comment by arnavs** [comment]
Sounds good @jstac. For now, I've created a `credits` text file in the repo with this list of names, so we don't lose them.

**Comment by jlperla** [comment]
Put back names from exercises

**Comment by arnavs** [comment]
Done at a6b4f71.
