### ISSUE TITLE
Setup Automatic Pushing for LFS

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#522]
Based on slack discussions, @jstac  and others agreed that `quantecon-notebooks-jl` might be a better name when the repo is cloned.

To do the transition for the julia notes, I think we should
- [x] Setup the repository for LFS for all `ipynb` files
- [x] Populate the https://github.com/QuantEcon/quantecon-notebooks-jl repository with the existing julia notebooks in it.  Note: I think we will want to add in a directory structure for those (like in the datascience ones) based on sections, but we will need to wait until the RST can also be reorganized
-  [ ] Point any automatic pushing to https://github.com/QuantEcon/lecture-jl-notebooks to instead use the github LFS commands (@mmcky  I wasn't sure if there was automatic pushing yet, but @arnavs can tell you any changes required if there is)
- [x] Change the URL for the notebook repo in https://github.com/QuantEcon/lecture-source-jl/pull/497 to point at the new one
- [x] Add in the comment in the instructions on the cloning to accept LFS.  Some language is in https://github.com/QuantEcon/lecture-source-jl/issues/514
- [x] Add installation instructions for linux and command-line git users into the https://github.com/QuantEcon/lecture-source-jl/pull/497 PR for the instructions
- [x] After testing this, merge that PR into the main build and regerate the build and notebooks.
- [x] After the pushing has been changed to the new rep, I will archive the old one.

**Comment by arnavs** [comment]
Done. From a user perspective, we're transitioned to LFS! 

I'm going to leave this issue open because I'm not sure what the deal is with automatic pushing. But I'll confirm with Matt.
