### ISSUE TITLE
Ensure build infrastructure is compatible with reorganized rst files

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#524]
We need to adapt the build infrastructure to ensure that #523 doesn't break anything.  The things I can think of are:
- [ ] The download notebook link at the top of every file would need to point at the right location
- [ ] The links to the indices in any breadcrumbs could break
- [ ] The automatic push to the notebook repo would want to maintain the file structure for all `ipynb` files

But I imagine there are more.  @arnavs  This is the part of it you will need to have the most involvement with.

**Comment by arnavs** [comment]
Latest build proves compatibility.
