### ISSUE TITLE
Pin down diffs b/t docker and standard setup

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#527]
We have a [Python script](https://gist.github.com/arnavs/0c56877c5701da86daf82f20ea873204) from @mmcky which diffs the `_build_jupyter` folder (output from the Docker) with a known copy (which we have).

We need someone to carefully step through these, see what the discrepancies are, and list them so they can be fixed in the Docker image. 

To get someone set up: 

- [ ] Make sure they have Python, and the deps (`nbdime` etc.)
- [ ] Give them the reference `_build_jupyter` zip. 
- [ ] Make sure they can parse the diff output.

**Comment by arnavs** [comment]
Then, once this is done, we can diff the output between `1.7.9` and `1.8` on the Sphinx.

**Comment by arnavs** [comment]
@PooyaFa This could be a good one for you to work on, now that you're done with the math notation and the Dockerized JupyterHub. 

Let's talk about it tomorrow if you have time.

**Comment by arnavs** [comment]
Started working on this. A lot of the diffs seem to be coming from `$` in the build server output (correct) vs `\$` in the Docker (incorrect). 

Maybe this has been fixed since we last built the Docker image (i.e., it's in a more recent Jupinx?). Will run again. 

cc @jlperla since I think you had the same issue.

**Comment by jlperla** [comment]
Make sure ability to push to a staging (i.e. preview) as well as the live.
@jlperla would run it as a test!

**Comment by jlperla** [comment]
Don't forget pushing the compiled notebooks to the LFS storage for them.
