### ISSUE TITLE
reorganize directory structure

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-source-jl#543]
Hi all, 

We've just reorganized the Python lecture source directory structure.  See https://github.com/QuantEcon/lecture-source-py/pull/198.

I propose that we do the same on the Julia side.

The motivation is that the names used are confusing, which caused problems for some people.

In particular, in the present structure, PDFs, *.jl files and so on live under `rst_files`.

You can see the new structure on the [Python side](https://github.com/QuantEcon/lecture-source-py) and in the PR above.

Note that the Python reorganization involved a hack. See [this issue](https://github.com/QuantEcon/lecture-source-py/issues/201).   This might cause problems in the future, particularly on Windows.

It would be great if someone could (a) implement the same directory structure on the Julia side, (b) fix the hack mentioned just above if it seems like a good idea (or close the issue), and (c) adjust [Jupinx](https://github.com/QuantEcon/sphinxcontrib-jupyter) and the build system accordingly.

@mmcky Would you mind to supervise/coordinate this effort?

CC @arnavs @jlperla @cc7768 @sglyon @DrDrij @AakashGfude

**Comment by arnavs** [comment]
Sounds good, @jstac. Just to confirm, the shift you implemented is to move the `static/` out of the `rst_files/`, bundle them both under `source/`, and (as a hack), symlink `source/rst_files/static -> source/static`?

We're currently working on our own reorganization of the files in #541, to create subdirectories for each section, like `rst_files/getting_started/julia_environment.jl`. 

I think this is compatible with what you've done on the Python side. Once we've ironed it out, we can definitely work on what you suggest.

**Comment by jlperla** [comment]
@arnavs now is the right time to do this. Take a look at any contradictions to our reorg into directories.

@jstac we did a reorganization into directories for the lectures recently, to match the datascience. The reason behind it was that for cloning the jupyter directory having a flat structure makes things hard for users to find

**Comment by jstac** [comment]
@arnavs Confirmed, and yes, I think it's fully compatible.

@jlperla Understood.  That sounds like a good plan.  I'll try to do something similar on the Python side in the near future.

**Comment by jlperla** [comment]
@arnavs  I just wanted to remind you of this task for when you are iterating on the directory reorganization over the next day or so.

**Comment by arnavs** [comment]
A bit later than we anticipated, but this is done now. The directory structure on the Julia side now matches the https://github.com/QuantEcon/lecture-source-py/pull/198
