### ISSUE TITLE
Warning on Plots colorbar entries

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#553]
On the vse.syzygy.ca with the prebaked 
```
activate_github("QuantEcon/QuantEconLecturePackages", tag = "v0.9.9");
```
and the `kalman.ipynb` 
There are a bunch of warnings:
```
┌ Warning: Overwriting colorbar entry
└ @ Plots /home/jovyan/.julia/packages/Plots/oiirH/src/backends/gr.jl:438
┌ Warning: Overwriting colorbar entry
└ @ Plots /home/jovyan/.julia/packages/Plots/oiirH/src/backends/gr.jl:438
```
etc. throughout.  This may be a GR issue with compatability, so it could just be about updating to the ideal version at some point.

**Comment by arnavs** [comment]
No longer an issue with the `v0.9.10` version of QELP.
