### ISSUE TITLE
Mid-July Tasks

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#579]
- [ ] Verify that issue with `jupyter lab` vs `jupyter notebook` was taken care of. 
- [ ] Think about adding instructions on package compiler + Plots to `advanced setup instructions`, or something like that. 
- [ ] Think through whether using the built-in conda/jupyter is better for users to start out.
- [ ] Update the setup instructions once we pin down the best solution for `activate_github_path` etc.

**Comment by jlperla** [comment]
I am going to spin out a separate issue for the `activate_github_path` from this metaissue for discusison

**Comment by jlperla** [comment]
These are being spun out, so will close
