### ISSUE TITLE
FIX: A few broken links identified from linkchecker

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-jl#586]
[linkcheck-julia-broken-lecture-source-jl.txt](https://github.com/QuantEcon/lecture-source-jl/files/3416914/linkcheck-julia-broken-lecture-source-jl.txt)

**Comment by arnavs** [comment]
@PooyaFa This is a short one to knock off. Text file above has some broken links/things that are not found. If you could see what's up, and prepare a PR with fixed links, that would be great. 

It looks like some external websites (e.g., for `Optim.jl` and `VegaLite.jl` and the QuantEcon website `quant-econ.net/jl`) have been reorganized, so you may have to do a little digging to find the new links. 

If there's anything that takes too much time/you can't figure out, just flag it and move on.

**Comment by PooyaFa** [comment]
Just PR .

**Comment by arnavs** [comment]
Closed in PR above. Thanks @PooyaFa
