### ISSUE TITLE
Updates to the build and deployment process

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#589]
If #588 is correct, then we need to make sure the following happens in the build/deployment process:

- [x] Any `Project.toml` and `Manifest.toml` in the `source/rst` tree gets copied over, along with everything else to wherever the notebook building/executing 
- [x] Need to figure out a way to easily bump versions of these across the board, such as the evoluation of https://github.com/QuantEcon/lecture-source-jl/blob/master/source/_static/includes/alldeps_no_using.jl and https://github.com/QuantEcon/lecture-source-jl/blob/master/source/_static/includes/deps_no_using.jl 

Keep in mind that the tags here are now of the lecture-source-jl itself, which should be modified in those documents.
One suggestion:
- [x] We do this with a bash script where we can run a  script to do a global replace within the repo for anything of the pattern which includes the tags or version numbers.
```
github_project("QuantEcon/quantecon-notebooks-jl", path="XXXXX", tag = "vX.X.X")
```
(basically, regex: starts with `github_project` and ends with `tag = ...")

The script would allow us to modify a version across the board.
Similarly, it would replace all `Project.toml` files that have 
```
version = "X.X.X"
```
Then the workflow for tagging a new release of project/manifests would just be to run the script to modify the files, check it in, tag it with the tag you just modified.  Ugly, but perhaps better than the alternatives.  We would then get rid of the `alldeps_no_using.jl` etc. includes...

**Comment by arnavs** [comment]
The way to do this is to do a global find/replace on all `*.jl` and `*.toml` files for the current version number.

Other than that, I've worked with @AakashGfude over the last few days and the `InstantiateFromURL` + Jupinx infrastructure is now in place.
