### ISSUE TITLE
Make sure that _static is not deployed to the notebooks repo

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#590]

**Comment by arnavs** [comment]
The setup moves `_static` to `_build/website/jupyter/executed`, but all the links and such refer to the AWS. So we don't depend on it, and can just ignore it when populating the notebooks repo.

Will close this out once that pipeline is actually built.

**Comment by arnavs** [comment]
Added `_static` to the `.gitignore` for that repo. Pipeline is then a simple drag and drop.
