### ISSUE TITLE
Test shallow clone for the ngitpuller links

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#594]
For the nbgitpuller url, it appears that https://github.com/jupyterhub/nbgitpuller/pull/67 has been merged.

This should in principle let us add something like `depth=1` to the url for the nbgitpuller link on both the Julia and Datascience material and get the shallow clone.

Remains to be tested, though.

**Comment by arnavs** [comment]
Just tested this and it works. We add `&depth=1` to the end of the URL.

**Comment by jlperla** [comment]
SHould we add this to the launch bar?  @cc7768  @sglyon  lets discuss at some point.

**Comment by arnavs** [comment]
The `nbgitpuller` docs recommend only adding it if we see performance hits, and the full clone is fairly quick (at least on the VSE jupyterhub, where I tested this.)

That said, I don't see the harm in it.

**Comment by jlperla** [comment]
OK, lets hold off then.
