### ISSUE TITLE
Archive old Julia notebook repos

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#599]
Archive the old name, and put readme to it saying now outdated (with link to new ones)

**Comment by jlperla** [comment]
I think they are now archived, and we just need to adjust the text to mention the deprecation and the new location?

**Comment by arnavs** [comment]
Yeah, archived them in #603. I will un-archive each, make those changes, and then re-archive. (Archiving means you can't even edit the README.)
