### ISSUE TITLE
Check if dataframes code needs to be modified 

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#602]
New version of dataframes has different mutable interface. Check if used anywhere, and adapt

**Comment by arnavs** [comment]
@XiaojunGuan basically just go through and search for lectures where we're using `DataFrames.jl`, and there are a bunch of deprecation warnings or something.

**Comment by jlperla** [comment]
It may only be in the "more Julia" section.

The other thing to do is look if we show mutation of columns, since the notation has changed. It is now `df[!, :col]` to reference a column you will modify. 

 See https://juliadata.github.io/DataFrames.jl/stable/man/getting_started/

**Comment by arnavs** [comment]
Done in #608.
