### ISSUE TITLE
Upgrade everything to Julia 1.2

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#604]
We should test, and upgrade as necessary, everything to Julia 1.2

It is possible that a few dependencies will be broken, which would be a reason to delay (or up the packages as required). We should not use new library features quite yet, though

**Comment by jlperla** [comment]
We can pull this if there are issues.

**Comment by arnavs** [comment]
@jlperla I'm moving this to `v1.1` for now because we are dependent on an upstream PR to do it properly. If we have extra time, I will come back to it.

**Comment by arnavs** [comment]
I've had success with the `julia-1.2` kernel, so let's use that in the `conf.py`. @mmcky has installed it on the EC2 machine.
