### ISSUE TITLE
Get rid of minor Julia versions in the breadcrumbs

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#610]
![image](https://user-images.githubusercontent.com/13106721/63475175-afe4ea00-c430-11e9-829c-3b902fa16897.png)
 
See above. Right now it shows "Julia 1.1.0" in the breadcrumbs, which is incorrect and often out of sync.  I think just saying "Julia" would be good enough for now.  We can deal with it again when Julia releases a 2.0 version

**Comment by arnavs** [comment]
cc @DrDrij, what are your thoughts? I think this is grabbing the kernel information from the `conf.py`:

```
jupyter_kernels = {
    "julia": {
        "kernelspec": {
            "display_name": "Julia 1.1.0",
            "language": "julia",
            "name": "julia-1.1"
            },
        "file_extension": ".jl"
    }
}
```

Do we just change the display name?

**Comment by Nosferican** [comment]
If it is just grabbing the kernel information, it should keep updated. I think it is useful to know which version was used to run the code.

**Comment by jlperla** [comment]
It gives the (incorrect) impression that the code only runs on a particular minor version of Julia, which is incorrect. If you want that sort of information, you could see it in the coverage.

**Comment by Nosferican** [comment]
I would disagree that it gives that impression as most blogs and kernels will have the version it runs. I don't assume it wouldn't run with anything later (e.g., Julia `v1.2.0` which is the current latest release, and the version people default to when installing Julia the first time). No strong feeling on whether it would work with the long term support release (Julia `v"1.0.4")`. We could add a note if there is anything that requires a new feature (e.g., `1.3.0` for threads).

**Comment by arnavs** [comment]
Worth noting that the kernel information isn't necessarily even up-to-date; i.e., `conf.py` could be out of sync with what comes out of `jupyter kernelspec list.` You'd need to grab info from `nbconvert` to see what the display name is for the kernel that's actually used. 

I've submitted a commit and I'll check if this is fixed in the next hourly build.

We can change it back later if that's what @Nosferican and @jlperla decide.

**Comment by jlperla** [comment]
Great.  BTW, note that the "Python" lectures just say "Python" in the breadcrumb, without even saying Python 3, so this is much more consistent with the general site.

**Comment by arnavs** [comment]
You can see that this has been fixed in the `preview-lectures.quantecon.org/jl` lectures.
