### ISSUE TITLE
Update the "How to read this lecture..." on the html

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#615]

**Comment by jlperla** [comment]
Add a comment that says to run `] instantiate` as required

**Comment by arnavs** [comment]
@jlperla I'm able to make this change, if you'd like to add it to `v1.0.2` release.

**Comment by jlperla** [comment]
Let's wait until 1.1 when we have the full launching updated

**Comment by arnavs** [comment]
This is done in the lectures (we have a note saying `] add InstantiateFromURL` as required, and the rest comes from that package.)
