### ISSUE TITLE
Test new conda-based setup instructions on key OSs

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#616]
After #612 is merged, follow the instructions carefully with Julia 1.2

- [ ] Windows
- [ ] OSX
- [ ] Ubuntu
- [ ] Ubuntu on WSL

Also, test the instructions from the perspective of someone who installed Jupyter separately in conda. (i.e. delete the `.julia` install Conda locally, and then make sure the "Alternatively" work.)

**Comment by arnavs** [comment]
@jlperla I find that quitting the `julia` terminal isn't enough to stop the notebook server started with `using Ijulia; jupyterlab(detached = true)`. I guess because it's detached. 

How have you been doing this?

**Comment by jlperla** [comment]
What os? It always seemed to shutdown on windows, after closing the terminal, but if it doesn't with Linux/osx then that is an issue.

Maybe take the `detached` out of all of the instructions (globally do a search in the PR)?

Also, change the text to reflect that the he jupyter notebook server now takes the whole repl, etc. There is a chance you will need to rethink a few steps in the he instructions where I assumed that the REPL would be available

**Comment by arnavs** [comment]
Closing this since we incorporated feedback from @XiaojunGuan and @wupeifan. Thanks to both of you for your detailed comments.
