### ISSUE TITLE
Linear Algebra Types

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#62]
I'm finding some issue with specialized types in the `LinearAlgebra` module. See below for a MWE. The issue is that, because these don't subtype `Matrix` as some external libraries (like `PyPlot`) expect, methods defined on matrices don't seem to work. 

Let me know how we should proceed. 

```
julia> x = [0 1; 1 0]
2×2 Array{Int64,2}:
 0  1
 1  0

julia> transpose(x)
2×2 Transpose{Int64,Array{Int64,2}}:
 0  1
 1  0

julia> transpose(x) isa Matrix
false

julia> typeof(x')
Adjoint{Int64,Array{Int64,2}}

julia> x' isa Matrix
false

julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by arnavs** [comment]
I suspect these libraries will needed to be rewritten to switch on `AbstractMatrix`, which may be the solution here.

**Comment by jlperla** [comment]
@Nosferican I am going to close this because I think we know the answer:  Duck type everything and this isn't a problem.  We can just make the struct's without any type annotations to begin with, and this won't be an issue when we move to named tuples for all parametesr.

**Comment by arnavs** [comment]
Makes sense. I'll leave an issue with PyPlot for what it's worth.
