### ISSUE TITLE
Determine appropriate dataframes version and do deprecation check with the full toml

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#621]
Due to the change in the dataframes notation, plenty of downstream packages have nasty deprecation warnings.  We need to see if it is possible to use the newer version of DataFrames without breaking dependencies (e.g. GLM, FixedEffect, etc.)

If everything works except for a particular deprecation warning on a particular package, then we can live with it while the package fixes things up.

**Comment by arnavs** [comment]
There are a few (4) deprecation warnings in `GLM.jl`. And one in `StatsModels.jl`

Since the line numbers are all there, may just be easier to patch those packages to use the new notation. Will send them PRs.
