### ISSUE TITLE
Minimize Subdirectory TOMLs

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#624]
I am not sure if getting_started_julia/Project.toml is needed, but I know that it is excessive.

Consider getting rid of it and running coverage to check if things work?  Consider adding packages to the main Project if it is something small and innocuous or lets discuss if it is not.

**Comment by arnavs** [comment]
@jlperla For the initial setup, I just added a copy of QELAP to every subdirectory with a lecture that depended on it.

You're right that this doesn't make sense here. This can be removed.
