### ISSUE TITLE
Check coloring of installation output 

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#626]
See https://github.com/QuantEcon/InstantiateFromURL.jl/issues/40

We need to run the code on a desktop installation to see how it looks without having output stripped

**Comment by arnavs** [comment]
See these two use cases. @jlperla You can close if this looks good.

<img width="1192" alt="Screen Shot 2019-08-23 at 3 08 40 PM" src="https://user-images.githubusercontent.com/5009477/63626435-ec8f1d80-c5b7-11e9-88f0-67d1d66e0b74.png">
<img width="731" alt="Screen Shot 2019-08-23 at 3 08 49 PM" src="https://user-images.githubusercontent.com/5009477/63626436-ec8f1d80-c5b7-11e9-9f6f-0dd7227b9de1.png">

**Comment by jlperla** [comment]
Looks good to me
