### ISSUE TITLE
Wait on RegressionTables and Re-Add to Lectures

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#634]
This is currently commented out, and removed from Project/Manifest. Before 1.1, we should take another look.

**Comment by jlperla** [comment]
For https://github.com/jmboehm/RegressionTables.jl/issues/26

Is there any way we could make the PR ourselves?

**Comment by arnavs** [comment]
Moving this to 1.1 since we decided to wait on Johannes.

**Comment by jlperla** [comment]
With this fixed, lets test and see if we can get this and the dataframes stuff bumped up, and turn in back on in the lecture notes. I would love to teach with FixedEffectsModels and this in a few weeks.

**Comment by arnavs** [comment]
Sounds good. Will do as soon as Johannes tags a release. Which should be soon, since I think the FixedEffects upgrade is fairly minor.

**Comment by arnavs** [comment]
@jlperla I'm closing this because #681 looked good.
