### ISSUE TITLE
Change julia jupyterhub dropdowns, and the default choice

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#647]
Right now they are listed as:
- `VSE`
- `PIMS`
- `binder`
- `colab`

First, we should remove `colab` from this list since it doesn't yet support julia.  After that, I think things look better with the full URL, so maybe change this to (in this order!)
- `mybinder.org (Public)`
- `quantecon.syzygy.ca (Public)`
- `vse.syzygy.ca (UBC only)`

I think that it could also be that `colab` is the current default?  If so, then change it to `quantecon.syzygy.ca` for now

Where if we decide that `quantecon.syzygy.ca` dominates Binder, we can temporarily remove it.

**Comment by arnavs** [comment]
Done.
