### ISSUE TITLE
Remove Compat from the entire lecture set (and the Package/Manifest)

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#650]
This should not be required after 1.1

**Comment by jlperla** [comment]
Make sure to carefully check the coverage afterwards, though, because Compat could have caused other side effects.

**Comment by jlperla** [comment]
I have rethought this and think we should push things forward if possible, otherwise it invalidates every single notebook when we fix it.

Can we give finding `Compat` and globally getting rid of it in the notebooks? I suspect this will have no side effects.

**Comment by arnavs** [comment]
I opened #659 and started a coverage build for it. It is around 12:30 AM here so sleeping soon, but I will check this in 7 hours or so when I wake up.
