### ISSUE TITLE
Launch Button Default to Binder

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#654]
cc @DrDrij @jlperla @mmcky 

We changed the order of the options in the launch bar (which took.) The issue is that the actual bar still defaults to `CoLab` (which doesn't exist anymore, as an option.)

Any advice? @DrDrij could you take a quick look through our `julia.tpl` and see if there's an easy fix?

<img width="926" alt="Screen Shot 2019-09-02 at 12 05 51 AM" src="https://user-images.githubusercontent.com/5009477/64082824-950a5380-cd15-11e9-9859-41ea6a8bc6d8.png">

**Comment by jlperla** [comment]
To make sure I understand: is it that `colab` in https://github.com/QuantEcon/lecture-source-jl/blob/master/theme/templates/julia.tpl#L167 should be replaces by the string from https://github.com/QuantEcon/lecture-source-jl/blob/master/theme/templates/julia.tpl#L205

**Comment by jlperla** [comment]
@DrDrij  If you can increase the delay on the popup of the launch button by a bit more when you look at this, I think it may be slightly better, but I defer to you on usability.

**Comment by DrDrij** [comment]
@jlperla You correctly identified the lines to amend. I've also increased popup opening delay from 200ms to 500ms. The PR is ready here:
https://github.com/QuantEcon/lecture-source-jl/pull/658

**Comment by arnavs** [comment]
Fixed in the latest clean build.
