### ISSUE TITLE
Regtable not fully commented out

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#655]
Right now the `data_statistical_packages` is failing due to the `regtable` function in the `FixedEffects`.  I am not entirely sure if having that `FixedEffects` code is worth it until the regtable is fixed?  What would the output of the call look like without displaying it?

I think you can just comment out the whole `FixedEffects` section and then we can turn it back on when regtable merges.

**Comment by arnavs** [comment]
Thanks @jlperla for catching this. I removed mention of the package in the above commit.
