### ISSUE TITLE
Execution for Downloads Notebooks

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#660]
Go to a file with static images, just as you can he first lecture. It looked to me like it was looking for a local file instead (in `_static`of pointing at the internet°I noticed this in binder, but could it be everywhere? @arnavs @mmcky

**Comment by arnavs** [comment]
@jlperla Are you checking the `quantecon-notebooks-julia`?

That one has not been updated in a while, and was populated with filler notebooks. We will be adding the (executed) notebooks from the `_downloads` section which has the global URLs for images.

**Comment by mmcky** [comment]
@arnavs also working on adding execution for you on the `_downloads` notebook.

**Comment by arnavs** [comment]
Sounds good @mmcky. Updated the title, since we still need that to work before we can release.

**Comment by arnavs** [comment]
@mmcky has indicated that either this will get handled tomorrow (Australian) in a Jupinx patch, or we will manually execute on Wednesday and then patch Jupinx on Friday.

**Comment by jlperla** [comment]
Yes, that is what I was testing with, since it is the user facing thing.  Whatever it takes to get them fixed up for teaching is appreciated.

**Comment by arnavs** [comment]
Closing this because of @mmcky's PR https://github.com/QuantEcon/quantecon-notebooks-julia/pull/2. 

There is https://github.com/QuantEcon/sphinxcontrib-jupyter/issues/267 which deals with executing the download notebooks, since those notebooks solve our URL issues.
