### ISSUE TITLE
Fix False Positives in Test Coverage

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#661]
Don't want to give people the impression that something is wrong with a given lecture, when there isn't.

**Comment by jlperla** [comment]
Making sure there are no false positives is useful (note that false negatives would mean we fail to see an issue, not that we flag an issue that doesn't exist), but lower priority than making sure the notebooks themselves are the "real" ones.

**Comment by arnavs** [comment]
Done, will close when I see the changes reflected in the next nightly build.
