### ISSUE TITLE
Only use the df[!, :col] for mutation

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#665]
Right now the code in http://preview-lectures.quantecon.org.s3-website-ap-southeast-2.amazonaws.com/jl/more_julia/data_statistical_packages.html#Constructing-a-DataFrame shows `df[!, :col]` but I don't think you need to do that unless you are mutating it?

**Comment by jlperla** [comment]
Handing #687 over to you for checking.  Merge after you make sure I didn't make any mistakes.

**Comment by arnavs** [comment]
Closing since we merged #687
