### ISSUE TITLE
Alternatives to Printf?

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#666]
See http://preview-lectures.quantecon.org.s3-website-ap-southeast-2.amazonaws.com/jl/multi_agent_models/rational_expectations.html

Not sure if this is really necessary for the lecture and alternatives would work?

**Comment by mmcky** [comment]
@jlperla it is probably best to reference the source rather than the preview site as it is liable to change (as the `master` branch changes). 

https://github.com/QuantEcon/lecture-source-jl/blob/master/source/rst/multi_agent_models/rational_expectations.rst
