### ISSUE TITLE
Fix QuantEcon DSP deprecation

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#667]
Note http://preview-lectures.quantecon.org.s3-website-ap-southeast-2.amazonaws.com/jl/time_series_models/estspec.html for example.

**Comment by arnavs** [comment]
@jlperla This deprecation is coming from `QuantEcon.jl` (see https://github.com/QuantEcon/QuantEcon.jl/issues/248) and is a known issue in that package. I don't think it came from a recent release.

**Comment by arnavs** [comment]
Also, this is the only deprecation warning (it shows up in 4 lectures.) I'll push forward on tagging a new release of QuantEcon (looks like there is template code for this that Spencer wanted to merge, but the PR author closed it.)

**Comment by jlperla** [comment]
Don't close this issue (unless it is a duplicate in this repo) until fixed

**Comment by arnavs** [comment]
We tagged a new version of `QuantEcon` with the error gone, and ran `] up QuantEcon` in the TOML. 

The few sub-dependency upgrades looked innocuous, but just to be paranoid I am running coverage again.
