### ISSUE TITLE
Remove zreferences.html at the root level of lectures.quantecon.org

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-jl#669]
Once the links are fixed in `conf.py` we can delete the `zreferences.html` file located at the root level of lectures.quantecon.org

**Comment by arnavs** [comment]
@mmcky Can we do this now?

**Comment by arnavs** [comment]
Assuming this is obsolete now that we've moved to `julia.quantecon.org` and `python.quantecon.org`. But we can re-open if not.
