### ISSUE TITLE
Get Escape $ Fix Working in Monospace Format

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#671]
See 
![image](https://user-images.githubusercontent.com/13106721/64256060-810e4f80-ced7-11e9-9227-40a878273e12.png)

This is in https://github.com/QuantEcon/lecture-source-jl/blob/master/source/rst/getting_started_julia/julia_by_example.rst

There were changes in the Jupinx escaping that might cause this.  We should try to find other places where a $ is used as display in a text block

**Comment by arnavs** [comment]
Looks like Jupinx fix doesn't work inside code formatting in text blocks. Short term fix is to go out of code formatting and escape normally. 

Moving this to 1.1 and raising an issue in Jupinx.

**Comment by jlperla** [comment]
Not worth it prior to jupyterbook conversion.
