### ISSUE TITLE
Julia Status Page should have Jesse's name

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-jl#674]
http://preview-lectures.quantecon.org.s3-website-ap-southeast-2.amazonaws.com/jl/status.html

this needs to be updated in the `status.html` file in `theme`

**Comment by jlperla** [comment]
If this is non-trivial for the themes, it can wait.  I will move the milestone since it is low priority.

If there is any way for you to conditionally show my name, only when coverage is at 100%, it would be appreciated :-)

**Comment by arnavs** [comment]
This is a one-liner, so I went ahead and fixed it. See above commit.
