### ISSUE TITLE
Create a packagecompile.jl file for internal use

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#677]
Create a file`utilities/packagecompile.jl` in the notebook repo

- [x] Put in a note on usage on the README.jl (e.g. run again after a project.toml update)
- [x] Add running it to the WSL instructions for editing
- [x] See if builds work with it running on the image

**Comment by arnavs** [comment]
The reason this _might_ not be faster is that we have to spin up a new `IJulia` instance for each notebook. So we're paying the startup cost associated with PackageCompiler once per lecture, as far as I understand it. @mmcky, can you confirm?
