### ISSUE TITLE
Math display typo in /more_julia/optimization_solver_packages.rst

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#684]
See 
![image](https://user-images.githubusercontent.com/13106721/64813141-8746a080-d555-11e9-963b-902d884de4e1.png)

**Comment by arnavs** [comment]
@jlperla Was able to fix in this case by truncating the text mode. But I think this is a fundamental flaw in RST--- you can't have a math block, then have a `\text{}`, then do math inside of that text.
