### ISSUE TITLE
Scan and fix all deprecations if possible

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#686]
i.e. other than downstream packages which are not our fault.

**Comment by arnavs** [comment]
@jlperla We have four of them (total) spread out amongst a few packages in data and statistics. Nothing serious in terms of presentation, but they're all to do with downstream packages. 

The warning is: 

```
┌ Warning: `T` is deprecated, use `nonmissingtype` instead.
│   caller = (::getfield(StatsModels, Symbol("##40#41")){Array{Int64,1}})(::Array{Float64,1}) at none:0
└ @ StatsModels ./none:0
```

etc.
