### ISSUE TITLE
Fix Jupinx

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#7]
Currently, we have a few issues with the Jupinx build on the source reStructured Text: 

- [ ] A few files are referring to nonexistent code blocks. 
- [ ] There is some (stochastic) issue with the use of the `*` symbol inside code. I couldn't replicate it, but @Nosferican and @jlperla could.
- [ ] `\Span` `\col` `\RR` and other improperly parsed issues (see orth_proj.ipynb).

And likely a few others. We can close this when we're satisfied with the output Jupyter.

**Comment by mmcky** [comment]
thanks @arnavs - the last issue is we haven't added those ``\RR`` to mathjax config. Will need to take a closer look at the other items.

**Comment by arnavs** [comment]
@mmcky Closing this; will add stuff to Jupinx if it comes up.
