### ISSUE TITLE
Figures :width: attribute need to use %

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-jl#708]
@arnavs I think the figures using `:width:` need a %

http://docutils.sourceforge.net/docs/ref/rst/directives.html#image

The `:scale:` indicates it is optional but the `:width:` take integer or percentage

```
.. figure:: /_static/figures/judd_fig2.png
    :width: 70
```

should be

```
.. figure:: /_static/figures/judd_fig2.png
    :width: 70 %
```

**Comment by arnavs** [comment]
Thanks @mmcky, will go through and fix these tomorrow.

**Comment by arnavs** [comment]
@mmcky Can you point to where you see the bad syntax? Just did a quick global search through the lectures and it looks like we are using the `%`.
