### ISSUE TITLE
Issue with unicode and the linear algebra WIP

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#710]
```
Encoding error:
'charmap' codec can't encode character '\u22c5' in position 76069: character maps to <undefined>
The full traceback has been saved in C:\Users\jlperla\AppData\Local\Temp\sphinx-err-qr9zfs7e.log, if you want to report the issue to the developers.
```

**Comment by arnavs** [comment]
@jlperla Looks like this is a Windows console error and not a function of the PR. See: https://stackoverflow.com/a/28041598. 

I will try it on my Windows machine and get back to you.

**Comment by jlperla** [comment]
OH great, then all good.

**Comment by arnavs** [comment]
Closing this as it won't affect what's on the site or notebooks, and isn't fatal for the build process.
