### ISSUE TITLE
Update Troubleshooting Page

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#731]
e.g. https://julia.quantecon.org/troubleshooting.html

These are Python-specific for now, but should be changed for Julia.

**Comment by jlperla** [comment]
@arnavs  Can you do a minimalist version for now?

Maybe just start by removing the python content, having the "local setup" guide point towards the installation steps, and maybe a suggestion to delete the `.julia` and follow the package setup again.

Also, add in a jupyterhub help telling people how to reset the environment to the latest sets of notes.  i.e. remove a single notebook and then click on launch again  and how to reset everything (i.e. delete the entire set of notebooks by launching a terminal and going `rm -rf quantecon-julia-notebooks` or whatever in the root).

**Comment by mmcky** [comment]
thanks @arnavs just about to open an issue.
