### ISSUE TITLE
Default Julia startup arguments for Juno and the REPL

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#76]
The new arguments for Julia v1.0 include the ability to activate a project when julia starts up.

It isn't documented especially well yet, but I think the options are:
- `--project=.` to select the current project file
- `--project=@.` to recursively go up the tree until it finds a project file (or default otherwise)?

These can be set in Juno (by going to the `Julia Client` settings and setting the `Additional Julia Startup Arguments`.

The question is: what should the settings be in our setup guides - and is it something we should submit a PR for to the Juno to change the default.

We should ask on slack to see how it is supposed to work test both versions with the following permutations:
- [ ] Open up the Juno repl after starting Juno in a particular directory with a project file
- [ ] Same, but with a project that doesn't have a project file yet.  This shouldn't error, and should default to the standard `v1.0` project
- [ ] Same but in a sub-directory of something with a project file.  It would be nice if it picked up the parent directory project file, but not essential.  Again, shouldn't error

We should also make sure that this workflow is the one we want.  Finally, what other features for working with Pkg3 would make sense.  An `instantiate` button/command?  A `test` one?  Asking to create a new project when starting the REPL in a folder without a project file, etc.

**Comment by jlperla** [comment]
sorry @jstac , wrong assignment... unless you want to learn the new package manager :-)

**Comment by arnavs** [comment]
Sounds good, @jlperla. Will do. Also worth noting that recommended startup for Atom (at least on macOS, and I suspect on Linux) is to run `atom .` in the folder you want to load. So that could give us a natural default of "check if there's a `Project.toml`, and load it if there is."

**Comment by jlperla** [comment]
Yeah but in practice after you use Atom, you right click on the menubar to start the project.  Not sure on OSX though.

I am not sure if the default of `--project=.` works... the problem is that if it starts in a folder without a Project file, it doesn't seem to default to the basic `v1.0` one.  We can ask what the `@.` is supposed to do.

**Comment by jlperla** [comment]
Discussed with the core-devs.  The advice needs to be **not** to change those settings in Juno... if people want to do it themselves, then they probably know enough about environment variables for it to be caveat emptor.

The issue is that it can be a security hole, and hence we want to force users to make an active decision to activate a project.
