### ISSUE TITLE
Run regression test on Julia 1.3

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#784]
We should wait before updating kernels/etc., but it would be nice to know if tehre are regressions.

**Comment by arnavs** [comment]
Results attached. Looks pretty good... maybe a lecture or two with an error? We can sort it out.

[code-execution-results.json.txt](https://github.com/QuantEcon/lecture-source-jl/files/3906407/code-execution-results.json.txt)
