### ISSUE TITLE
Numerical Linear Algebra

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#792]
@jlperla I had a look at the linear algebra stuff. Two things:

1. The text is definitely English, but very information-dense... I think it would benefit from a copy-editing pass. Could probably hire Katherine (our editor from datascience) to do it for a small sum, or I can get to it when I have some downtime. 

2. We only use the `OrdinaryDiffEq` stuff in one cell (the last one in sparsity.) I'm partial to making that one optional (`no-execute`), as otherwise we'd have to add it to the global manifest. 

No rush, so I'm adding this to a faraway milestone.

**Comment by jlperla** [comment]
OK, perfect.  I will think about the right timing of the copy editing.  My main quetsion was whether it is close to being ready to hand off to a copy editor, or if the text is not ready even for that.

My hope is that we can move towards more continuous time solutions over the next few years, so I don't have an issue with adding ther OrdinaryDiffEq (note, *not* the whole DiffEq).

Can you try this:  Look at the `Manifest.toml` with everything up to that cell working.  Then add in the `OrdinaryDiffEq` and `DiffEqOperators` or whatever is required for that cell.  See what else was added to the Manifest.

It could be that we already have most of the dependencies for OrdinaryDiffEq and DiffEqOperators in the Manifest through other packages.  If so, then it might not be a big change....

**Comment by arnavs** [comment]
I guess it's not terrible actually. And some of these packages are worthwhile in their own right, perhaps for later lectures (i.e., `ModelingToolkit`).

Well, we can decide later. 

```
 Resolving package versions...
 Installed CanonicalTraits ────── v0.2.1
 Installed DiffEqBase ─────────── v6.8.0
 Installed DiffEqOperators ────── v4.2.2
 Installed OrdinaryDiffEq ─────── v5.26.8
 Installed GeneralizedGenerated ─ v0.1.3
 Installed RecursiveArrayTools ── v1.2.1
 Installed ModelingToolkit ────── v0.8.0
  Updating `~/quantecon/lecture-source-jl/source/rst/Project.toml`
  [9fdde737] + DiffEqOperators v4.2.2
  [1dea7af3] + OrdinaryDiffEq v5.26.8
  Updating `~/quantecon/lecture-source-jl/source/rst/Manifest.toml`
  [a603d957] + CanonicalTraits v0.2.1
  [2b5f629d] + DiffEqBase v6.8.0
  [9fdde737] + DiffEqOperators v4.2.2
  [ffbed154] + DocStringExtensions v0.8.1
  [069b7b12] + FunctionWrappers v1.0.0
  [6b9d7cbe] + GeneralizedGenerated v0.1.3
  [b14d175d] + JuliaVariables v0.2.0
  [d8e11817] + MLStyle v0.3.1
  [961ee093] + ModelingToolkit v0.8.0
  [46d2c3a1] + MuladdMacro v0.2.1
  [71a1bf82] + NameResolution v0.1.3
  [1dea7af3] + OrdinaryDiffEq v5.26.8
  [8162dcfd] + PrettyPrint v0.1.0
  [731186ca] + RecursiveArrayTools v1.2.1
  [f2c3362d] + RecursiveFactorization v0.1.0
  [a2a6695c] + TreeViews v0.3.0
```

**Comment by jlperla** [comment]
Lets do it then.  It would be great to have a clean manifest where we can start to do continuous-time stuff off of.  We can prepare a Julia v1.3 release which has a manifest that "can work" with these new lectures, which makes it much easier to push them up later.

**Comment by jlperla** [comment]
See #830
