### ISSUE TITLE
Fix Julia PDF export issues.

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#799]
It seems like the Julia PDF output is broken.  If you click on https://julia.quantecon.org/  and choose the PDF you will see it stops at the end of the "SOLVERS, OPTIMIZERS, AND AUTOMATIC DIFFERENTIATION" lecture.

Can you try to see what may have gone wrong here?  My guess is that there is a bug in generating a PDF output from a lecture that it can't merge.... which one?  Maybe which ever one comes next in the list ("https://julia.quantecon.org/more_julia/tools_editors.html ?)

@arnavs   can you work with @mmcky @AakashGfude  to resolve?  Thanks!

**Comment by mmcky** [comment]
@jlperla is this recent or was this the issue raised when the `pdf` broke previously?

**Comment by jlperla** [comment]
I think it is old. Looked good when I took a look today
