### ISSUE TITLE
One typo in the need for speed

### ISSUE THREAD

**Issue by JackRab** [QuantEcon/lecture-source-jl#804]
In the subsection *Composite Types with Abstract Field Types* under the section **Fast and Slow Julia Code** of [The need for speed](https://julia.quantecon.org/more_julia/need_for_speed.htm), there is one sentence saying
>As we’ll see, the last of **options these** gives us the best performance, while still maintaining significant flexibility.

should it be

>As we’ll see, the last of **these options** gives us the best performance, while still maintaining significant flexibility.

**Comment by jlperla** [comment]
Thank you so much!  That whole lecture needs some revisiting in the next version or two.

**Comment by arnavs** [comment]
Thanks @JackRab, just fixed this. 

Hope you enjoyed the lecture.

**Comment by JackRab** [comment]
Thank a lot for your work.
