### ISSUE TITLE
Colab integration

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#806]
Some links:
- https://github.com/Dsantra92/Julia-on-Colab
- https://gist.github.com/yiyuezhuo/91ac12cf8caa28b2776f19a9fa58d031
- https://www.youtube.com/watch?v=xpZo3L2dYTY

- In principle, should only need to do something
```
!curl -sSL "https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.4.1-linux-x86_64.tar.gz" -o julia.tar.gz
!tar -xzf julia.tar.gz -C /usr --strip-components 1
!rm -rf julia.tar.gz*
!julia -e 'using Pkg; pkg" up; add IJulia ;  precompile"'

# refresh window to activate julia kernel
```
or 
```
# Installation cell
%%shell
if ! command -v julia 3>&1 > /dev/null
then
    wget 'https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.4.1-linux-x86_64.tar.gz' \
        -O /tmp/julia.tar.gz
    tar -x -f /tmp/julia.tar.gz -C /usr/local --strip-components 1
    rm /tmp/julia.tar.gz
fi
julia -e 'using Pkg; pkg"add IJulia InstantiateFromURL; precompile;"'
echo 'Done'
```
And then "refresh" the window.  But getting the notebook to match the kernelspec might be needed.

Note that the URL also works, so maybe we could get people to copy/paste some text like that in... or even have a "colab-notebooks" repo.
 `https://colab.research.google.com/github/QuantEcon/quantecon-notebooks-julia/blob/master/getting_started_julia/julia_essentials.ipynb`

**Comment by jlperla** [comment]
Strategy would be a post-processing script to add an installation instructions/cell and potentially change the jupyter kernel stuff.

Might also make sense to remove the `InstantiateFromURL` and tell people to manually install...

**Comment by arnavs** [comment]
Seems to work, but getting the notebook's kernelspec to match before you upload is essential. Also switched to 1.4.1, which came out recently. 

I'm able to install `CuArrays` and reproduce his results. 

The first time you actually use the GPU it will download a bunch of binary crap. 

I used the `%%shell`-style script. 

The GPU they give us is: 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P0    26W /  75W |    161MiB /  7611MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

**Comment by jlperla** [comment]
OK, @arnavs  sounds like we basically have 2 choices here.  In both cases, we wuold generate a set of notebooks with a patch on the existing ones to add in the colab installation... and we can make sure to setup the jupyter kernelspec to precisely match.

Also, in both cases we take the generated notebooks and find the generated output matching the
```
using InstantiateFromURL
github_project("QuantEcon/quantecon-notebooks-julia", version = "0.5.0")
# uncomment to force package installation
# github_project("QuantEcon/quantecon-notebooks-julia", version="0.5.0", instantiate=true)
```
cell a replace it with two cells.  In the first cell is always something with julia installation and colab instructions.  That is, something like 
```bash
%%shell
if ! command -v julia 3>&1 > /dev/null
then
    wget 'https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.4.1-linux-x86_64.tar.gz' \
        -O /tmp/julia.tar.gz
    tar -x -f /tmp/julia.tar.gz -C /usr/local --strip-components 1
    rm /tmp/julia.tar.gz
fi
julia -e 'using Pkg; pkg"add IJulia InstantiateFromURL; precompile;"'
echo 'Done'
```

## Choice 1:   We add in an instantiatefromurl option to download and instantiate withtout precompiling.  So the cell becomes something like
```
using InstantiateFromURL
github_project("QuantEcon/quantecon-notebooks-julia", version = "0.5.0", instantiate = true, precompile = false)
```
The advantage of this is that we know the combination of package versions will work, and the user doesn't need to see any errors as they add packages.  The disadvantage is that it may take an extra 2-3 minutes to load, and if people want to update notebooks they would have to manually delete the project/manifest.  The first is an issue, the second I am less worried about.

## Choice 2: We turn that into something like the following
```
] add Plots Distributions Expectations   # add more packages as required
```
Where we can tell the user to add in packages when they get errors.

The benefit of this is that it will be faster to load the first time, and will get the latest copies of packages.  The downside is that the latest copies of packages might be incompatible or buggy, and it requires a lot of stop and start as users find missing packages.  That round-trip time could be > 2-3 minutes...

**Comment by jlperla** [comment]
@arnavs  I created https://github.com/QuantEcon/quantecon-notebooks-julia-colab for the notebook repo we would push to... regardless of the approach.

**Comment by arnavs** [comment]
Closing this as we have more specific issues and we decided on the `precompile = false` setup with InstantiateFromURL as the approach.
