### ISSUE TITLE
Iterate on release steps for the full deployment process after colab/etc. is done

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#821]
Thinks like how to initiate a preview/etc.   Will walk through this carefully with @ajozefiak  and me so that the two of us could do it as required.

Several variations:
1. A patch to the website, not worth pushing out notebooks
2. A change to the website and both notebook repositories, but not worth bumping package versions
3. A full package bump with the full notebook deployments

See my changes to RELEASE.md with placeholders for this

**Comment by arnavs** [comment]
In the short run, @mmcky could you give @ajozefiak access to the QuantEcon.AWS.Admin repo? It looks like he will be working with Jesse on this stuff after I leave UBC in a few weeks.

**Comment by jlperla** [comment]
@arnavs @mmcky  Lets coordinate this a little later and figure out exactly what we need to do (so I can do things as well)!

**Comment by mmcky** [comment]
I also need to update the `QuantEcon.userguide` which documents our setup etc.
