### ISSUE TITLE
Python script for notebook colab updates

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#824]
We want to have a script to generate colab notebook modficiations as part of the build process.  It would operate on the full notebook downloads as a post-processing step.

Seems like loading each notebook with https://nbformat.readthedocs.io/en/latest/api.html and then adding in the cells at the beignning is the key?

If so, we can add in new literals in https://github.com/QuantEcon/lecture-source-jl/tree/master/source/_static/includes  where we have that sort of stuff for the colab instructions and the julia instllation step.

**Comment by jlperla** [comment]
@mmcky  I will add you here for any discussions after we figure out the cells we want.  Do you want this to run on your build server or something that we do as part of a manual step in the deployment process?

**Comment by mmcky** [comment]
@jlperla for sure. I have reduced notifications from github now to just mentions -- so thanks for tagging me. Please continue to do so if you need my attention on something.

**Comment by mmcky** [comment]
Writing a post-build script is the way forward to get this implemented (in a timely fashion) I think.

**Comment by jlperla** [comment]
@arnavs  I noticed that https://github.com/QuantEcon/lecture-source-jl/blob/dca432e33dade36da31546c8fce8f8b4bedc3aca/util/execute_nb.py  has a structure that might be copyable?

**Comment by arnavs** [comment]
@mmcky I think I'm ready to pick your brain about the pre-processing step to inject cells into the notebook. Let me know when you're around.

**Comment by arnavs** [comment]
This is done and tested.
