### ISSUE TITLE
Add precompile = true to setup instructions where appropriate

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#825]
https://github.com/QuantEcon/lecture-source-jl/edit/master/source/rst/getting_started_julia/getting_started.rst  for  sure

**Comment by jlperla** [comment]
Required if changing to `precompile = false` default.

**Comment by arnavs** [comment]
This was done. Fixed in the two places in that lecture and added the option to the commented-out section of the include script, along with a comment of what it does.
