### ISSUE TITLE
Fix packages for pdf build

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#841]
This is a placeholder issue for fixing the pdf .  It sounds like there may be issues with the packages/etc. used by the pdf build?  @mmcky  @arnavs 

If there is a manual step we need to do to upgrade Julia and/or packages on the build server, this might not be the worst time to document it.

**Comment by mmcky** [comment]
I have removed `jupyterpdf` to initiate a clean build on the build instance for the `pdf` -- hopefully this was a cache issue given `html` outputs seems ok.

**Comment by mmcky** [comment]
@arnavs @jlperla here is the latest `clean` run of `pdf` for `julia`

http://preview.julia.quantecon.org.s3-website-ap-southeast-2.amazonaws.com/_downloads/pdf/quantitative_economics_with_julia.pdf

Would you mind to review?

**Comment by jlperla** [comment]
@mmcky The immediate issue that we were trying to solve seemed to be fixed.  The error no longer appears, so I will close this issue.

However, note #849 suggests something else happened with the backend when it comes to the plotting packages.
