### ISSUE TITLE
Plots not showing in the pdf build

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#849]
@mmcky  Found another PDF issue in what you showed me.  None of the plots seem to be showing inline?

**Comment by mmcky** [comment]
Is the `Plots` package loading? Is there a reference to an example. With `inline` do you mean in the text and loaded from files (or generated plots after code blocks)?

**Comment by jlperla** [comment]
Sorry, what I mean is that it isn't showing them in the PDF as embedded images (as it normally would).  I noticed this with both vegalite.jl and plots.jl, so it might not be specific to a single package.

**Comment by mmcky** [comment]
@AakashGfude there doesn't seem to be any plots in the `julia` pdf files that are being generated. Any ideas?
