### ISSUE TITLE
Watch out for Julia 1.5 

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#876]
An error report was forwarded my way by @jstac about the Jupyter setup not working in 1.5. 

Issues resolved when opening in a directory without pre-existing TOML. 

Could be connected to https://github.com/JuliaLang/IJulia.jl/issues/939.

**Comment by jlperla** [comment]
Ah thanks Arnav.  I will take a look soon.

**Comment by jlperla** [comment]
I am going to close this unless we see a specific error report.  At this point it sounds like there are issues with OSX at particular versions unreleated to anything we have done.

Since we don't fix the IJulia version in our manifest, it is out of our hands.
