### ISSUE TITLE
Replace REPL Screenshots with Text

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#9]
cc: @jstac, @natashawatkins, @mmcky, etc. 

One thing @Nosferican, @jlperla and I discussed was replacing screenshots like: 

<img width="871" alt="44611767-24eaf880-a7b8-11e8-9a70-00b4fa900704" src="https://user-images.githubusercontent.com/5009477/44684584-4ccb9d80-a9fe-11e8-95e1-9721d295a22a.png">

with something like: 

```
arnavsood@Arnavs-MacBook-Pro:~/research/lecture-source-jl$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.0 (2018-08-08)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> 
```

for compactness and upgradability. Let me know if you concur. If not, we can close this issue.

**Comment by natashawatkins** [comment]
I can see how that would be a little easier to maintain - but it could be kind of confusing to users because it's not technically in a jupyter code block. Also it would still need to be updated right?

**Comment by arnavs** [comment]
For sure, would still need to update, at least until Jupyter has some kind of `repl` mode. I just think it's easier to copy/paste some text than to replace an image.

**Comment by jlperla** [comment]
How many screenshots are there?  If it is just a few, then I think it is better off just keeping an image so that people can visually see that it is a console.  It is not like these get modified very often.  But I don't have a strong feelings.

**Comment by arnavs** [comment]
There are just a few. Sure, I don't have an issue leaving it.
