### ISSUE TITLE
Plots, GR, and Trust

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#98]
What is the basic plan with trust and the jupyter notebooks for QE?  One place this comes up is in the plotting, since `svg+xml` is not a trusted mimetype.  If we want the notebooks to load up and have the figures visible without running them, then there are two choices:
1. Put `gr(fmt="png")`  or something like that in front, which chagnes the svg into `png` - not requiring trust
2. Teach users to go `Trust Notebook` when they open them.

Part of the quetsion is also whether the rest of the QE output will work with the generated notebooks if they are not trusted?  If we have to trust them regardless, then changing to `png` is not worth it.

**Comment by jstac** [comment]
@mmcky This is above my pay grade.  Do you have any thoughts?

**Comment by jlperla** [comment]
@mmcky @jstac :  Yeah, this is a tricky issue here, but is also a question of how users are intended to access the notebooks.  Do we envision that they would be able to open them up and "work" without realizing they need to manually trust them?  If so, then we can try to make sure that the Julia based plots don't break that requirement.  You might want to check in with `matplotlib` as well ffor the appropriate mime-types.

More generally, this isn't a Julia-specific issue, but rather a Jupyter one.  The place where this would come up with the Jupinx based build process would mostly be about whether HTML or javascript is used anywhere.  See https://ipython.org/ipython-doc/3/notebook/security.html

**Comment by arnavs** [comment]
Most of this is above my pay grade is well, but an auto-trust feature would make the rewriting process a bit easier. Some Jupyter operations (notably switching kernels) don't seem to work unless the notebook is trusted.

**Comment by jlperla** [comment]
Well, hopefully they don't need to switch kernels at all.  Were there other things that happen in normal operations?  I am not sure an `auto-trust` feature is possible as it seems to break the jupyter security model, but we could work to avoid things which require trust.

**Comment by arnavs** [comment]
@jlperla I don't think so. And I'm not sure that you need to necessarily trust the notebook to make this work. But I do find that, whenever notebook operations don't seem to be working, I can trust the notebook and resolve the problem.

**Comment by jstac** [comment]
In my experience, when users need to do something manual for the notebooks to run, even if you put a big notification with flashing lights, they will completely ignore it and then complain when the notebook doesn't run.

**Comment by mmcky** [comment]
@jlperla the build process itself won't be an issue as because you can run the notebooks in `trust` from the command line - however the user point of view is more difficult. As you say it kind of breaks the security model. It will be interesting to see what happens if we use already executed notebooks (as the download link) -- will they detect being run on a new machine?

**Comment by mmcky** [comment]
In our `Docker` environments in the past we have used:

```
RUN find /home/. -name '*.ipynb' -exec jupyter trust {} \;
```

which enables trust over a collection of notebooks. This is how we remove the trust issue for ``tmpnb`` instances for workshops etc.

**Comment by jlperla** [comment]
>  will they detect being run on a new machine?

Is there anything in particular that requires trust that you can think of for setting up a test?  The only one that has jumped out at me was the `svg` mimetype.  Do you do anything tricky with HTML or javascript in the headers, for equations, or for references?
